	.Z80
;************************************************
;* Load Program für Boot Loader				
;* Der Boot Loader muss sich an Adresse 1000H   
;* befinden							
;* 80 Spur Laufwerke   1K pro Sektor Boot       
;* 				
;* U. Haumann 07.05.2026
;************************************************



	ORG	0100H		

OFFSET	EQU	0A000H		;damit BIOS Start bei EA00h
CPMB		EQU	03400H+OFFSET	;start cp/m
BIOS		EQU	04A00H+OFFSET	;start bios
BOOTP		EQU	01000H		;Hier muss sich das Boot Programm befinden

WBOOT0:
;
		LD	SP,0FFH		;start of stack
;
		LD	HL,BOOTP		;START ADRESSE Boot Loader
		LD	B,1			;ANZAHL DER SEKTOREN  A 1024 BYTES
		LD	D,0			;START BEI TRACK 0 Sektor 1, 1=bootsektor
		LD	E,1			;
RDSEC:
		PUSH	HL
		PUSH	DE
		PUSH	BC
		LD	C,11010000B	;laufwerk 0 double dense mini
		LD	B,2			;1=read 2=Write
		CALL	0F027H		;Monitor Einsprung Mini Laufwerk
		POP	BC
		POP	DE
		POP	HL
		JP	C,0F01EH		;monitor aufrufen bei fehler (Restart)
				
		JP	BIOS			;Fertig start coldbios

		END





