	.z80
		;*********************************************************************
		;* Universal Formatierer fuer Mini/Maxi                              *
		;* Rev 1.22 (C) 1984 Rolf-Dieter Klein / JS                          *
		;* FLO2-Baugruppe / MC/ NDR/                                         *
		;* FLO1-Baugruppe MC                                                 *
		;* 31.05.2026 *dg* Quellcode der Version 1.22 aus COM-Datei          *
		:                  wiederhergestellt                                 *
		;*********************************************************************
	flo0 equ 0c0h 	; FLO2-Mini/Maxi.
	flo1 equ 0c1h
	flo2 equ 0c2h
	flo3 equ 0c3h
	flo4 equ 0c4h
		;
	floa0 equ 040h 	; FLO1-Maxi
	floa1 equ 041h
	floa2 equ 042h
	floa3 equ 043h
	floa4 equ 044h
		;
	flob0 equ 030h 	; FLO1-Mini
	flob1 equ 031h
	flob2 equ 032h
	flob3 equ 033h
	flob4 equ 034h
		;
		; arbeitet unabhaengig vom CP/M - Betriebsystem.
	jp start 	; Hauptprogr.

co::	jp 0f009h 	; Ausgabe eines Zeichens in C

ci::	; v1.22
	call 0f003h 	; Eingabe eines Zeichens nach A
	and 7Fh
	ret

int::
	pop af  	; spez. Int-Routine
	in a,(floa0)
	in a,(flob0)
	in a,(flo0) 	; Status flo ist wichtig
	ei
	reti  	; ok fertig

format::		; Universal Formatierer
	ld hl,fmsg 
	call print
	in a,(floa0) 	; ggf. bei gemischtem Betrieb auch
	in a,(flob0)   	; andere Ports loeschen
	in a,(flo0) 	; alle Interrupts loeschen
		;
	im 1  	; Mode 1, RST-7 verwenden
	ld a,0c3h 	; Sprungvektor setzen
	ld (38h),a
	ld hl,int
	ld (39h),hl 	; auf Interruptroutine
		; 
	call rstore 	; Auf Spur 0 bringen
		;
	xor a
	ld (akttrk),a  	; Start bei Spur 0
	ld a,(spuren) 	; Anzahl Spuren
	ld b,a
loop::
	push bc
	call ecmachk 	; falls Spur 0, und ecma70
	call gentrack 	; Spur generieren
	call form 	; und formatierenŠ	call errchk
	ld a,(kopf)
;1 	if a=1  	; Seite 1 auch
	CP 1  
	JP NZ,.L1
	ld a,(laufwerk) 	; Rueckseite setzen
	or 80h  	; aber kein Side-sel
	ld (laufwerk),a
	ld a,(sideflag)
;2 	if a<>0
	OR A
	JP Z,.L2
	ld a,80h
	ld (sidesel),a 	; setzen
;2 	endif
.L2:
	call gentrack
	call form
	call errchk
	ld a,(laufwerk)
	and 7fh
	ld (laufwerk),a   
	xor a
	ld (sidesel),a
;1 	endif
.L1:
	ld a,(akttrk)
	inc a
	ld (akttrk),a
	ld b,a
	ld a,(spuren)
;1 	if a<>b
	CP b
	JP Z,.L3
	call stepin
;1 	endif
.L3:
	ld c,'F'
	call co 	; Meldung FFFFF ausgeben bei jeder Spur ein F
	pop bc
	djnz loop
		; Verify
	ld hl,vmsg
	call print
	call rstore
	xor a
	ld (akttrk),a  	; Start bei Spur 0
	ld a,(spuren) 	; Anzahl Spuren
	ld b,a
loop1::
	push bc
	call ecmachk
	call verify
	ld a,(kopf)
;1 	if a=1
	CP 1
	JP NZ,.L4
	ld a,(laufwerk)
	or 80h
	ld (laufwerk),a
	ld a,(sideflag)
;2 	if a<>0
	OR A
	JP Z,.L5Š	ld a,80h
	ld (sidesel),a 	; setzen
;2 	endif
.L5:
	call verify
	ld a,(laufwerk)
	and 7fh
	ld (laufwerk),a 
	xor a
	ld (sidesel),a 	; wieder Seite 0
;1 	endif
.L4:
	ld a,(akttrk)
	inc a
	ld (akttrk),a
	ld b,a
	ld a,(spuren)
;1 	if a<>b
	CP b
	JP Z,.L6
	call stepin
;1 	endif
.L6:
	ld c,'V' 
	call co 	; VVVVV fuer Verify
	pop bc
	djnz loop1
	call rstore 	; und am Schluss auf 0 zurueck
	ret

ecmachk:
	ld a,(ecma)
	or a
	ret z  	; 0=kein ECMA70 Format
	xor a
	ld (minimax),a 	; immer Minilaufwerk
	ld a,(akttrk) 	; = Spur 0, dann SD-Formatieren
;1 	if a=0
	OR A
	JP NZ,.L7
	ld hl,128
	ld (anzbyte),hl
	ld a,0 	; erste Spur einfache Dichte
	ld (dichte),a 	;
	ld a,0
	ld (kopf),a 	; 16 x SD , 40 Spuren
	ld a,16
	ld (sektoren),a
	ld a,27
	ld (gaplen),a
	ld a,40
	ld (spuren),a
;1 	else
	JP .L8
.L7:
	ld hl,256 	; rest DD
	ld (anzbyte),hl
	ld a,1
	ld (dichte),a 	; DD
	ld a,0
	ld (kopf),a 	; nur einseitig
	ld a,16 	; Sektorenzahl
	ld (sektoren),a
	ld a,54
	ld (gaplen),a 	; STD GapŠ	ld a,40 	; und 40 Spuren
	ld (spuren),a
;1 	endif
.L8:
	ret
errchk:		; allgemeine Fehlerpruefroutine
	or a
	ret z  	; =0, Status ok
		; Track, Spur ausgeben
	push af 	; Fehlercode retten
	ld hl,tkmsg
	call print
	ld a,(akttrk)
	ld l,a
	ld h,0 
	call printhl
	ld hl,skmsg
	call print
	ld a,(aktsek)
	ld l,a
	ld h,0
	call printhl
	call crlf
		;
	pop af  	; Fehlercode zurueck
	bit 2,a
	ld hl,f0msg 	; error
;1 	if nz
	JP Z,.L9
	ld hl,f2msg
;1 	endif
.L9:
	bit 3,a
;1 	if nz
	JP Z,.L10
	ld hl,f3msg
;1 	endif
.L10:
	bit 4,a
;1 	if nz
	JP Z,.L11
	ld hl,f4msg
;1 	endif
.L11:
	bit 5,a
;1 	if nz
	JP Z,.L12
	ld hl,f5msg
;1 	endif
.L12:
	bit 6,a
;1 	if nz
	JP Z,.L13
	ld hl,f6msg
;1 	endif
.L13:
;1 	if nz
	JP Z,.L14
	ld hl,f6msg 	; dominant ist Fehler, Writeprot.
;1 	endif
.L14:
	call print
;1 	repeat
.L15:
	call ci
;1 	until a in ['W','w']
	CP 'W'
	JP Z,.L16
	CP 'w'Š	JP NZ,.L15
.L16:
	jp start 	; Stack adjust nicht noetig 
printhl:		; dezimale Ausgabe
	xor a
	push af
aus1:
	ld a,16
	ld bc,10 	; div 10
	ld de,0 	; Rest
	ex de,hl
divlp:
	push af
	sla e
	rl d
	rl l
	rl h
	set 0,e
	xor a
	sbc hl,bc
;1 	if c
	JP NC,.L17
	add hl,bc
	res 0,e
;1 	endif
.L17:
	pop af
	dec a
	jr nz,divlp
	ex de,hl 	; hl=erg, de=rest
		;
	ld a,e
	or 30h
	push af
	ld a,h
	or l
	jr nz,aus1
aus2:
	pop af
	or a
	ret z
	ld c,a
	call co
	jr aus2
gentrack::		; neue Spur erzeugen
	ld ix,formtab 	; Startadresse Formattabelle 
		; header ausgeben
	ld a,(dichte) 	; je nach dichte
;1 	if a=0
	OR A
	JP NZ,.L18
	ld b,16
	ld c,0ffh 	; fuellbyte 
;1 	else
	JP .L19
.L18:
	ld b,32 	; bei doppelter Dichte
	ld c,04eh
;1 	endif
.L19:
;1 	do b
.L20:
	ld (ix+0),c
	inc ix
;1 	enddo  	; Header wird abgelegt
	DEC BŠ	JP NZ,.L20
		; Sektorenschleife
	ld a,1
	ld (aktsek),a 	; aktueller Sektor
	ld a,(sektoren)
	ld b,a
;1 	do b
.L21:
	push bc
		; ID-Feld aufbereiten
	ld a,(dichte)
;2 	if a=0 	; SD
	OR A
	JP NZ,.L22
;3 	do b,6
	LD b,6
.L23:
	ld (ix+0),0
	inc ix
;3 	enddo
	DEC B
	JP NZ,.L23
	ld (ix+0),0feh 	; ID-Adress-Mark
	inc ix
	ld a,(akttrk)
	ld (ix+0),a  	; Track 0..n
	inc ix
	ld a,(sidesel) 	; fuer Side-Flag
	and 80h  	;
;3 	if a=0
	OR A
	JP NZ,.L24
	ld (ix+0),0  	; Seite 0
;3 	else
	JP .L25
.L24:
	ld (ix+0),1  	; Seite 1
;3 	endif
.L25:
	inc ix
	ld a,(aktsek)
	ld (ix+0),a  	; Sektor 1..n
	inc ix
	ld hl,(anzbyte) 	; 128,256,512,1024
	ld a,h  	; 0,1,2,4 da 80h,100h,200h,400h
;3 	if a=4
	CP 4
	JP NZ,.L26
	ld a,3
;3 	endif
.L26:
	ld (ix+0),a  	; 0,1,2,3 Laengenkennung
	inc ix
	ld (ix+0),0f7h 	; und CRC erzeugen
	inc ix
;3 	do b,11
	LD b,11
.L27:
	ld (ix+0),0ffh
	inc ix
;3 	enddo
	DEC B
	JP NZ,.L27
;3 	do b,6
	LD b,6
.L28:
	ld (ix+0),0
	inc ixŠ;3 	enddo
	DEC B
	JP NZ,.L28
	ld (ix+0),0fbh 	; Data Mark
	inc ix
;2 	else  	; DD
	JP .L29
.L22:
;3 	do b,12
	LD b,12
.L30:
	ld (ix+0),0
	inc ix
;3 	enddo
	DEC B
	JP NZ,.L30
;3 	do b,3
	LD b,3
.L31:
	ld (ix+0),0f5h
	inc ix
;3 	enddo
	DEC B
	JP NZ,.L31
	ld (ix+0),0feh 	; ID-Adress-Mark
	inc ix
	ld a,(akttrk)
	ld (ix+0),a  	; Track 0..n
	inc ix
	ld a,(sidesel) 	; fuer Side-Sel SSO
	and 80h
;3 	if a=0
	OR A
	JP NZ,.L32
	ld (ix+0),0  	; Seite 0
;3 	else
	JP .L33
.L32:
	ld (ix+0),1  	; Seite 1
;3 	endif
.L33:
	inc ix
	ld a,(aktsek)
	ld (ix+0),a  	; Sektor 1..n
	inc ix
	ld hl,(anzbyte) 	; 128,256,512,1024
	ld a,h  	; 0,1,2,4 da 80h,100h,200h,400h
;3 	if a=4
	CP 4
	JP NZ,.L34
	ld a,3
;3 	endif
.L34:
	ld (ix+0),a  	; 0,1,2,3 Laengenkennung
	inc ix
	ld (ix+0),0f7h 	; und CRC erzeugen
	inc ix
;3 	do b,22
	LD b,22
.L35:
	ld (ix+0),04eh
	inc ix
;3 	enddo
	DEC B
	JP NZ,.L35
;3 	do b,12
	LD b,12
.L36:
	ld (ix+0),0Š	inc ix
;3 	enddo
	DEC B
	JP NZ,.L36
;3 	do b,3
	LD b,3
.L37:
	ld (ix+0),0f5h
	inc ix
;3 	enddo
	DEC B
	JP NZ,.L37
	ld (ix+0),0fbh 	; Data Mark
	inc ix
;2 	endif
.L29:
		; Datenblock ablegen
	ld a,(filler) 	; Datenbyte
	ld c,a
	ld hl,(anzbyte) 	; 128,256,512,1024
;2 	do hl
.L38:
	ld (ix+0),c
	inc ix
;2 	enddo
	DEC HL
	LD A,H
	OR L
	JP NZ,.L38
		;
	ld (ix+0),0f7h 	; CRC ablegen danach
	inc ix
	ld a,(dichte)
;2 	if a=0
	OR A
	JP NZ,.L39
	ld c,0ffh  	; Datenbyte SD
;2 	else
	JP .L40
.L39:
	ld c,04eh  	; Datenbyte DD
;2 	endif
.L40:
	ld a,(gaplen)
	ld b,a  	; Gap 3 ablegen
;2 	do b
.L41:
	ld (ix+0),c
	inc ix
;2 	enddo
	DEC B
	JP NZ,.L41
		; alle Sektoren
	ld a,(aktsek)
	inc a
	ld (aktsek),a 	; neue Sektorennummer
	pop bc
;1 	enddo
	DEC B
	JP NZ,.L21
		; fuellen bis ende
	ld a,(dichte)
;1 	if a=0  	; SD
	OR A
	JP NZ,.L42
	ld c,0ffh 	; Gap 4
;1 	else  	; DDŠ	JP .L43
.L42:
	ld c,04eh
;1 	endif
.L43:
;1 	do hl,1000 	; Sicherheitshalber grosse Zahl
	LD hl,1000 
.L44:
	ld (ix+0),c   	; damit bis zum Indexpuls
	inc ix 	; keine Fremdbytes kommen
;1 	enddo
	DEC HL
	LD A,H
	OR L
	JP NZ,.L44
	ret
verify::		; pruefen einer Spur
	call wai  	; Head Settle Time
	ld a,1   	; beruecksichtigen
	ld (aktsek),a
	ld a,(sektoren)
	ld b,a
;1 	do b
.L45:
	push bc
	call read  	; einfach einlesen
	call errchk  	; =0 dann ok, sonst Meldung ausgeben
	ld a,(aktsek)
	inc a
	ld (aktsek),a
	pop bc
;1 	enddo
	DEC B
	JP NZ,.L45
	ret

wai::
	push bc 	; Warteschleife 40ms.. 10ms
	ld bc,0d05h
lp3::
	dec bc
	ld a,c
	or b
	jp nz,lp3
	pop bc
	ret
rstore::		; Auf Spur 0 bringen
	ld a,(user)
	or a  	; FLO2
	jp nz,rastore
	ld hl,250 	; Versuche max
r1st:
	push  hl
	in a,(flo0)
	call wai
	ei  	; Jetzt Int erlaubt
	call rexec
	di
	pop hl
	in a,(flo0) 	; Status pruefen
	and 80h 	; <>0 dann nicht ready
	jp z,r2st
	dec hl
	ld a,h
	or l  	; Anzahl versucheŠ	jr nz,r1st
		; FEHLER
	ld hl,rmsg
	call print
;1 	repeat
.L46:
	call ci
;1 	until a in ['W','w']
	CP 'W'
	JP Z,.L47
	CP 'w'
	JP NZ,.L46
.L47:
	jp start
rastore:
	cp 1  	; FLO1-Maxi
	jp nz,rbstore
	ld hl,250 	; Versuche max
ra1st:
	push  hl
	in a,(floa0)
	call wai
	ei  	; Jetzt Int erlaubt
	call raexec
	di
	pop hl
	in a,(floa0) 	; Status pruefen
	and 80h 	; <>0 dann nicht ready
	jp z,r2st
	dec hl
	ld a,h
	or l  	; Anzahl versuche
	jr nz,ra1st
		; FEHLER
	ld hl,rmsg
	call print
;1 	repeat
.L48:
	call ci
;1 	until a in ['W','w']
	CP 'W'
	JP Z,.L49
	CP 'w'
	JP NZ,.L48
.L49:
	jp start
rbstore:
	ld hl,250 	; Versuche max
rb1st:
	push  hl
	in a,(flob0)
	call wai
	ei  	; Jetzt Int erlaubt
	call rbexec 	; rev 1.2
	di
	pop hl
	in a,(flob0) 	; Status pruefen
	and 80h 	; <>0 dann nicht ready
	jp z,r2st
	dec hl
	ld a,h
	or l  	; Anzahl versuche
	jr nz,rb1st
		; FEHLER
	ld hl,rmsgŠ	call print
;1 	repeat
.L50:
	call ci
;1 	until a in ['W','w']
	CP 'W'
	JP Z,.L51
	CP 'w'
	JP NZ,.L50
.L51:
	jp start

r2st:		; fertig
	ret

rexec::		; Ausfuehrung
	call setup
	ld a,0bh 	; Rstore ohne Verify
	out (flo0),a
	halt  	; ueber INT zurueck

raexec::		; Ausfuehrung
	call setup
	ld a,0bh 	; Rstore ohne Verify
	out (floa0),a
	halt  	; ueber INT zurueck

rbexec::		; Ausfuehrung
	call setup
	ld a,0bh 	; Rstore ohne Verify
	out (flob0),a
	halt  	; ueber INT zurueck

stepin::		; Step ausfuehren
	call wai 	; aber erst nach Delay, sonst
	ei     	; gehen Tracks verloren
	call stpexec
	di
	ret

stpexec::
	call setup 	; Laufwerk und Dichte
	ld a,(user)
;1 	if a=0
	OR A
	JP NZ,.L52
	ld a,5bh
	out (flo0),a 	; Step ohne Verify
;1 	elseif a=1
	JP .L53
.L52:
	CP 1
	JP NZ,.L54
	ld a,5bh
	out (floa0),a
;1 	elseif a=2
	JP .L53
.L54:
	CP 2
	JP NZ,.L55
	ld a,5bh 
	out (flob0),a
;1 	endif
.L55:
.L53:
	halt 
Šread:
	ld b,2
read1:
	push bc
	ei
	call readex
	di
	pop bc  	; Fehlerzaehler
	ld a,(user)
;1 	if a=0
	OR A
	JP NZ,.L56
	in a,(flo0) 	; Status beim Lesen pruefen
;1 	elseif a=1
	JP .L57
.L56:
	CP 1
	JP NZ,.L58
	in a,(floa0)
;1 	elseif a=2
	JP .L57
.L58:
	CP 2
	JP NZ,.L59
	in a,(flob0)
;1 	endif
.L59:
.L57:
	and 00111100b 	; =0 dann ok
	ret z
	djnz read1 	; max Retry
	ret
readex:
	call setup 	; Dichtecode setzen, Head ist down.
	ld a,(user)
;1 	if a=0
	OR A
	JP NZ,.L60
	ld a,(aktsek)
	out (flo2),a 	; Sektor definieren
	ld hl,formtab 	; dorthin Daten legen 
	ld c,flo3 	; Datenport
	ld a,(sidesel) 	; fuer Side-Control
	and 80h
	rlca  	; bit 0
	rlca  	; bit 1
	and 00000010b 	; 1=Seite 1
	add a,88h 	; kein Delay abwarten, head ist down
	out (flo0),a 	; und Befehl geben
red1:
	in a,(flo4)
	rlca
	jp nc,red1 	; warten bis DRQ-da ist
	ini  	; Daten ablegen
	jp red1 	; bis alle Daten gelesen, dann Interrupt 
;1 	elseif a=1 	; flo 1 maxi
	JP .L61
.L60:
	CP 1 
	JP NZ,.L62
	ld a,(aktsek)
	out (floa2),a 	; Sektor definieren
	ld hl,formtab 	; dorthin Daten legen 
	ld c,floa3 	; Datenport
	ld a,(sidesel) 	; fuer Side-Control
	and 80hŠ	rlca  	; bit 0
	rlca  	; bit 1
	and 00000010b 	; 1=Seite 1
	add a,88h 	; kein Delay abwarten, head ist down
	out (floa0),a 	; und Befehl geben
raed1:
	in a,(floa4)
	rlca
	jp nc,raed1 	; warten bis DRQ-da ist
	ini  	; Daten ablegen
	jp raed1 	; bis alle Daten gelesen, dann Interrupt 
;1 	elseif a=2 	; flo1 Mini
	JP .L61
.L62:
	CP 2 
	JP NZ,.L63
	ld a,(aktsek) 
	out (flob2),a 	; Sektor definieren
	ld hl,formtab 	; dorthin Daten legen 
	ld c,flob3 	; Datenport
	ld a,(sidesel) 	; fuer Side-Control
	and 80h
	rlca  	; bit 0
	rlca  	; bit 1
	and 00000010b 	; 1=Seite 1
	add a,88h 	; kein Delay abwarten, head ist down
	out (flob0),a 	; und Befehl geben
rbed1:
	in a,(flob4)
	rlca
	jp nc,rbed1 	; warten bis DRQ-da ist
	ini  	; Daten ablegen
	jp rbed1 	; bis alle Daten gelesen, dann Interrupt 
;1 	endif
.L63:
.L61:
	ret 

setup::
	push bc
	ld a,(laufwerk) 	; Laufwerkscode
	ld b,a 
	ld a,(dichte)
;1 	if a=0   	; SD
	OR A
	JP NZ,.L64
	ld a,b
	or 10h
	ld b,a
;1 	endif
.L64:
	ld a,(minimax)
;1 	if a=0   	; Mini
	OR A
	JP NZ,.L65
	ld a,b
	or 20h
	ld b,a
;1 	endif
.L65:
	ld a,(user)
;1 	if a=0   	; FLO2
	OR A
	JP NZ,.L66
	; v1.22
	LD A,(flotyp)
	CP 01h
	JP NZ,L0653
	
	ld a,b  	; OK Code fertig
	XOR 10h
	JP L0654
L0653:
	LD a,b
L0654:
	pop bc
	out (flo4),a	;
;1 	elseif a=1  	; MAXI
	JP .L67
.L66:
	CP 1  
	JP NZ,.L68
	ld a,b
	pop bc
	xor 10h  	; DENSE invertiert bei FLO1
	out (floa4),a
;1 	elseif a=2
	JP .L67
.L68:
	CP 2
	JP NZ,.L69
	ld a,b
	pop bc
	xor 10h  	; DENSE invertiert bei FLO1
	out (flob4),a
;1 	endif
.L69:
.L67:
	ret
form::		; Formatieren einer Spur.
	call wai
	ei
	call fmt
	di
	ld a,(user)
;1 	if a=0
	OR A
	JP NZ,.L70
	in a,(flo0) 	; pruefen auf Schreibschutz, Datalost
;1 	elseif a=1
	JP .L71
.L70:
	CP 1
	JP NZ,.L72
	in a,(floa0)
;1 	elseif a=2
	JP .L71
.L72:
	CP 2
	JP NZ,.L73
	in a,(flob0)
;1 	endif
.L73:
.L71:
	and 44h
	ret

fmt::
	call setup 	; Dichte einstellen etc., auf Port FLO4
	ld a,(user)
;1 	if a=0  	; FLO 2
	OR A
	JP NZ,.L74
	ld hl,formtab 	; Startadresse 
	ld c,flo3 	; Datenport
	ld a,(sidesel) 	; Side-Flag setzen, fuer SSO-Ausgang
	and 80h 	; wenn Sideflag auf 80h gesetzt wird
	rlca  	; bit 0
	rlca  	; bit 1
	and 00000010b 	; 1=Seite 1
	or 0f4h 	; Formatier-Befehl+nicht documentierter
	out (flo0),a 	; Side-Select-Befehl fuer SSO
fmtlp::
	in a,(flo4) 	; drq int head
	rlca  	; bit 7 ins carryŠ	jp nc,fmtlp 	; 0=warten 1=fertig i
	outi  	; und Byte ausgeben
	jp fmtlp 	; durch INT wird die Routine gestoppt.
;1 	elseif a=1 	; FLO1 maxi
	JP .L75
.L74:
	CP 1 
	JP NZ,.L76
	ld hl,formtab 	; Startadresse 
	ld c,floa3 	; Datenport
	ld a,(sidesel) 	; Side-Flag setzen, fuer SSO-Ausgang
	and 80h 	; wenn Sideflag auf 80h gesetzt wird
	rlca  	; bit 0
	rlca  	; bit 1
	and 00000010b 	; 1=Seite 1
	or 0f4h 	; Formatier-Befehl+nicht documentierter
	out (floa0),a 	; Side-Select-Befehl fuer SSO
famtlp::
	in a,(floa4) 	; drq int head
	rlca  	; bit 7 ins carry
	jp nc,famtlp 	; 0=warten 1=fertig i
	outi  	; und Byte ausgeben
	jp famtlp 	; durch INT wird die Routine gestoppt.
;1 	elseif a=2 	; FLO1 mini
	JP .L75
.L76:
	CP 2 
	JP NZ,.L77
	ld hl,formtab 	; Startadresse 
	ld c,flob3 	; Datenport
	ld a,(sidesel) 	; Side-Flag setzen, fuer SSO-Ausgang
	and 80h 	; wenn Sideflag auf 80h gesetzt wird
	rlca  	; bit 0
	rlca  	; bit 1
	and 00000010b 	; 1=Seite 1
	or 0f4h 	; Formatier-Befehl+nicht documentierter
	out (flob0),a 	; Side-Select-Befehl fuer SSO
fbmtlp::
	in a,(flob4) 	; drq int head
	rlca  	; bit 7 ins carry
	jp nc,fbmtlp 	; 0=warten 1=fertig i
	outi  	; und Byte ausgeben
	jp fbmtlp 	; durch INT wird die Routine gestoppt.
;1 	endif
.L77:
.L75:
	ret
start::
		;
schleife::		; Hauptwiederholschleife
	ld hl,headtxt 	; wieder von vorne
	call print
		; 
;1 	repeat
.L78:
	call ci
;1 	until a in ['1'..'6']
	CP '6'+1
	JP NC,.L78
	CP '1'+0
	JP C,.L78
.L79:
	push af
	xor a
	ld (ecma),a 	; kein ECMA70,ist default.
	ld (user),a 	; Savety 0=flo2
	ld a,0e5hŠ	ld (filler),a 	; Filler ist normalerweise E5
	xor a
	ld (sidesel),a 	; std kein SSO verwenden
	ld (sideflag),a 	; auch nicht bei Kopfwechsel 
	pop af
;1 	if a='1' 	; Mini
	CP '1' 
	JP NZ,.L80
	xor a
	ld (minimax),a
	call setspur
	call setlw
	call setdichte
	call setsek
;1 	elseif a='2' 	; Maxi
	JP .L81
.L80:
	CP '2' 
	JP NZ,.L82
	ld a,1
	ld (minimax),a
	call setspur
	call setlw
	call setdichte
	call setsek
;1 	elseif a='3' 	; 8 Zoll
	JP .L81
.L82:
	CP '3' 
	JP NZ,.L83
	ld a,1
	ld (minimax),a
	ld hl,128 	; 128 Bytes pro Sektor
	ld (anzbyte),hl
	ld a,0
	ld (dichte),a 	; SD
	ld a,27 	; Gaplaenge
	ld (gaplen),a
	ld a,0
	ld (kopf),a 	; einseitig
	ld a,26 	; Sektorenzahl
	ld (sektoren),a
	ld a,77 	; 0..76
	ld (spuren),a 	; Spurenanzahl
;1 	elseif a='4' 	; ECMA 70
	JP .L81
.L83:
	CP '4' 
	JP NZ,.L84
	xor a
	ld (minimax),a 	; rev 1.1, loeschen
	ld a,1
	ld (ecma),a 	; Spezialformat SD erste Spur
	ld (sideflag),a 	; wenn rueckseite dann mit Bit
		; rest in ecma doppelt
	ld hl,256 	; rest DD
	ld (anzbyte),hl
	ld a,1
	ld (dichte),a 	; DD
	ld a,0
	ld (kopf),a 	; nur einseitig
	ld a,16 	; Sektorenzahl
	ld (sektoren),a
	ld a,54Š	ld (gaplen),a 	; STD Gap
	ld a,40 	; und 40 Spuren
	ld (spuren),a
;1 	elseif a='5' 	; NDR spezial
	JP .L81
.L84:
	CP '5' 
	JP NZ,.L85
	ld a,0 	; Mini
	ld (minimax),a
	ld hl,1024 	; Anzahl Bytes
	ld (anzbyte),hl
	ld a,1 	; DD
	ld (dichte),a
	ld a,54 	; Gaplaenge 3
	ld (gaplen),a
	ld a,5
	ld (sektoren),a
	ld a,1
	ld (kopf),a 	; Doppelseitig
	ld a,1
	ld (sideflag),a 	; und mit Side-Bit
	ld a,80 	; Spuren 0..79
	ld (spuren),a
;1 	elseif a='6' 	; ENDE
	JP .L81
.L85:
	CP '6' 
	JP NZ,.L86
	jp exit
;1 	endif
.L86:
.L81:
		;
	ld hl,menue7 	; FLO-Typ
	call print
;1 	repeat
.L87:
	call ci
;1 	until a in ['1'..'3',0dh]
	CP '4'+1
	JR NC,.L89
	CP '1'+0
	JP NC,.L88
.L89:
	CP 0dh
	JP NZ,.L87
.L88:
;1 	if a='2'
	CP '2'
	JP NZ,.L90
	ld a,1 	; flo1, maxi
;1 	elseif a='3'
	JP .L91
.L90:
	CP '3'
	JP NZ,.L92
	ld a,2 	; flo2, mini
;1 	else
	JP .L93
.L92:
	; v1.22
	CP '4'
	JP NZ,L0838
	LD A,01h
	LD (flotyp),A

	xor a  	; FLO2 mini/maxi
	JP .L91
	
L0838:	
	CP '1'
	JP NZ,.L91
	XOR A
	LD (flotyp),A
	
;1 	endif
.L93:
.L91:
	ld (user),a 	; ablegen
		;
inner::		; Schleife bei Laufwerksbestimmung
	ld hl,menue6 	; Laufwerk eingeben
	call print
;1 	repeat
.L94:
	call ci 	; 0..9Š;1 	until a in ['0'..'9']
	CP '9'+1
	JP NC,.L94
	CP '0'+0
	JP C,.L94
.L95:
;1 	if a in ['1'..'8']
	CP '8'+1
	JP NC,.L96
	CP '1'+0
	JP C,.L96
.L97:
;2 	if a='1'
	CP '1'
	JP NZ,.L98
	ld a,1
;2 	elseif a='2'
	JP .L99
.L98:
	CP '2'
	JP NZ,.L100
	ld a,2
;2 	elseif a='3'
	JP .L99
.L100:
	CP '3'
	JP NZ,.L101
	ld a,4
;2 	elseif a='4'
	JP .L99
.L101:
	CP '4'
	JP NZ,.L102
	ld a,8
;2 	elseif a='5'
	JP .L99
.L102:
	CP '5'
	JP NZ,.L103
	ld a,81h
;2 	elseif a='6'
	JP .L99
.L103:
	CP '6'
	JP NZ,.L104
	ld a,82h
;2 	elseif a='7'
	JP .L99
.L104:
	CP '7'
	JP NZ,.L105
	ld a,84h
;2 	elseif a='8'
	JP .L99
.L105:
	CP '8'
	JP NZ,.L106
	ld a,88h
;2 	endif
.L106:
.L99:
	ld (laufwerk),a
	ld a,(sideflag) 	; nur wenn Flag gesetzt.
;2 	if a<>0
	OR A
	JP Z,.L107
	ld a,(laufwerk)
	and 80h
;3 	if nz  	; 80h laden.
	JP Z,.L108
	ld (sidesel),a 	; wenn Flag, dann Rueckseite mit side-bit
;3 	endif  	; fuer ECMA-70 wichtig.Š.L108:
;2 	endif
.L107:
;1 	elseif a='9'
	JP .L109
.L96:
	CP '9'
	JP NZ,.L110
	jp schleife 	; neue Parameter
;1 	elseif a='0'
	JP .L109
.L110:
	CP '0'
	JP NZ,.L111
	jp exit 	; Ende
;1 	else
	JP .L112
.L111:
	jp inner 	; wiederholen
;1 	endif
.L112:
.L109:
		;
		; Formatierer aufrufen, wenn bereit
		; Controllwerte am Bildschirm ausgeben
;1 	repeat
.L113:
	call werteaus
	ld hl,formtxt
	call print
	call ci
;1 	until a in ['J','j','n','N',3]
	CP 'J'
	JP Z,.L114
	CP 'j'
	JP Z,.L114
	CP 'n'
	JP Z,.L114
	CP 'N'
	JP Z,.L114
	CP 3
	JP NZ,.L113
.L114:
;1 	if a in ['n','N']
	CP 'n'
	JP Z,.L116
	CP 'N'
	JP NZ,.L115
.L116:
	jp start 	; Neustarten, von vorne
;1 	endif
.L115:
;1 	if a=3
	CP 3
	JP NZ,.L117
	jp exit 	; Abbruch CTRL-C
;1 	endif
.L117:
	call format
		; Ende der Formatierung
	jp inner 	; und von vorne, mit gleichen Parametern
		;
exit::
	ld hl,fimsg
	call print
;1 	repeat
.L118:
	call ci
;1 	until a=0dh
	CP 0dh
	JP NZ,.L118
	im 0  	; Savety bei FLO1, ggf IM0-Mode verwendet
	call 0  	; daher ruecksetzen.
	retŠsetspur::
	ld hl,menue3
	call print
;1 	repeat
.L119:
	call ci
;1 	until a in ['1'..'5']
	CP '5'+1
	JP NC,.L119
	CP '1'+0
	JP C,.L119
.L120:
;1 	if a='1'
	CP '1'
	JP NZ,.L121
	ld a,35
;1 	elseif a='2'
	JP .L122
.L121:
	CP '2'
	JP NZ,.L123
	ld a,40
;1 	elseif a='3'
	JP .L122
.L123:
	CP '3'
	JP NZ,.L124
	ld a,70
;1 	elseif a='4'
	JP .L122
.L124:
	CP '4'
	JP NZ,.L125
	ld a,77
;1 	elseif a='5'
	JP .L122
.L125:
	CP '5'
	JP NZ,.L126
	ld a,80
;1 	endif
.L126:
.L122:
	ld (spuren),a
	ret
setlw::
	ld hl,menue4
	call print
;1 	repeat
.L127:
	call ci
;1 	until a in ['1'..'3']
	CP '3'+1
	JP NC,.L127
	CP '1'+0
	JP C,.L127
.L128:
;1 	if a='1'
	CP '1'
	JP NZ,.L129
	ld a,0  
	ld (kopf),a
;1 	elseif a='2'
	JP .L130
.L129:
	CP '2'
	JP NZ,.L131
	ld a,1
	ld (kopf),a
;1 	else
	JP .L132
.L131:
	ld a,1Š	ld (kopf),a
	ld a,1
	ld (sideflag),a 	; Seite 0 beginnt
;1 	endif
.L132:
.L130:
	ld (kopf),a 	; Anzahl der Koepfe-1
	ret

setdichte::
	ld hl,menue2
	call print
;1 	repeat
.L133:
	call ci
;1 	until a in ['1'..'2']
	CP '2'+1
	JP NC,.L133
	CP '1'+0
	JP C,.L133
.L134:
;1 	if a='1'
	CP '1'
	JP NZ,.L135
	ld a,0 	; einfache Dichte
;1 	else
	JP .L136
.L135:
	ld a,1 	; doppelte Dichte
;1 	endif
.L136:
	ld (dichte),a
	ret
setsek::
	ld a,(minimax)
;1 	if a=0  	; Mini
	OR A
	JP NZ,.L137
	ld a,(dichte)
;2 	if a=0 	; SD
	OR A
	JP NZ,.L138
	ld hl,menue5a
	call print
;3 	repeat
.L139:
	call ci
;3 	until a in ['1'..'3']
	CP '3'+1
	JP NC,.L139
	CP '1'+0
	JP C,.L139
.L140:
;3 	if a='1'
	CP '1'
	JP NZ,.L141
	ld hl,128
	ld (anzbyte),hl
	ld a,16
	ld (sektoren),a
	ld a,27
	ld (gaplen),a
;3 	elseif a='2'
	JP .L142
.L141:
	CP '2'
	JP NZ,.L143
	ld hl,128
	ld (anzbyte),hl
	ld a,18Š	ld (sektoren),a
	ld a,10
	ld (gaplen),a
;3 	elseif a='3'
	JP .L142
.L143:
	CP '3'
	JP NZ,.L144
	ld hl,256
	ld (anzbyte),hl
	ld a,10
	ld (sektoren),a
	ld a,16
	ld (gaplen),a
;3 	endif
.L144:
.L142:
;2 	else  	; DD
	JP .L145
.L138:
	ld hl,menue5b
	call print
;3 	repeat
.L146:
	call ci
;3 	until a in ['1'..'4']
	CP '4'+1
	JP NC,.L146
	CP '1'+0
	JP C,.L146
.L147:
;3 	if a='1'
	CP '1'
	JP NZ,.L148
	ld hl,256
	ld (anzbyte),hl
	ld a,16
	ld (sektoren),a
	ld a,54
	ld (gaplen),a
;3 	elseif a='2'
	JP .L149
.L148:
	CP '2'
	JP NZ,.L150
	ld hl,512
	ld (anzbyte),hl
	ld a,9
	ld (sektoren),a
	ld a,54
	ld (gaplen),a
;3 	elseif a='3'
	JP .L149
.L150:
	CP '3'
	JP NZ,.L151
	ld hl,512
	ld (anzbyte),hl
	ld a,10
	ld (sektoren),a
	ld a,40
	ld (gaplen),a
;3 	elseif a='4'
	JP .L149
.L151:
	CP '4'
	JP NZ,.L152
	ld hl,1024
	ld (anzbyte),hl
	ld a,5Š	ld (sektoren),a
	ld a,54
	ld (gaplen),a
;3 	endif
.L152:
.L149:
;2 	endif
.L145:
;1 	else  	; Maxi
	JP .L153
.L137:
	ld a,(dichte)
;2 	if a=0 	; SD
	OR A
	JP NZ,.L154
	ld hl,menue5c
	call print
;3 	repeat
.L155:
	call ci
;3 	until a in ['1'..'2']
	CP '2'+1
	JP NC,.L155
	CP '1'+0
	JP C,.L155
.L156:
;3 	if a='1'
	CP '1'
	JP NZ,.L157
	ld hl,128
	ld (anzbyte),hl
	ld a,26
	ld (sektoren),a
	ld a,27
	ld (gaplen),a
;3 	else
	JP .L158
.L157:
	ld hl,256
	ld (anzbyte),hl
	ld a,15
	ld (sektoren),a
	ld a,27
	ld (gaplen),a
;3 	endif
.L158:
;2 	else   	; DD
	JP .L159
.L154:
	ld hl,menue5d
	call print
;3 	repeat
.L160:
	call ci
;3 	until a in ['1'..'6']
	CP '6'+1
	JP NC,.L160
	CP '1'+0
	JP C,.L160
.L161:
;3 	if a='1'
	CP '1'
	JP NZ,.L162
	ld hl,256
	ld (anzbyte),hl
	ld a,26
	ld (sektoren),a
	ld a,54
	ld (gaplen),a
;3 	elseif a='2'
	JP .L163
.L162:
	CP '2'Š	JP NZ,.L164
	ld hl,512
	ld (anzbyte),hl
	ld a,14
	ld (sektoren),a
	ld a,54
	ld (gaplen),a
;3 	elseif a='3'
	JP .L163
.L164:
	CP '3'
	JP NZ,.L165
	ld hl,512
	ld (anzbyte),hl
	ld a,15
	ld (sektoren),a
	ld a,54
	ld (gaplen),a
;3 	elseif a='4'
	JP .L163
.L165:
	CP '4'
	JP NZ,.L166
	ld hl,512
	ld (anzbyte),hl
	ld a,16
	ld (sektoren),a
	ld a,40
	ld (gaplen),a
;3 	elseif a='5'
	JP .L163
.L166:
	CP '5'
	JP NZ,.L167
	ld hl,1024
	ld (anzbyte),hl
	ld a,8
	ld (sektoren),a
	ld a,54
	ld (gaplen),a
;3 	elseif a='6'
	JP .L163
.L167:
	CP '6'
	JP NZ,.L168
	ld hl,1024
	ld (anzbyte),hl
	ld a,9
	ld (sektoren),a
	ld a,40
	ld (gaplen),a
;3 	endif
.L168:
.L163:
;2 	endif
.L159:
;1 	endif
.L153:
	ret
print::
	ld a,(hl)
;1 	while a<>0 
.L169:
	OR A
	JP Z,.L170
	ld c,a
	call co
	inc hl
	ld a,(hl)
;1 	endwhileŠ	JP .L169
.L170:
	ret

werteaus:		; Conrolle, Werte ausgeben
	ld c,1ah
	call co 	; Bildschirm loeschen
	ld a,(minimax)
;1 	if a=0  	; 0=Mini
	OR A
	JP NZ,.L171
	ld hl,tmini
;1 	else
	JP .L172
.L171:
	ld hl,tmaxi
;1 	endif
.L172:
	call print
	ld a,(user)
;1 	if a=0  	; FLO 2
	OR A
	JP NZ,.L173
	
	; v1.22
	LD A,(flotyp)
	OR A
	JP NZ,L0BD4
	LD HL,tflo2
	JP L0BD7
	
L0BD4:	
	ld hl,tflo1c
L0BD7:
;1 	elseif a=1
	JP .L174
.L173:
	CP 1
	JP NZ,.L175
	ld hl,tflo1a
;1 	else a=2
	JP .L176
.L175:
	ld hl,tflo1b
;1 	endif
.L176:
.L174:
	call print
	ld a,(dichte)
;1 	if a=0  	; 0=SD
	OR A
	JP NZ,.L177
	ld hl,tfm
;1 	else
	JP .L178
.L177:
	ld hl,tmfm
;1 	endif
.L178:
	ld a,(ecma)
;1 	if a=1
	CP 1
	JP NZ,.L179
	ld hl,tecma 	; Sonderfall, Ecma-Format
;1 	endif
.L179:
	call print
	call crlf
	call crlf
	ld hl,tspuren
	call print
	ld a,(spuren)
	ld l,a
	ld h,0
	call printhl 	; Anzahl Spuren
	call crlf
	ld hl,tsektoren
	call print
	ld a,(sektoren)
	ld l,a
	ld h,0Š	call printhl 	; Anzahl Sektoren
	call crlf
	ld hl,tbytes
	call print
	ld hl,(anzbyte)
	call printhl 	; Bytes pro Sektor
	call crlf
		;
	ld hl,tlaufwerk
	call print
	ld a,(laufwerk)
	and 0fh 	; 1,2,4,8
;1 	if a=1
	CP 1
	JP NZ,.L180
	ld c,'A'
;1 	elseif a=2
	JP .L181
.L180:
	CP 2
	JP NZ,.L182
	ld c,'B'
;1 	elseif a=4
	JP .L181
.L182:
	CP 4
	JP NZ,.L183
	ld c,'C'
;1 	elseif a=8
	JP .L181
.L183:
	CP 8
	JP NZ,.L184
	ld c,'D'
;1 	else
	JP .L185
.L184:
	ld c,'?'
;1 	endif
.L185:
.L181:
	call co
	call crlf
	call crlf
		; 
	ld a,(kopf)
;1 	if a=1  	; zweiseitig
	CP 1  
	JP NZ,.L186
	ld a,(sideflag)
;2 	if a=0 	; ohne SSO
	OR A
	JP NZ,.L187
	ld hl,tzweiseitig
;2 	else  	; mit SSO
	JP .L188
.L187:
	ld hl,tzweisso
;2 	endif
.L188:
	call print
;1 	else  	; einseitig
	JP .L189
.L186:
	ld a,(laufwerk) 
	and 80h
;2 	if z  	; vorderseite
	JP NZ,.L190
	ld hl,teinseitig
	call printŠ;2 	else  	; rueckseite
	JP .L191
.L190:
	ld a,(sideflag)
;3 	if a=0 	; ohne sso
	OR A
	JP NZ,.L192
	ld hl,trueckseite
;3 	else  	; sso
	JP .L193
.L192:
	ld hl,truecksso
;3 	endif
.L193:
	call print
;2 	endif
.L191:
;1 	endif
.L189:
	call crlf 
	call crlf
		; Kapazitaet ausrechnen
	ld hl,tkap
	call print
	ld a,(sektoren)
	ld l,a
	ld h,0
	ld a,(spuren)
	ld e,a
	ld d,0
	call mulhlde 	; sektoren*tracks
	ld a,(kopf)
;1 	if a=1
	CP 1
	JP NZ,.L194
	ld de,2
	call mulhlde 	; wenn zweiseitig, dann doppelt
;1 	endif
.L194:
	ld de,(anzbyte) 	; de=1024,512,256,128
		; de=400h,200h,100h,80h
;1 	if d=0
	LD A,d
	OR A
	JP NZ,.L195
;2 	do b,3 	; div 8
	LD b,3 
.L196:
	sra h
	rr l
;2 	enddo
	DEC B
	JP NZ,.L196
;1 	elseif d=1
	JP .L197
.L195:
	LD A,d
	CP 1
	JP NZ,.L198
	sra h  	; div 4
	rr l
	sra h
	rr l
;1 	elseif d=2
	JP .L197
.L198:
	LD A,d
	CP 2
	JP NZ,.L199
	sra h  	; div 2Š	rr l
;1 	elseif d=4
	JP .L197
.L199:
	LD A,d
	CP 4
	JP NZ,.L200
	nop  	; hl = KBytes
;1 	endif
.L200:
.L197:
	call printhl 	; ausgeben
	ld hl,tkap1
	call print
	call crlf
	ret

mulhlde:		; fuer Kapazitaetsbestimmung
		; hl*de -> hl
	ld a,16
	push de
	pop bc
	ld de,0
	ex de,hl
mullp:
	push af
	bit 0,e
;1 	if nz
	JP Z,.L201
	add hl,bc
;1 	endif
.L201:
	sra h
	rr l
	rr d
	rr e
	pop af
	dec a
	jr nz,mullp
	ex de,hl 	; nur lsb nach hl
	ret

crlf:
	ld hl,tcrlf
	call print
	ret
tkap:
	defb 'Speicherkapazitaet :  ',0
tkap1:
	defb ' KBytes',0
tmini:
	defb 'Mini-Laufwerk  ',0
tmaxi:
	defb 'Maxi-Laufwerk  ',0
tflo2:
	defb 'FLO2 (C0h)  ',0
tflo1a:
	defb 'FLO1 (40h)  ',0
tflo1b:
	defb 'FLO1 (30h)  ',0
tflo1c:
	defb 'FLO1 (C0h)  ',0
tfm:
	defb 'FM  ',0
tmfm:
	defb 'MFM  ',0
tecma:Š	defb 'ECMA70 ',0
tspuren:
	defb 'Anzahl Spuren    = ',0
tsektoren:
	defb 'Anzahl Sektoren  = ',0
tbytes:
	defb 'Bytes/pro Sektor = ',0
tlaufwerk:
	defb 'Laufwerk ',0
teinseitig:
	defb 'Vorderseite wird formatiert',0
trueckseite:
	defb 'Rueckseite wird formatiert',0
truecksso:
	defb 'Rueckseite wird mit SSO formatiert',0
tzweiseitig:
	defb 'beide Seiten werden formatiert',0
tzweisso:
	defb 'beide Seiten werden formatiert',0dh,0ah
	defb 'Seite 1 mit SSO, Seite 0 normal',0
formtxt::
	defb 0dh,0ah
	defb 'ACHTUNG Diskette wird formatiert',0dh,0ah
	defb 'Start = "J"',0dh,0ah
	defb 0
headtxt::
	defb 1ah,0dh,0ah
	defb ' Universal Formatierer  V 1.22 , Rolf-Dieter Klein / JS ',0dh,0ah
	defb ' (C) 1984, Muenchen ',0dh,0ah
	defb 0dh,0ah
	defb ' --   Bitte Systemdiskette herausnehmen    -- ',0dh,0ah
	defb ' -- und zu formatierende Diskette einlegen -- ',0dh,0ah
	defb 0dh,0ah
	defb 'Minilaufwerke (5 1/4") = 1',0dh,0ah
	defb 'Maxilaufwerke (8"    ) = 2',0dh,0ah
	defb 'Std  8" SD SD 77 Spur  = 3',0dh,0ah
	defb 'ECMA 70 DD SD 40 Spur  = 4',0dh,0ah
	defb 'NDR- DD DS 80 Spur     = 5',0dh,0ah
	defb 'ENDE                   = 6',0dh,0ah
	defb 0dh,0ah,0
menue2::
	defb 1ah,0dh,0ah
	defb 'einfache Schreibdichte = 1',0dh,0ah
	defb 'doppelte Schreibdichte = 2',0dh,0ah
	defb 0dh,0ah,0
menue3::
	defb 1ah,0dh,0ah
	defb '35 Spuren  = 1',0dh,0ah
	defb '40 Spuren  = 2',0dh,0ah
	defb '70 Spuren  = 3',0dh,0ah
	defb '77 Spuren  = 4',0dh,0ah
	defb '80 Spuren  = 5',0dh,0ah
	defb 0dh,0ah,0
menue4::
	defb 1ah,0dh,0ah
	defb 'Einseitiges Laufwerk     = 1',0dh,0ah
	defb 'Doppeltseitiges Laufwerk = 2',0dh,0ah
	defb 'Doppeltseitig und SSO    = 3',0dh,0ah
	defb 0dh,0ah,0
menue5a::		; einfache Dichte, Minifloppy
	defb 1ah,0dh,0ahŠ	defb '128 Bytes pro Sektor  (16 pro Track) = 1',0dh,0ah
	defb '128 Bytes pro Sektor  (18 pro Track) = 2',0dh,0ah
	defb '256 Bytes pro Sektor  (10 pro Track) = 3',0dh,0ah
	defb 0dh,0ah,0
menue5b::		; doppelte Dichte, Minifloppy
	defb 1ah,0dh,0ah
	defb '256 Bytes pro Sektor  (16 pro Track) = 1',0dh,0ah
	defb '512 Bytes pro Sektor  (9 pro Track)  = 2',0dh,0ah
	defb '512 Bytes pro Sektor  (10 pro Track) = 3',0dh,0ah
	defb '1024 Bytes pro Sektor (5 pro Track)  = 4',0dh,0ah
	defb 0dh,0ah,0
menue5c::		; einfache Dichte Maxifloppy
	defb 1ah,0dh,0ah
	defb '128 Bytes pro Sektor (26 pro Track) = 1',0dh,0ah
	defb '256 Bytes pro Sektor (15 pro Track) = 2',0dh,0ah
	defb 0dh,0ah,0
menue5d::		; doppelte Dichte Maxifloppy
	defb 1ah,0dh,0ah
	defb '256 Bytes pro Sektor (26 pro Track) = 1',0dh,0ah
	defb '512 Bytes pro Sektor (14 pro Track) = 2',0dh,0ah
	defb '512 Bytes pro Sektor (15 pro Track) = 3',0dh,0ah
	defb '512 Bytes pro Sektor (16 pro Track) = 4',0dh,0ah
	defb '1024 Bytes pro Sektor (8 pro Track) = 5',0dh,0ah
	defb '1024 Bytes pro Sektor (9 pro Track) = 6',0dh,0ah
	defb 0dh,0ah,0
menue6::
	defb 1ah,0dh,0ah
	defb 'Laufwerk              A = 1',0dh,0ah
	defb 'Laufwerk              B = 2',0dh,0ah
	defb 'Laufwerk              C = 3',0dh,0ah
	defb 'Laufwerk              D = 4',0dh,0ah
	defb 'Laufwerk A Rueckseite A = 5',0dh,0ah
	defb 'Laufwerk B Rueckseite B = 6',0dh,0ah
	defb 'Laufwerk C Rueckseite C = 7',0dh,0ah
	defb 'Laufwerk D Rueckseite D = 8',0dh,0ah
	defb 'NEUSTART    = 9',0dh,0ah
	defb 'ENDE        = 0',0dh,0ah
	defb 0dh,0ah,0
menue7:
	defb 1ah,0dh,0ah
	defb 'FLO2-Maxi/Mini (0C0h) = 1',0dh,0ah
	defb 'FLO1-Maxi (40h)       = 2',0dh,0ah
	defb 'FLO1-Mini (30h)       = 3',0dh,0ah
	defb 'FLO1-Maxi/Mini (0C0h) = 4',0dh,0ah
	defb 0dh,0ah,0
fmsg:
	defb 1ah,0dh,0ah
	defb 'Diskette wird formatiert ... bitte warten ',0dh,0ah
	defb 0dh,0ah,0
f6msg:
	defb 0dh,0ah
	defb 'Schreibschutz gesetzt',0dh,0ah
	defb 'Neustart = Taste W druecken',0dh,0ah,0
f5msg:
	defb 0dh,0ah
	defb 'Record Typ ist falsch',0dh,0ah
	defb 'Neustart = Taste W druecken',0dh,0ah,0
f4msg:
	defb 0dh,0ah
	defb 'Record nicht gefunden',0dh,0ah
	defb 'Neustart = Taste W druecken',0dh,0ah,0
f3msg:Š	defb 0dh,0ah
	defb 'CRC Fehler aufgetreten',0dh,0ah
	defb 'Neustart = Taste W druecken',0dh,0ah,0
f2msg:
	defb 0dh,0ah
	defb 'CPU zu langsam fuer gewaehltes Format-- Datenverlust',0dh,0ah
	defb 'hoeherer Takt erforderlich',0dh,0ah
	defb 'Neustart = Taste W druecken',0dh,0ah,0
f0msg:
	defb 0dh,0ah
	defb 'Fehler aufgetreten. Neustart = Taste W druecken',0dh,0ah,0
tkmsg:
	defb 0dh,0ah
	defb 'Track = ',0
skmsg:
	defb ', Sektor = ',0
tcrlf:
	defb 0dh,0ah,0
rmsg:
	defb 0dh,0ah
	defb 'Laufwerk nicht READY ... bitte pruefen:',0dh,0ah
	defb ' 1. Diskette falschherum eingelegt',0dh,0ah
	defb ' 2. Laufwerkstuere nicht geschlossen',0dh,0ah
	defb ' 3. falsche Laufwerksnummer angegeben',0dh,0ah
	defb ' 4. Laufwerksmotor dreht sich nicht',0dh,0ah
	defb ' 5. READY-Leitung nicht ok',0dh,0ah 
	defb 0dh,0ah
	defb 'Neustart = Taste W druecken',0dh,0ah,0
vmsg:
	defb 0dh,0ah
	defb 'Diskette wird geprueft ... bitte warten',0dh,0ah
	defb 0dh,0ah,0
fimsg:
	defb 1ah,0dh,0ah
	defb 'Systemdiskette in Laufwerk A einlegen,',0dh,0ah
	defb 'dann CR (carriage return) druecken.',0dh,0ah,0

	defb 0	; v1.22
	
user::	defb 0  	; NDR=1, MC+Term1=2, sonst=3
flotyp:	defb 0    	; 0=flo2, 1=flo1  max, 2=flo1 min
minimax::	defb 0  	; 0=Mini 1=Maxi
ecma::	defb 0  	; 1=ECMA70 Format (SD,128 auf TK0)
anzbyte::	defw 0  	; Anzahl der Bytes pro Sektor
filler::	defb 0e5h 	; Fuellbyte std=E5
dichte::	defb 0  	; 0=einfache Dichte, 1=doppelte Dichte
gaplen::	defb 0  	; Gap 3 Laenge zwischen Sektoren
spuren::	defb 0  	; Anzahl der Spuren
kopf::	defb 0  	; 0=einseitig, 1=zweiseitig
sektoren::	defb 0  	; Anzahl der Sektoren pro Spur
laufwerk::	defb 0  	; 1,2,4,8 = Laufwerkscode
		; 81,82,84,88 = Rueckseite
sidesel::	defb 0  	;0=Seite 0,SSO, 80h=Seite 1,SSO
sideflag::	defb 0  	; 0=SSO nicht verwenden
		;
akttrk::	defb 0  	; aktuelle Spur
aktsek::	defb 0  	; aktueller Sektor
		;
formtab::		; Formatierbereich, dorthin wird
		; ein Track gelegt.

	end start
