	.z80

	;*********************************************************************
	;* Universal Formatierer fuer Mini/Maxi                              *
	;* Rev 1.22 (C) 1984 Rolf-Dieter Klein / JS                          *
	;* FLO2-Baugruppe / MC / NDR                                         *
	;* FLO1-Baugruppe MC                                                 *
	;* 31.05.2026 *dg* Quellcode der Version 1.22 aus COM-Datei          *
	;*                 wiederhergestellt                                 *
	;* 03.07.2026 *dg* Quellcode ueberarbeitet und dokumentiert          *
	;*                 Binaer identisch zur Version 1.22                 *
	;*********************************************************************

	; arbeitet unabhaengig vom CP/M - Betriebsystem.
	; verwendet den Monitor

; IO ADDESSES FLO1/FLO2 Mini/Maxi
FLO0	EQU 0C0H	; Status/Command
FLO1	EQU 0C1H	; Track
FLO2	EQU 0C2H	; Sector
FLO3	EQU 0C3H	; Data
FLO4	EQU 0C4H	; Special FLO-Flags

; IO ADDESSES FLO1 Maxi
FLOA0	EQU 040H
FLOA1	EQU 041H
FLOA2	EQU 042H
FLOA3	EQU 043H
FLOA4	EQU 044H

; IO ADDESSES FLO1 Mini
FLOB0	EQU 030H
FLOB1	EQU 031H
FLOB2	EQU 032H
FLOB3	EQU 033H
FLOB4	EQU 034H

;-----------------------------------------------------------------------------

	JP START 	; Hauptprogramm

;-----------------------------------------------------------------------------

CONOUT:	JP 0F009H 	; Ausgabe eines Zeichens in C

;-----------------------------------------------------------------------------

CONIN:	CALL 0F003H 	; Eingabe eines Zeichens nach A
	AND 7FH
	RET

;-----------------------------------------------------------------------------
; Interrupt routine

INTR:	POP AF
	; reset interrupts
	IN A,(FLOA0)
	IN A,(FLOB0)
	IN A,(FLO0)
	EI
	RETI

;-----------------------------------------------------------------------------
; Universal Formatter

FORMAT:	LD HL,FMSG 
	CALL PRNMSG
	
	; reset interrupts
	IN A,(FLOA0) 	; ggf. bei gemischtem Betrieb auch
	IN A,(FLOB0)   	; andere Ports loeschen
	IN A,(FLO0) 	; alle Interrupts loeschen

	IM 1  		; MODE 1, RST-7 verwenden
	LD A,0C3H 	; Sprungvektor setzen (JP)
	LD (38H),A
	LD HL,INTR
	LD (39H),HL 	; auf Interruptroutine

	; --- format ---------------------------------------------------------

	CALL HOME 	; set head to track 0

	XOR A
	LD (CURTRK),A  	; start with track 0
	LD A,(TRKCNT) 	; number of tracks
	LD B,A

FORM1:	; format loop (tracks)

	; --- format side 0 ---
	
	PUSH BC
	CALL ECMACHK 	; check if track 0 and ECMA70
	CALL GENTRK 	; create track
	CALL FRMTRK 	; format track
	CALL ERRCHK
	
	LD A,(SSDS)
	CP 1
	JP NZ,FORM3	; -> single sided

	; --- double-sided,. format side 1 ---
	
	LD A,(DRIVE)	; Rueckseite setzen
	OR 80H  	; aber kein Side-sel
	LD (DRIVE),A

	LD A,(USESSO)
	OR A
	JP Z,FORM2	; -> no SSO
	
	; SSO
	LD A,80H 
	LD (SIDESEL),A 	; setzen

FORM2:	CALL GENTRK
	CALL FRMTRK
	CALL ERRCHK
	
	; set side 0
	LD A,(DRIVE)
	AND 7FH
	LD (DRIVE),A   
	XOR A
	LD (SIDESEL),A

FORM3:	LD A,(CURTRK)
	INC A
	LD (CURTRK),A
	LD B,A
	LD A,(TRKCNT)
	CP B
	JP Z,FORM4	; AKTRK = TRKCNT
	
	CALL STEPIN
	
FORM4:	LD C,'F'
	CALL CONOUT 	; Meldung FFFFF ausgeben bei jeder Spur ein F
	POP BC
	DJNZ FORM1	; -> format loop (tracks)

	; verify -------------------------------------------------------------
	
	LD HL,VMSG
	CALL PRNMSG
	
	CALL HOME	; set head to track 0
	
	XOR A
	LD (CURTRK),A  	; start with track 0
	LD A,(TRKCNT) 	; number of tracks
	LD B,A

FORM5:	; verify loop (tracks)

	; --- verify side 0 ---

	PUSH BC
	CALL ECMACHK
	CALL VERIFY
	LD A,(SSDS)
	CP 1
	JP NZ,FORM7	; -> single-sided

	; --- double-sided, verify side 1 ---
	
	LD A,(DRIVE)
	OR 80H
	LD (DRIVE),A
	LD A,(USESSO)
	OR A
	JP Z,FORM6	; -> no SSO
	
	; SSO
	LD A,80H
	LD (SIDESEL),A

FORM6:	CALL VERIFY

	; set side 0
	LD A,(DRIVE)
	AND 7FH
	LD (DRIVE),A 
	XOR A
	LD (SIDESEL),A 	; wieder Seite 0

FORM7:	LD A,(CURTRK)
	INC A
	LD (CURTRK),A
	LD B,A
	LD A,(TRKCNT)
	CP B
	JP Z,FORM8	; -> TRKCNT = CURTRK

	CALL STEPIN

FORM8:	LD C,'V' 
	CALL CONOUT 	; VVVVV fuer Verify
	POP BC
	DJNZ FORM5	; -> verify loop (tracks)
	
	CALL HOME 	; set head to track 0
	RET
	
;-----------------------------------------------------------------------------
; Set ECMA70 format

ECMACHK:
	LD A,(ECMA)	; 1=ECMA70
	OR A
	RET Z  		; no ECMA70
	
	XOR A
	LD (MINMAX),A 	; always mini drive
	
	LD A,(CURTRK)
	OR A
	JP NZ,ECMAC1	; -> not track 0
	
	; track 0, format single-density
	LD HL,128
	LD (BYTCNT),HL
 	
	LD A,0 		; single density
	LD (DENSITY),A 	;
	LD A,0		; single-sided
	LD (SSDS),A
	LD A,16		; 16 sectors
	LD (SECCNT),A
	LD A,27
	LD (GAPLEN),A
	LD A,40		; 40 tracks
	LD (TRKCNT),A
	JP ECMAC2
	
ECMAC1:	; not track 0, format double density
	LD HL,256
	LD (BYTCNT),HL
	
	LD A,1		; double density
	LD (DENSITY),A
	LD A,0 		; single-sided
	LD (SSDS),A
	LD A,16 	; 16 sectors
	LD (SECCNT),A
	LD A,54
	LD (GAPLEN),A 	; STD Gap
	LD A,40 	; 40 tracks
	LD (TRKCNT),A

ECMAC2:	RET

;-----------------------------------------------------------------------------
; General error check routine

; error code in A
;   bit 2 = CPU to slow
;   bit 3 = CRC error
;   bit 4 = record not found
;   bit 5 = wrong record type
;   bit 6 = write protected

ERRCHK:	OR A
	RET Z  	; =0? -> Status ok
	
	; TRACK, Spur ausgeben
	PUSH AF 	; save error code
	LD HL,TKMSG
	CALL PRNMSG
	LD A,(CURTRK)
	LD L,A
	LD H,0 
	CALL PRNTHL
	LD HL,SKMSG
	CALL PRNMSG
	LD A,(CURSEC)
	LD L,A
	LD H,0
	CALL PRNTHL
	CALL CRLF

	POP AF  	; restore error code
	
	; check bit 2
	BIT 2,A
	LD HL,F0MSG 	; error message
	JP Z,ERRC1	; -> bit 2 not set
	
	; bit 2, CPU too slow
	LD HL,F2MSG

ERRC1:	; check bit 3
	BIT 3,A
	JP Z,ERRC2	; -> bit 3 not set

	; bit 3, CRC errror
	LD HL,F3MSG

ERRC2:	; check bit 4
	BIT 4,A
	JP Z,ERRC3	; -> bit 4 not set
	
	; bit 4, record not found
	LD HL,F4MSG
	
ERRC3:	; check bit 5
	BIT 5,A
	JP Z,ERRC4	; -> bit 5 not set

	; bit 5, wrong record type
	LD HL,F5MSG

ERRC4:	; check bit 6
	BIT 6,A
	JP Z,ERRC5	; -> bit 6 not set

	; bit 6, write protected
	LD HL,F6MSG
	
ERRC5:	; check bit 7
	JP Z,ERRC6
	
	; bit 7, write protected
	LD HL,F6MSG 	; dominant is write proteced error

ERRC6:	CALL PRNMSG

ERRC7:	; wait for 'W' or 'w'
	CALL CONIN
	CP 'W'
	JP Z,ERRC8
	CP 'w'
	JP NZ,ERRC7

ERRC8:	JP START 	; no stack adjust needed
	
;-----------------------------------------------------------------------------
; PRNMSG decimal value in HL
	
PRNTHL:	XOR A
	PUSH AF

PRNTH1:	; digit loop
	LD A,16
	LD BC,10 	; div 10
	LD DE,0 	; Rest
	EX DE,HL
	
PRNTH2:	; division loop
	PUSH AF
	SLA E
	RL D
	RL L
	RL H
	SET 0,E
	XOR A
	SBC HL,BC
	JP NC,PRNTH3
	
	ADD HL,BC
	RES 0,E
	
PRNTH3:	POP AF
	DEC A
	JR NZ,PRNTH2
	
	EX DE,HL 	; HL=result, DE=remainder
	LD A,E
	OR 30H
	PUSH AF
	LD A,H
	OR L
	JR NZ,PRNTH1	; -> loop
	
PRNTH4:	;output
	POP AF
	OR A
	RET Z
	
	LD C,A
	CALL CONOUT
	JR PRNTH4
	
;-----------------------------------------------------------------------------
; Create new track
	
GENTRK:	LD IX,FORMTAB 	; start of format table

	; header
	LD A,(DENSITY)
	OR A
	JP NZ,GENT1	; -> double-density

	; single-density
	LD B,16
	LD C,0FFH 	; fuellbyte 
	JP GENT2

GENT1:	; double density
	LD B,32
	LD C,04EH
	
GENT2:
GENT3:	LD (IX+0),C
	INC IX
	DEC B
	JP NZ,GENT3

	; create sectors
	
	LD A,1		; start with sector 1
	LD (CURSEC),A 	; current sector
	LD A,(SECCNT)
	LD B,A

GENT4:	; sector loop
	PUSH BC
	
	; ID field
	LD A,(DENSITY)
	OR A
	JP NZ,GENT11	; -> double density

	; --- single density ---
	
	LD B,6

GENT5:	LD (IX+0),0
	INC IX
	DEC B
	JP NZ,GENT5
	
	LD (IX+0),0FEH 	; ID address marc
	INC IX
	LD A,(CURTRK)	; track number 0..n
	LD (IX+0),A
	INC IX

	LD A,(SIDESEL) 	; side
	AND 80H  	;
	OR A
	JP NZ,GENT6	; -> side 1

	; side 0
	LD (IX+0),0  	; Seite 0
	JP GENT7

GENT6:	; side 1
	LD (IX+0),1  	; Seite 1

GENT7:	INC IX
	LD A,(CURSEC)
	LD (IX+0),A  	; Sector 1..n
	INC IX
	LD HL,(BYTCNT)	; sector size (128,256,512,1024)
	LD A,H  	; 0,1,2,4 da 80h,100h,200h,400h
	CP 4
	JP NZ,GENT8	; -> not 4
	
	; A=4
	LD A,3

GENT8:	LD (IX+0),A  	; Laengenkennung (0,1,2,3)
	INC IX
	LD (IX+0),0F7H 	; create CRC
	INC IX

	LD B,11
GENT9:	LD (IX+0),0FFH
	INC IX
	DEC B
	JP NZ,GENT9
	
	LD B,6
GENT10:	LD (IX+0),0
	INC IX
	DEC B
	JP NZ,GENT10
	
	LD (IX+0),0FBH 	; data mark
	INC IX
	JP GENT20

	; --- double density ---

GENT11:	LD B,12
GENT12:	LD (IX+0),0
	INC IX
	DEC B
	JP NZ,GENT12
	
	LD B,3
GENT13:	LD (IX+0),0F5H
	INC IX
	DEC B
	JP NZ,GENT13
	
	LD (IX+0),0FEH 	; ID address mark
	INC IX
	LD A,(CURTRK)
	LD (IX+0),A  	; track 0..n
	INC IX
	LD A,(SIDESEL) 	; for side-sel SSO
	AND 80H
	OR A
	JP NZ,GENT14	; -> side 1

	; side 0
	LD (IX+0),0  	; side 0
	JP GENT15
	
GENT14:	LD (IX+0),1  	; side 1

GENT15:	INC IX
	LD A,(CURSEC)
	LD (IX+0),A  	; sector 1..n
	INC IX
	LD HL,(BYTCNT)	; sector size (128,256,512,1024)
	LD A,H  	; 0,1,2,4 da 80h,100h,200h,400h
	CP 4
	JP NZ,GENT16
	
	; A=4
	LD A,3

GENT16:	LD (IX+0),A  	; 0,1,2,3 Laengenkennung
	INC IX
	LD (IX+0),0F7H 	; create CRC
	INC IX
	
	LD B,22
GENT17:	LD (IX+0),04EH
	INC IX
	DEC B
	JP NZ,GENT17

	LD B,12
GENT18:	LD (IX+0),0
	INC IX
	DEC B
	JP NZ,GENT18
	
	LD B,3
GENT19:	LD (IX+0),0F5H
	INC IX
	DEC B
	JP NZ,GENT19
	
	LD (IX+0),0FBH 	; data mark
	INC IX

	; write data block

GENT20:	LD A,(FILLER) 	; data byte
	LD C,A
	LD HL,(BYTCNT) ; 128,256,512,1024

GENT21:	LD (IX+0),C
	INC IX
	DEC HL
	LD A,H
	OR L
	JP NZ,GENT21
	
	LD (IX+0),0F7H 	; write CRC
	INC IX
	LD A,(DENSITY)
	OR A
	JP NZ,GENT22	; -> double density
	
	; single density
	LD C,0FFH  	; Datenbyte SD
	JP GENT23

GENT22:	; double density
	LD C,04EH  	; Datenbyte DD

GENT23:	LD A,(GAPLEN)
	LD B,A  	; store gap 3

GENT24:	LD (IX+0),C
	INC IX
	DEC B
	JP NZ,GENT24
	
	; next sector
	LD A,(CURSEC)
	INC A
	LD (CURSEC),A 	; neue Sektorennummer
	POP BC
	DEC B
	JP NZ,GENT4	; -> sector loop
	
	; fill to the end
	LD A,(DENSITY)
	OR A
	JP NZ,GENT25	; -> double-sided

	; single-sided
	LD C,0FFH 	; store gap 4
	JP GENT26

GENT25:	; double-sided
	LD C,04EH

GENT26:	LD HL,1000	; use big number to make shure there are no
			; unwanted bytes till the index puls
GENT27:	LD (IX+0),C
	INC IX
	DEC HL
	LD A,H
	OR L
	JP NZ,GENT27
	
	RET
	
;-----------------------------------------------------------------------------
; Verify a track, test-read read all sectors
	
VERIFY:	CALL DELAY  	; head settle time

	LD A,1
	LD (CURSEC),A
	LD A,(SECCNT)

	LD B,A
	
VERIF1:	PUSH BC
	CALL READ  	; simply read
	CALL ERRCHK  	; 0=ok, otherwise message
	
	LD A,(CURSEC)
	INC A
	LD (CURSEC),A
	
	POP BC
	DEC B
	JP NZ,VERIF1
	
	RET
	
;-----------------------------------------------------------------------------
; Delay loop 40ms..10ms (???)

DELAY:	PUSH BC
	LD BC,0D05H

DELAY1:	DEC BC
	LD A,C
	OR B
	JP NZ,DELAY1
	
	POP BC
	RET
	
;-----------------------------------------------------------------------------
; Set head to track 0

HOME:	LD A,(USER)
	OR A
	JP NZ,HOME4
	
	; USER=0: FLO1/FLO2 (C0h)
	
	LD HL,250 	; max retries
	
HOME1:	; retry loop
	PUSH  HL
	IN A,(FLO0)	; read status
	CALL DELAY
	EI  		; enable interrupts
	CALL RSTEX	; execute Restore
	DI
	POP HL
	IN A,(FLO0)	; read status
	AND 80H 	; <>0 dann nicht ready
	JP Z,HOME12
	
	DEC HL
	LD A,H
	OR L  		
	JR NZ,HOME1	; -> retry
	
	; error
	LD HL,RMSG	; not ready
	CALL PRNMSG

HOME2:	; wait for 'W' / 'w'
	CALL CONIN
	CP 'W'
	JP Z,HOME3
	CP 'w'
	JP NZ,HOME2

HOME3:	JP START
	
	;---------------------------------------------------------------------

HOME4:	CP 1  		; 1=FLO1-Maxi
	JP NZ,HOME8

	; FLO1 Maxi
	
	LD HL,250 	; max retries
	
HOME5:	; retry loop
	PUSH HL
	IN A,(FLOA0)
	CALL DELAY
	EI  		; enable interrupts
	CALL RSTEXA	; execute Restore
	DI
	POP HL
	IN A,(FLOA0) 	; check status
	AND 80H
	JP Z,HOME12	; -> 0=ready
	
	DEC HL
	LD A,H
	OR L
	JR NZ,HOME5	; -> retry
	
	; error
	LD HL,RMSG	; not ready
	CALL PRNMSG

HOME6:	; wait for 'W' / 'w'
	CALL CONIN
	CP 'W'
	JP Z,HOME7
	CP 'w'
	JP NZ,HOME6

HOME7:	JP START
	
	;---------------------------------------------------------------------
	
HOME8:	; FLO1-Mini (???)

	LD HL,250 	; max retries

HOME9:	; retry loop
	PUSH  HL
	IN A,(FLOB0)
	CALL DELAY
	EI  		; enable interrupts
	CALL RSTEXB	; execute Restore
	DI
	POP HL
	IN A,(FLOB0) 	; check status
	AND 80H
	JP Z,HOME12	; -> 0=ready
	
	DEC HL
	LD A,H
	OR L
	JR NZ,HOME9	; -> retry

	; error
	LD HL,RMSG	; not ready
	CALL PRNMSG

HOME10:	; wait for 'W' / 'w'
	CALL CONIN
	CP 'W'
	JP Z,HOME11
	CP 'w'
	JP NZ,HOME10

HOME11:	JP START

HOME12:	; finished
	RET

;-----------------------------------------------------------------------------
; Execute Restore FLO2

RSTEX:	CALL SETSR	; setup special register
	LD A,00001011B 	; 0000=Restore, Headload=1, Verify=0, Stepping rate=11
	OUT (FLO0),A	; write command
	HALT  		; UEBER INT zurueck

;-----------------------------------------------------------------------------
; Execute Restore FLO1 Maxi

RSTEXA:	CALL SETSR	; setup special register
	LD A,00001011B 	; see FLO2
	OUT (FLOA0),A
	HALT  		; UEBER INT zurueck

;-----------------------------------------------------------------------------
; Execute Restore FLO1 Mini

RSTEXB:	CALL SETSR	; setup special register
	LD A,00001011B 	; see FLO2
	OUT (FLOB0),A
	HALT  		; UEBER INT zurueck

;-----------------------------------------------------------------------------
; Step ausfuehren

STEPIN:	CALL DELAY 	; settle head
	EI
	CALL STPEX
	DI
	RET

;-----------------------------------------------------------------------------
; Execute drive step

STPEX:
 	; Laufwerk und Dichte
	CALL SETSR	; setup special register
	LD A,(USER)
	OR A
	JP NZ,STPEX1

	; USER=0: FLO1/FLO2 (C0h)
	LD A,01011011B	; 010=Step In, update=1, headload=1, verify=0, stepping rate=11
	OUT (FLO0),A	; write command
	JP STPEX3

STPEX1:	CP 1
	JP NZ,STPEX2
	
	; USER=1: FLO1 Maxi
	LD A,01011011B	; see FLO2
	OUT (FLOA0),A	; write command
	JP STPEX3

STPEX2:	CP 2
	JP NZ,STPEX3	; das fuehrt zu einem Endlos-HALT, weil der Controller
			; nicht programmier wurde.

	; USER=2: FLO1 Mini
	LD A,01011011B	; see FLO2
	OUT (FLOB0),A	; write command

STPEX3:	HALT 

;-----------------------------------------------------------------------------

READ:	LD B,2

READ1:	PUSH BC
	EI
	CALL READEX
	DI
	POP BC  	; Fehlerzaehler
	LD A,(USER)
	OR A
	JP NZ,READ2
	
	; USER=0: FLO1/FLO2 (C0h)
	IN A,(FLO0) 	; read status
	JP READ4
	
READ2:	CP 1
	JP NZ,READ3
	
	; USER=1: FLO1 Maxi
	IN A,(FLOA0)
	JP READ4
	
READ3:	CP 2
	JP NZ,READ4
	
	; USER=2: FLO1 Mini
	IN A,(FLOB0)

READ4:	AND 00111100B
	RET Z		; -> ok
	
	DJNZ READ1 	; -> retry
	RET

;-----------------------------------------------------------------------------

READEX:	CALL SETSR 	; setup special register
	LD A,(USER)
	OR A
	JP NZ,READX2

	; USER=0: FLO1/FLO2 (C0h)
	LD A,(CURSEC)
	OUT (FLO2),A 	; Sektor definieren
	LD HL,FORMTAB 	; dorthin Daten legen 
	LD C,FLO3 	; Datenport
	LD A,(SIDESEL) 	; fuer Side-Control
	AND 80H
	RLCA  		; BIT 0
	RLCA  		; BIT 1
	AND 00000010B 	; 1=Seite 1
	ADD A,88H 	; kein Delay abwarten, head ist down
	OUT (FLO0),A 	; und Befehl geben

READX1:	; wait for DRQ
	IN A,(FLO4)
	RLCA		; DRQ -> Carry
	JP NC,READX1	; -> wait

	INI  		; DATEN ablegen
	JP READX1 	; bis alle Daten gelesen, dann Interrupt 
	JP READX6

READX2:	CP 1 
	JP NZ,READX4

	; USER=1: FLO1 Maxi
	LD A,(CURSEC)
	OUT (FLOA2),A 	; Sektor definieren
	LD HL,FORMTAB 	; dorthin Daten legen 
	LD C,FLOA3 	; Datenport
	LD A,(SIDESEL) 	; fuer Side-Control
	AND 80H
	RLCA  		; BIT 0
	RLCA  		; BIT 1
	AND 00000010B 	; 1=Seite 1
	ADD A,88H 	; kein Delay abwarten, head ist down
	OUT (FLOA0),A 	; und Befehl geben

READX3:	IN A,(FLOA4)
	RLCA
	JP NC,READX3 	; warten bis DRQ-da ist
	INI  		; DATEN ablegen
	JP READX3 	; bis alle Daten gelesen, dann Interrupt 
	JP READX6
	
READX4:	CP 2 
	JP NZ,READX6
	
	; USER=2: FLO1 Mini
	LD A,(CURSEC) 
	OUT (FLOB2),A 	; Sektor definieren
	LD HL,FORMTAB 	; dorthin Daten legen 
	LD C,FLOB3 	; Datenport
	LD A,(SIDESEL) 	; fuer Side-Control
	AND 80H
	RLCA  		; BIT 0
	RLCA  		; BIT 1
	AND 00000010B 	; 1=Seite 1
	ADD A,88H 	; kein Delay abwarten, head ist down
	OUT (FLOB0),A 	; und Befehl geben

READX5:	IN A,(FLOB4)
	RLCA
	JP NC,READX5 	; warten bis DRQ-da ist
	INI  		; DATEN ablegen
	JP READX5 	; bis alle Daten gelesen, dann Interrupt 

READX6:	RET 

;-----------------------------------------------------------------------------
; Setup special register (Register 4)

SETSR:	PUSH BC
	LD A,(DRIVE) 	; Laufwerkscode
	LD B,A 
	LD A,(DENSITY)
	OR A
	JP NZ,SETCT1	; -> DD

	; SD
	LD A,B
	OR 10H		; set FD179x and FDC9293 density signal
	LD B,A

SETCT1:	LD A,(MINMAX)
	OR A
	JP NZ,SETCT2

	; Mini
	LD A,B
	OR 20H		; set FDC9293 Mini signal
	LD B,A
	
SETCT2:	; Mini/Maxi
	LD A,(USER)
	OR A
	JP NZ,SETCT5
	
	; USER=0: FLO1/FLO2 (C0h)
	LD A,(FLOTYP)
	CP 01H
	JP NZ,SETCT3

	; FLO1 (C0h)
	LD A,B
	XOR 10H		; invert density signal
	JP SETCT4

SETCT3:	LD A,B

SETCT4:	POP BC
	OUT (FLO4),A
	JP SETCT7

SETCT5:	CP 1  
	JP NZ,SETCT6
	
	; FLO1 Maxi (USER=1)
	LD A,B
	POP BC
	XOR 10H  	; invert density signal
	OUT (FLOA4),A
	JP SETCT7

SETCT6:	CP 2
	JP NZ,SETCT7
	
	; FLO1 Mini (USER=2)
	LD A,B
	POP BC
	XOR 10H  	; invert density signal
	OUT (FLOB4),A

SETCT7:	RET
	
;-----------------------------------------------------------------------------
; Format track

FRMTRK:	CALL DELAY
	EI
	CALL FMT
	DI
	
	; check for lost data and write protection
	
	LD A,(USER)
	OR A
	JP NZ,FRMTR1
	
	; FLO1/FLO2 (C0h)
	IN A,(FLO0) 	; read status
	JP FRMTR3

FRMTR1:	CP 1
	JP NZ,FRMTR2
	
	; FLOW1 Maxi
	IN A,(FLOA0) 	; read status
	JP FRMTR3

FRMTR2:	CP 2
	JP NZ,FRMTR3
	
	; FLO1 Mini
	IN A,(FLOB0) 	; read status

FRMTR3:	AND 01000100B	; Bit 2=Lost Data, Bit 6=Write Protect
	RET

;-----------------------------------------------------------------------------

FMT:	CALL SETSR 	; setup special register
	LD A,(USER)
	OR A
	JP NZ,FMT2

	; FLO1/FLO2 (C0h)
	LD HL,FORMTAB 	; Startadresse 
	LD C,FLO3 	; Datenport
	LD A,(SIDESEL) 	; Side-Flag setzen, fuer SSO-Ausgang
	AND 80H 	; wenn USESSO auf 80h gesetzt wird
	RLCA  		; BIT 0
	RLCA  		; BIT 1
	AND 00000010B 	; Side select for FD1797 (SSO)
	OR 0F4H 	; 1111x1xx=Write track, Formatier-Befehl+nicht documentierter
	OUT (FLO0),A 	; Side-Select-Befehl fuer SSO

FMT1:	; format loop
	IN A,(FLO4) 	; DRQ int head
	RLCA  		; DRQ -> carry
	JP NC,FMT1 	; -> wait
	
	; ready
	OUTI		; (HL) -> Port (C), length in B
	JP FMT1 	; durch INT wird die Routine gestoppt.
	JP FMT6

FMT2:	CP 1 
	JP NZ,FMT4
	
	; FLO1 Maxi
	LD HL,FORMTAB 	; Startadresse 
	LD C,FLOA3 	; Datenport
	LD A,(SIDESEL) 	; Side-Flag setzen, fuer SSO-Ausgang
	AND 80H 	; wenn USESSO auf 80h gesetzt wird
	RLCA  		; BIT 0
	RLCA  		; BIT 1
	AND 00000010B 	; Side select for FD1797 (SSO)
	OR 0F4H 	; see FLO2
	OUT (FLOA0),A

FMT3:	; wait for DRQ
	IN A,(FLOA4) 	; drq int head
	RLCA  		; BIT 7 ins carry
	JP NC,FMT3 	; -> wait
	
	OUTI		; (HL) -> Port (C), length in B
	JP FMT3 	; durch INT wird die Routine gestoppt.
	JP FMT6

FMT4:	CP 2 
	JP NZ,FMT6
	
	; FLO1 Mini
	LD HL,FORMTAB 	; Startadresse 
	LD C,FLOB3 	; Datenport
	LD A,(SIDESEL) 	; Side-Flag setzen, fuer SSO-Ausgang
	AND 80H 	; wenn USESSO auf 80h gesetzt wird
	RLCA  		; BIT 0
	RLCA  		; BIT 1
	AND 00000010B 	; Side select for FD1797 (SSO)
	OR 0F4H 	; see FLO2
	OUT (FLOB0),A

FMT5:	; wait for DRQ
	IN A,(FLOB4) 	; DRQ int head
	RLCA  		; BIT 7 ins carry
	JP NC,FMT5 	; -> wait
	
	OUTI		; (HL) -> Port (C), length in B
	JP FMT5 	; durch INT wird die Routine gestoppt.

FMT6:	RET

;-----------------------------------------------------------------------------
; Main input loop
	
START:

MAINLOOP:

	LD HL,HEADTXT	; Programm start message and format type
	CALL PRNMSG

	; --- disk format selection ---
	
MAIN1:	; wait for 1..6
	CALL CONIN
	CP '6'+1
	JP NC,MAIN1
	CP '1'+0
	JP C,MAIN1
	
MAIN2:	PUSH AF
	XOR A
	LD (ECMA),A 	; 0=no ECMA70 (default)
	LD (USER),A 	; 0 = FLO1/FLO2 (C0h)
	LD A,0E5H
	LD (FILLER),A 	; Filler ist normalerweise E5h
	XOR A
	LD (SIDESEL),A 	; no SSO (default)
	LD (USESSO),A	; auch nicht bei Kopfwechsel 
	POP AF
	
	CP '1' 
	JP NZ,MAIN3
	
	; Format 1: Mini 5 1/4"
	; MINMAX = 0
	XOR A		; 0 = Mini
	LD (MINMAX),A
	CALL SELTRK
	CALL SELSID
	CALL SELDEN
	CALL SELSEC
	JP MAIN8
	
MAIN3:	CP '2' 
	JP NZ,MAIN4
	
	; Format 2: Maxi 8"
	; MINMAX = 1
	LD A,1		; 1 = Maxi
	LD (MINMAX),A
	CALL SELTRK
	CALL SELSID
	CALL SELDEN
	CALL SELSEC
	JP MAIN8

MAIN4:	CP '3'
	JP NZ,MAIN5
	
	; Format 3: Std  8" SD SD 77 Spur
	LD A,1		; Maxi disk
	LD (MINMAX),A
	LD HL,128 	; 128 bytes per sector
	LD (BYTCNT),HL
	LD A,0 		; single-density
	LD (DENSITY),A
	LD A,27 	; gap lenght 27
	LD (GAPLEN),A
	LD A,0 		; single-sided
	LD (SSDS),A
	LD A,26 	; 26 sectors
	LD (SECCNT),A
	LD A,77 	; 77 tracks
	LD (TRKCNT),A
	JP MAIN8

MAIN5:	CP '4' 
	JP NZ,MAIN6

	; Format 4: ECMA 70 DD SD 40 Spur
	XOR A		; Mini disk
	LD (MINMAX),A
	LD A,1	 	; Spezialformat SD erste Spur
	LD (ECMA),A 	; wenn rueckseite dann mit Bit
	LD (USESSO),A	; REST in ECMA doppelt
	LD HL,256 	; 256 bytes per sector
	LD (BYTCNT),HL
	LD A,1		; double-density
	LD (DENSITY),A
	LD A,0		; single-sided
	LD (SSDS),A
	LD A,16 	; 16 sectors
	LD (SECCNT),A
	LD A,54		; gap length 54
	LD (GAPLEN),A
	LD A,40 	; 40 tracks
	LD (TRKCNT),A
	JP MAIN8

MAIN6:	CP '5' 
	JP NZ,MAIN7

	; Format 5: NDR- DD DS 80 Spur
	LD A,0 		; Mini disk
	LD (MINMAX),A
	LD HL,1024 	; 1024 bytes per sector
	LD (BYTCNT),HL
	LD A,1 		; double-density
	LD (DENSITY),A
	LD A,54 	; gap length 3
	LD (GAPLEN),A
	LD A,5		; 5 sectors
	LD (SECCNT),A
	LD A,1 		; double-sided
	LD (SSDS),A
	LD A,1		; side bit
	LD (USESSO),A 	; und mit Side-Bit
	LD A,80 	; 80 tracks (0..79)
	LD (TRKCNT),A
	JP MAIN8

MAIN7:	CP '6' 
	JP NZ,MAIN8
	
	JP MAIN35	; -> exit
	
	; --- FLO type selection ---

MAIN8:	LD HL,MENUE7 	; FLO type
	CALL PRNMSG

MAIN9:	; wait for 1..3
	CALL CONIN
	CP '4'+1
	JR NC,MAIN10
	CP '1'+0
	JP NC,MAIN11
	
MAIN10:	CP 0DH
	JP NZ,MAIN9

MAIN11:	CP '2'
	JP NZ,MAIN12
	
	; FLO type 2: FLO1 Maxi (40h)
	; FLOTYP = 0
	; USER = 1
	LD A,1 	; FLO1, maxi
	JP MAIN15
	
MAIN12:	CP '3'
	JP NZ,MAIN13

	; FLO type 3: FLO1 Mini (30h)
	LD A,2 	; FLO2, mini
	; FLOTYP = 0
	; USER = 2
	JP MAIN15
	
MAIN13:	CP '4'
	JP NZ,MAIN14
	
	; FLO type 4: FLO1-Maxi/Mini (0C0h)
	; FLOTYP = 1
	; USER = 0
	LD A,01H
	LD (FLOTYP),A
	XOR A  	; FLO2 Mini/maxi
	JP MAIN15
	
MAIN14:	CP '1'
	JP NZ,MAIN15
	
	; FLO type 1: FLO2-Maxi/Mini (0C0h)
	; FLOTYP = 0
	; USER = 0
	XOR A
	LD (FLOTYP),A
	
MAIN15:	LD (USER),A

	; --- drive selection ---

MAIN16:	LD HL,MENUE6 	; drive
	CALL PRNMSG

MAIN17:	; wait for 0..9
	CALL CONIN
	CP '9'+1
	JP NC,MAIN17
	CP '0'+0
	JP C,MAIN17
	
	; 1..8
	CP '8'+1
	JP NC,MAIN27
	CP '1'+0
	JP C,MAIN27

	CP '1'
	JP NZ,MAIN18
	
	; drive 1: A
	LD A,1
	JP MAIN25

MAIN18:	CP '2'
	JP NZ,MAIN19
	
	; drive 2: B
	LD A,2
	JP MAIN25

MAIN19:	CP '3'
	JP NZ,MAIN20
	
	; drive 3: C
	LD A,4
	JP MAIN25
	
MAIN20:	CP '4'
	JP NZ,MAIN21
	
	; drive 4: D
	LD A,8
	JP MAIN25
	
MAIN21:	CP '5'
	JP NZ,MAIN22

	; drive 5: A backside A
	LD A,81H
	JP MAIN25
	
MAIN22:	CP '6'
	JP NZ,MAIN23

	; drive 6: B backside B
	LD A,82H
	JP MAIN25
	
MAIN23:	CP '7'
	JP NZ,MAIN24
	
	; drive 7: C backside C
	LD A,84H
	JP MAIN25
	
MAIN24:	CP '8'
	JP NZ,MAIN25
	
	LD A,88H

MAIN25:	LD (DRIVE),A
	LD A,(USESSO)
	OR A
	JP Z,MAIN26		; -> no SSO

	; SSO
	LD A,(DRIVE)
	AND 80H
	JP Z,MAIN26
	
	LD (SIDESEL),A 	; wenn Flag, dann Rueckseite mit side-bit
			; FUER ECMA-70 wichtig.
MAIN26:	JP MAIN30

MAIN27:	CP '9'
	JP NZ,MAIN28
	
	; '9'
	JP MAINLOOP 	; neue Parameter
	JP MAIN30
	
MAIN28:	CP '0'
	JP NZ,MAIN29

	; '0'
	JP MAIN35 	; -> exit
	JP MAIN30
	
MAIN29:	JP MAIN16 	; -> inner loop, mit gleichen Parametern

	;---------------------------------------------------------------------
	; call formatter, when ready output control values

MAIN30:	CALL PRNPRM

	LD HL,FORMTXT
	CALL PRNMSG
	
	; wait for 'J' / 'j'
	CALL CONIN
	CP 'J'
	JP Z,MAIN31
	CP 'j'
	JP Z,MAIN31
	CP 'n'
	JP Z,MAIN31
	CP 'N'
	JP Z,MAIN31
	CP 3		; ctrl-c
	JP NZ,MAIN30

MAIN31:	CP 'n'
	JP Z,MAIN32
	CP 'N'
	JP NZ,MAIN33

MAIN32:	JP START 	; Neustarten, von vorne

MAIN33:	CP 3		; ctrl-c
	JP NZ,MAIN34

	; ctrl-c
	JP MAIN35 	; Abbruch CTRL-C
	
MAIN34:	CALL FORMAT

	; end of formatting
	JP MAIN16 	; -> inner loop, mit gleichen Parametern
		
MAIN35:	LD HL,FIMSG	; end messaghe (insert system-disk)
	CALL PRNMSG

MAIN36:	; wait for CR
	CALL CONIN
	CP 0DH
	JP NZ,MAIN36
	
	IM 0  		; SAVETY bei FLO1, ggf IM0-Mode verwendet
	CALL 0  	; daher ruecksetzen.
	RET

;-----------------------------------------------------------------------------
; Track selection menu (35/40/70/77/80)

SELTRK:	LD HL,MENUE3
	CALL PRNMSG

SELTR1:	; wait for '1'..'5'
	CALL CONIN
	CP '5'+1
	JP NC,SELTR1
	CP '1'+0
	JP C,SELTR1

	CP '1'
	JP NZ,SELTR2

	; '1': 35 tracks
	LD A,35
	JP SELTR7

SELTR2:	CP '2'
	JP NZ,SELTR3
	
	; '2': 40 tracks
	LD A,40
	JP SELTR7

SELTR3:	CP '3'
	JP NZ,SELTR4
	
	; '3': 70 tracks
	LD A,70
	JP SELTR7
	
SELTR4:	CP '4'
	JP NZ,SELTR5
	
	; '4'; 77 tracks
	LD A,77
	JP SELTR7
	
SELTR5:	CP '5'
	JP NZ,SELTR6
	
	; '5': 80 traacks
	LD A,80

SELTR6:	; all other inputs: invalid???

SELTR7:	LD (TRKCNT),A
	RET
	
;-----------------------------------------------------------------------------
; Side selection menu (SS/DS/SSO)

SELSID:	LD HL,MENUE4
	CALL PRNMSG
	
SELSI1:	; wait for '1'..'3'
	CALL CONIN
	CP '3'+1
	JP NC,SELSI1
	CP '1'+0
	JP C,SELSI1

	CP '1'
	JP NZ,SELSI2
	
	; '1': single-sided
	LD A,0  
	LD (SSDS),A	; single-sided
	JP SELSI4
	
SELSI2:	CP '2'
	JP NZ,SELSI3
	
	; '2': double-sided
	LD A,1
	LD (SSDS),A	; double-sided
	JP SELSI4
	
SELSI3:	; all other inputs: double-sided with SSO
	LD A,1
	LD (SSDS),A	; double-sided
	LD A,1
	LD (USESSO),A	; use SSO
	
SELSI4:	LD (SSDS),A 	; single-sided=0, double-sided=1
	RET

;-----------------------------------------------------------------------------
; Density selection menu

SELDEN:	LD HL,MENUE2
	CALL PRNMSG

SELDE1:	; wait for '1'..'2'
	CALL CONIN
	CP '2'+1
	JP NC,SELDE1
	CP '1'+0
	JP C,SELDE1
	
	CP '1'
	JP NZ,SELDE2

	; '1': single-density
	LD A,0		; single-density
	JP SELDE3

SELDE2:	; all other inputs: double-density
	LD A,1 		; double-density

SELDE3:	LD (DENSITY),A
	RET
	
;-----------------------------------------------------------------------------
; Sector selection menu
;	256 bytes / 16 per track)
;	512 bytes / 9 per track)
;	512 bytes / 10 per track)
;	1024 bytes / 5 per track)

SELSEC:	LD A,(MINMAX)
	OR A
	JP NZ,SELSE13	; -> Maxi
	
	; --- 0 = Mini ---
	LD A,(DENSITY)
	OR A
	JP NZ,SELSE6
	
	; --- mini, single-density ---
	
	LD HL,MENUE5A
	CALL PRNMSG
	
SELSE1:	; wait for '1'..'3'
	CALL CONIN
	CP '3'+1
	JP NC,SELSE1
	CP '1'+0
	JP C,SELSE1
	
	CP '1'
	JP NZ,SELSE2

	; '1': 128 bytes per sector, 16 sectors per track
	LD HL,128
	LD (BYTCNT),HL
	LD A,16
	LD (SECCNT),A
	LD A,27
	LD (GAPLEN),A
	JP SELSE5

SELSE2:	CP '2'
	JP NZ,SELSE3

	; '2': 128 bytes per sector, 18 sectors per track
	LD HL,128
	LD (BYTCNT),HL
	LD A,18
	LD (SECCNT),A
	LD A,10
	LD (GAPLEN),A
	JP SELSE5
	
SELSE3:	CP '3'
	JP NZ,SELSE4
	
	; '3': 256 bytes per sector, 10 sectors per track
	LD HL,256
	LD (BYTCNT),HL
	LD A,10
	LD (SECCNT),A
	LD A,16
	LD (GAPLEN),A

SELSE4:	; all other inputs: invalid ???

SELSE5:	JP SELSE12

SELSE6:	; --- mini, double-density ---

	LD HL,MENUE5B
	CALL PRNMSG

SELSE7:	; wait for '1'..'4'
	CALL CONIN
	CP '4'+1
	JP NC,SELSE7
	CP '1'+0
	JP C,SELSE7

	CP '1'
	JP NZ,SELSE8
	
	; '1': 256 bytes per sector, 16 sectors per track
	LD HL,256
	LD (BYTCNT),HL
	LD A,16
	LD (SECCNT),A
	LD A,54
	LD (GAPLEN),A
	JP SELSE12
	
SELSE8:	CP '2'
	JP NZ,SELSE9
	
	; '2': 512 bytes per sector, 9 sectors per track
	LD HL,512
	LD (BYTCNT),HL
	LD A,9
	LD (SECCNT),A
	LD A,54
	LD (GAPLEN),A
	JP SELSE12
	
SELSE9:	CP '3'
	JP NZ,SELSE10
	
	; '3': 512 bytes per sector, 10 sectors per track
	LD HL,512
	LD (BYTCNT),HL
	LD A,10
	LD (SECCNT),A
	LD A,40
	LD (GAPLEN),A
	JP SELSE12
	
SELSE10:CP '4'
	JP NZ,SELSE11
	
	; '3': 1024 bytes per sector, 5 sectors per track
	LD HL,1024
	LD (BYTCNT),HL
	LD A,5
	LD (SECCNT),A
	LD A,54
	LD (GAPLEN),A

SELSE11:; all other inputs: invalid ???

SELSE12:JP SELSE25	; -> ret

	; --- Maxi ---
	
SELSE13:LD A,(DENSITY)
	OR A
	JP NZ,SELSE17
	
	; maxi, single-density
	LD HL,MENUE5C
	CALL PRNMSG

SELSE14:; wait for '1'..'2'
	CALL CONIN
	CP '2'+1
	JP NC,SELSE14
	CP '1'+0
	JP C,SELSE14

	CP '1'
	JP NZ,SELSE15
	
	; '1': 128 bytes per sector, 26 sectors per track
	LD HL,128
	LD (BYTCNT),HL
	LD A,26
	LD (SECCNT),A
	LD A,27
	LD (GAPLEN),A
	JP SELSE16
	
SELSE15:; all other: 256 bytes per sector, 15 sectors per track
	LD HL,256
	LD (BYTCNT),HL
	LD A,15
	LD (SECCNT),A
	LD A,27
	LD (GAPLEN),A
	
SELSE16:JP SELSE25	; -> ret

	; maxi, double-density

SELSE17:LD HL,MENUE5D
	CALL PRNMSG
	
SELSE18:; wait for '1'..'6'
	CALL CONIN
	CP '6'+1
	JP NC,SELSE18
	CP '1'+0
	JP C,SELSE18

	CP '1'
	JP NZ,SELSE19
	
	; '1': 256 bytes per sector, 26 sectors per track
	LD HL,256
	LD (BYTCNT),HL
	LD A,26
	LD (SECCNT),A
	LD A,54
	LD (GAPLEN),A
	JP SELSE25
	
SELSE19:CP '2'
	JP NZ,SELSE20
	
	; '2': 512 bytes per sector, 14 sectors per track
	LD HL,512
	LD (BYTCNT),HL
	LD A,14
	LD (SECCNT),A
	LD A,54
	LD (GAPLEN),A
	JP SELSE25
	
SELSE20:CP '3'
	JP NZ,SELSE21
	
	; '3': 512 bytes per sector, 15 sectors per track
	LD HL,512
	LD (BYTCNT),HL
	LD A,15
	LD (SECCNT),A
	LD A,54
	LD (GAPLEN),A
	JP SELSE25
	
SELSE21:CP '4'
	JP NZ,SELSE22
	
	; '4': 512 bytes per sector, 16 sectors per track
	LD HL,512
	LD (BYTCNT),HL
	LD A,16
	LD (SECCNT),A
	LD A,40
	LD (GAPLEN),A
	JP SELSE25
	
SELSE22:CP '5'
	JP NZ,SELSE23
	
	; '5': 1024 bytes per sector, 8 sectors per track
	LD HL,1024
	LD (BYTCNT),HL
	LD A,8
	LD (SECCNT),A
	LD A,54
	LD (GAPLEN),A
	JP SELSE25
	
SELSE23:CP '6'
	JP NZ,SELSE24
	
	; '6': 1024 bytes per sector, 9 sectors per track
	LD HL,1024
	LD (BYTCNT),HL
	LD A,9
	LD (SECCNT),A
	LD A,40
	LD (GAPLEN),A

SELSE24:; all other inputs: invalid

SELSE25:RET
	
;-----------------------------------------------------------------------------
; Print 0-terminated message, address in HL
	
PRNMSG:	LD A,(HL)

PRNTM1:	OR A
	JP Z,PRNTM2
	
	LD C,A
	CALL CONOUT
	INC HL
	LD A,(HL)
	JP PRNTM1

PRNTM2:	RET

;-----------------------------------------------------------------------------
; Print floppy parameters

PRNPRM:	LD C,1AH	; clear screen
	CALL CONOUT

	; --- mini / maxi ---

	LD A,(MINMAX)
	OR A
	JP NZ,PRNP1
	
	; Mini
	LD HL,TMINI
	JP PRNP2
	
PRNP1:	; Maxi
	LD HL,TMAXI

PRNP2:	CALL PRNMSG

	; --- user / flotype ---

	LD A,(USER)
	OR A		; USER=0 ?
	JP NZ,PRNP5
	
	; USER=0: FLO1/FLO2 (C0h)
	LD A,(FLOTYP)
	OR A
	JP NZ,PRNP3
	
	; USER=0, FLOTYP=0: FLO2 (C0h)
	LD HL,TFLO2
	JP PRNP4
	
PRNP3:	; USER=0, FLOYP=1: FLO1 (C0h)
	LD HL,TFLO1C

PRNP4:	JP PRNP7
	
PRNP5:	CP 1		; USER=1 ?
	JP NZ,PRNP6
	
	; USER=1: FLO1 (40h)
	LD HL,TFLO1A
	JP PRNP7

PRNP6:	; USER=other: FLO1 (30h)
	LD HL,TFLO1B

PRNP7:	CALL PRNMSG	; print USER/FLOTYP

	; --- density (FM/MFM/ECMA77)---

	LD A,(DENSITY)
	OR A
	JP NZ,PRNP8

	; DENSITY=0: FM
	LD HL,TFM
	JP PRNP9

PRNP8:	; DENSITY=1: MFM
	LD HL,TMFM

PRNP9:	LD A,(ECMA)
	CP 1
	JP NZ,PRNP10
	
	; ECMA
	LD HL,TECMA 	; special case: ECMA77 format

PRNP10:	CALL PRNMSG

	CALL CRLF
	CALL CRLF
	
	; --- number of track ---
	
	LD HL,TSPUREN
	CALL PRNMSG
	LD A,(TRKCNT)
	LD L,A
	LD H,0
	CALL PRNTHL 	; Anzahl Spuren
	CALL CRLF
	
	; --- number of sectors ---
	
	LD HL,TSEKTOREN
	CALL PRNMSG
	LD A,(SECCNT)
	LD L,A
	LD H,0
	CALL PRNTHL 	; Anzahl SECCNT
	CALL CRLF

	; --- bytes per sector ---
	
	LD HL,TBYTES
	CALL PRNMSG
	LD HL,(BYTCNT)
	CALL PRNTHL 	; Bytes pro Sektor
	CALL CRLF

	; --- drive (A,B, ...) ---

	LD HL,TLAUFWERK
	CALL PRNMSG
	LD A,(DRIVE)
	AND 0FH 	; 1,2,4,8
	CP 1
	JP NZ,PRNP11
	
	LD C,'A'
	JP PRNP15

PRNP11:	CP 2
	JP NZ,PRNP12
	
	LD C,'B'
	JP PRNP15

PRNP12:	CP 4
	JP NZ,PRNP13
	
	LD C,'C'
	JP PRNP15
	
PRNP13:	CP 8
	JP NZ,PRNP14
	
	LD C,'D'
	JP PRNP15

PRNP14:	LD C,'?'

PRNP15:	CALL CONOUT
	CALL CRLF
	CALL CRLF

	; --- single-sided / double-sided ---

	LD A,(SSDS)
	CP 1
	JP NZ,PRNP18	; -> single-sided
	
	; double-sided
	
	LD A,(USESSO)
	OR A
	JP NZ,PRNP16	; -> SSO
	
	; double-sided, no SSO
	LD HL,TZWEISEITIG
	JP PRNP17

PRNP16:	; double-sided with SSO
	LD HL,TZWEISSO

PRNP17:	CALL PRNMSG
	JP PRNP22

	; single-sided

PRNP18:	LD A,(DRIVE) 
	AND 80H
	JP NZ,PRNP19
	
	; side 0
	LD HL,TEINSEITIG
	CALL PRNMSG
	JP PRNP22
	
PRNP19:	; side 1
	LD A,(USESSO)
	OR A
	JP NZ,PRNP20	; -> SSO
	
	; single-sided, no SSO
	LD HL,TRUECKSEITE
	JP PRNP21

PRNP20:	; side 1, with SSO
	LD HL,TRUECKSSO

PRNP21:	CALL PRNMSG

PRNP22:	CALL CRLF 
	CALL CRLF
	
	; --- capacity in kb ---
	
	LD HL,TKAP
	CALL PRNMSG
	LD A,(SECCNT)
	LD L,A
	LD H,0
	LD A,(TRKCNT)
	LD E,A
	LD D,0
	CALL MULHLDE 	; HL = sectors * tracks
	
	LD A,(SSDS)
	CP 1
	JP NZ,PRNP23	; -> single-sided
	
	; double-sided
	LD DE,2
	CALL MULHLDE 	; HL = HL * 2

PRNP23:	LD DE,(BYTCNT) 	; 1024,512,256,128
			; (400h,200h,100h,080h)
	LD A,D
	OR A
	JP NZ,PRNP25
	
	; D=0: HL = HL / 8 (1 KB / 8 = 128)
	LD B,3 
PRNP24:	SRA H
	RR L
	DEC B
	JP NZ,PRNP24
	
	JP PRNP29

PRNP25:	; D=1
	LD A,D
	CP 1
	JP NZ,PRNP26
	
	; D=1: HL = HL / 4 (1 KB / 4 = 256)
	SRA H
	RR L
	SRA H
	RR L
	JP PRNP29

PRNP26:	LD A,D
	CP 2
	JP NZ,PRNP27

	; D=2: HL = HL / 2 (1 KB / 2 = 512)
	SRA H
	RR L
	JP PRNP29

PRNP27:	; D=4: HL = HL / 1 (1 KB / 1 = 1024)

PRNP28:	LD A,D
	CP 4
	JP NZ,PRNP29
	
	NOP		; ???

PRNP29:	CALL PRNTHL	; print HL decimal
	LD HL,TKAP1
	CALL PRNMSG
	CALL CRLF
	RET
	
;-----------------------------------------------------------------------------
; HL = HL * DE
; for capacity calculation

MULHLDE:
	LD A,16
	PUSH DE
	POP BC
	LD DE,0
	EX DE,HL

MULHL1:	PUSH AF
	BIT 0,E
	JP Z,MULHL2
	
	ADD HL,BC

MULHL2:	SRA H
	RR L
	RR D
	RR E
	POP AF
	DEC A
	JR NZ,MULHL1
	
	EX DE,HL 	; LSB to HL
	RET
	
;-----------------------------------------------------------------------------
; Print CR/LF

CRLF:	LD HL,TCRLF
	CALL PRNMSG
	RET

;-----------------------------------------------------------------------------

TKAP:	DEFB 'Speicherkapazitaet :  ',0

TKAP1:	DEFB ' KBytes',0

TMINI:	DEFB 'Mini-Laufwerk  ',0

TMAXI:	DEFB 'Maxi-Laufwerk  ',0

TFLO2:	DEFB 'FLO2 (C0h)  ',0

TFLO1A:	DEFB 'FLO1 (40h)  ',0

TFLO1B:	DEFB 'FLO1 (30h)  ',0

TFLO1C:	DEFB 'FLO1 (C0h)  ',0

TFM:	DEFB 'FM  ',0

TMFM:	DEFB 'MFM  ',0

TECMA:	DEFB 'ECMA70 ',0

TSPUREN:
	DEFB 'Anzahl Spuren    = ',0

TSEKTOREN:
	DEFB 'Anzahl Sektoren  = ',0

TBYTES:	DEFB 'Bytes/pro Sektor = ',0

TLAUFWERK:
	DEFB 'Laufwerk ',0

TEINSEITIG:
	DEFB 'Vorderseite wird formatiert',0

TRUECKSEITE:
	DEFB 'Rueckseite wird formatiert',0

TRUECKSSO:
	DEFB 'Rueckseite wird mit SSO formatiert',0

TZWEISEITIG:
	DEFB 'beide Seiten werden formatiert',0

TZWEISSO:
	DEFB 'beide Seiten werden formatiert',0dh,0ah
	DEFB 'Seite 1 mit SSO, Seite 0 normal',0

FORMTXT:
	DEFB 0dh,0ah
	DEFB 'ACHTUNG Diskette wird formatiert',0dh,0ah
	DEFB 'Start = "J"',0dh,0ah
	DEFB 0

HEADTXT:
	DEFB 1ah,0dh,0ah
	DEFB ' Universal Formatierer  V 1.22 , Rolf-Dieter Klein / JS ',0dh,0ah
	DEFB ' (C) 1984, Muenchen ',0dh,0ah
	DEFB 0dh,0ah
	DEFB ' --   Bitte Systemdiskette herausnehmen    -- ',0dh,0ah
	DEFB ' -- und zu formatierende Diskette einlegen -- ',0dh,0ah
	DEFB 0dh,0ah
	DEFB 'Minilaufwerke (5 1/4") = 1',0dh,0ah
	DEFB 'Maxilaufwerke (8"    ) = 2',0dh,0ah
	DEFB 'Std  8" SD SD 77 Spur  = 3',0dh,0ah
	DEFB 'ECMA 70 DD SD 40 Spur  = 4',0dh,0ah
	DEFB 'NDR- DD DS 80 Spur     = 5',0dh,0ah
	DEFB 'ENDE                   = 6',0dh,0ah
	DEFB 0dh,0ah,0

MENUE2:	DEFB 1ah,0dh,0ah
	DEFB 'einfache Schreibdichte = 1',0dh,0ah
	DEFB 'doppelte Schreibdichte = 2',0dh,0ah
	DEFB 0dh,0ah,0

MENUE3:	DEFB 1ah,0dh,0ah
	DEFB '35 Spuren  = 1',0dh,0ah
	DEFB '40 Spuren  = 2',0dh,0ah
	DEFB '70 Spuren  = 3',0dh,0ah
	DEFB '77 Spuren  = 4',0dh,0ah
	DEFB '80 Spuren  = 5',0dh,0ah
	DEFB 0dh,0ah,0

MENUE4:	DEFB 1ah,0dh,0ah
	DEFB 'Einseitiges Laufwerk     = 1',0dh,0ah
	DEFB 'Doppeltseitiges Laufwerk = 2',0dh,0ah
	DEFB 'Doppeltseitig und SSO    = 3',0dh,0ah
	DEFB 0dh,0ah,0

MENUE5A:
; einfache Dichte, Minifloppy
	DEFB 1ah,0dh,0ah
	DEFB '128 Bytes pro Sektor  (16 pro Track) = 1',0dh,0ah
	DEFB '128 Bytes pro Sektor  (18 pro Track) = 2',0dh,0ah
	DEFB '256 Bytes pro Sektor  (10 pro Track) = 3',0dh,0ah
	DEFB 0dh,0ah,0

MENUE5B:
	; doppelte Dichte, Minifloppy
	DEFB 1ah,0dh,0ah
	DEFB '256 Bytes pro Sektor  (16 pro Track) = 1',0dh,0ah
	DEFB '512 Bytes pro Sektor  (9 pro Track)  = 2',0dh,0ah
	DEFB '512 Bytes pro Sektor  (10 pro Track) = 3',0dh,0ah
	DEFB '1024 Bytes pro Sektor (5 pro Track)  = 4',0dh,0ah
	DEFB 0dh,0ah,0

MENUE5C:
	; einfache Dichte Maxifloppy
	DEFB 1ah,0dh,0ah
	DEFB '128 Bytes pro Sektor (26 pro Track) = 1',0dh,0ah
	DEFB '256 Bytes pro Sektor (15 pro Track) = 2',0dh,0ah
	DEFB 0dh,0ah,0

MENUE5D:
	; doppelte Dichte Maxifloppy
	DEFB 1ah,0dh,0ah
	DEFB '256 Bytes pro Sektor (26 pro Track) = 1',0dh,0ah
	DEFB '512 Bytes pro Sektor (14 pro Track) = 2',0dh,0ah
	DEFB '512 Bytes pro Sektor (15 pro Track) = 3',0dh,0ah
	DEFB '512 Bytes pro Sektor (16 pro Track) = 4',0dh,0ah
	DEFB '1024 Bytes pro Sektor (8 pro Track) = 5',0dh,0ah
	DEFB '1024 Bytes pro Sektor (9 pro Track) = 6',0dh,0ah
	DEFB 0dh,0ah,0

MENUE6:	DEFB 1ah,0dh,0ah
	DEFB 'Laufwerk              A = 1',0dh,0ah
	DEFB 'Laufwerk              B = 2',0dh,0ah
	DEFB 'Laufwerk              C = 3',0dh,0ah
	DEFB 'Laufwerk              D = 4',0dh,0ah
	DEFB 'Laufwerk A Rueckseite A = 5',0dh,0ah
	DEFB 'Laufwerk B Rueckseite B = 6',0dh,0ah
	DEFB 'Laufwerk C Rueckseite C = 7',0dh,0ah
	DEFB 'Laufwerk D Rueckseite D = 8',0dh,0ah
	DEFB 'NEUSTART    = 9',0dh,0ah
	DEFB 'ENDE        = 0',0dh,0ah
	DEFB 0dh,0ah,0

MENUE7:	DEFB 1ah,0dh,0ah
	DEFB 'FLO2-Maxi/Mini (0C0h) = 1',0dh,0ah
	DEFB 'FLO1-Maxi (40h)       = 2',0dh,0ah
	DEFB 'FLO1-Mini (30h)       = 3',0dh,0ah
	DEFB 'FLO1-Maxi/Mini (0C0h) = 4',0dh,0ah
	DEFB 0dh,0ah,0

FMSG:	DEFB 1ah,0dh,0ah
	DEFB 'Diskette wird formatiert ... bitte warten ',0dh,0ah
	DEFB 0dh,0ah,0

F6MSG:	DEFB 0dh,0ah
	DEFB 'Schreibschutz gesetzt',0dh,0ah
	DEFB 'Neustart = Taste W druecken',0dh,0ah,0

F5MSG:	DEFB 0dh,0ah
	DEFB 'Record Typ ist falsch',0dh,0ah
	DEFB 'Neustart = Taste W druecken',0dh,0ah,0

F4MSG:	DEFB 0dh,0ah
	DEFB 'Record nicht gefunden',0dh,0ah
	DEFB 'Neustart = Taste W druecken',0dh,0ah,0

F3MSG:	DEFB 0dh,0ah
	DEFB 'CRC Fehler aufgetreten',0dh,0ah
	DEFB 'Neustart = Taste W druecken',0dh,0ah,0

F2MSG:	DEFB 0dh,0ah
	DEFB 'CPU zu langsam fuer gewaehltes Format-- Datenverlust',0dh,0ah
	DEFB 'hoeherer Takt erforderlich',0dh,0ah
	DEFB 'Neustart = Taste W druecken',0dh,0ah,0

F0MSG:	DEFB 0dh,0ah
	DEFB 'Fehler aufgetreten. Neustart = Taste W druecken',0dh,0ah,0

TKMSG:	DEFB 0dh,0ah
	DEFB 'Track = ',0

SKMSG:	DEFB ', Sektor = ',0

TCRLF:	DEFB 0dh,0ah,0

RMSG:	DEFB 0dh,0ah
	DEFB 'Laufwerk nicht READY ... bitte pruefen:',0dh,0ah
	DEFB ' 1. Diskette falschherum eingelegt',0dh,0ah
	DEFB ' 2. Laufwerkstuere nicht geschlossen',0dh,0ah
	DEFB ' 3. falsche Laufwerksnummer angegeben',0dh,0ah
	DEFB ' 4. Laufwerksmotor dreht sich nicht',0dh,0ah
	DEFB ' 5. READY-Leitung nicht ok',0dh,0ah 
	DEFB 0dh,0ah
	DEFB 'Neustart = Taste W druecken',0dh,0ah,0

VMSG:	DEFB 0dh,0ah
	DEFB 'Diskette wird geprueft ... bitte warten',0dh,0ah
	DEFB 0dh,0ah,0

FIMSG:	DEFB 1ah,0dh,0ah
	DEFB 'Systemdiskette in Laufwerk A einlegen,',0dh,0ah
	DEFB 'dann CR (carriage return) druecken.',0dh,0ah,0

	DEFB 0		; v1.22
	
USER:	DEFB 0  	; 0=FLO1/FLO2 (C0h), 1=FLO1 Maxi, 2=FLO1 Mini
FLOTYP:	DEFB 0    	; 0=FLO2 (C0h), 1=FLO1 (C0h) (only if USER=0)
MINMAX:	DEFB 0  	; 0=Mini, 1=Maxi
ECMA:	DEFB 0  	; 1=ECMA70 format (SD,128 on track 0)
BYTCNT:	DEFW 0  	; Anzahl der Bytes pro Sektor
FILLER:	DEFB 0E5h 	; fill byte std=E5h
DENSITY:DEFB 0  	; 0=single-density, 1=double-density
GAPLEN:	DEFB 0  	; Gap 3 Laenge zwischen Sektoren
TRKCNT:	DEFB 0  	; Anzahl der Spuren
SSDS:	DEFB 0  	; 0=single-sided, 1=double-sided
SECCNT:	DEFB 0  	; Anzahl der Sektoren pro Spur
DRIVE:	DEFB 0  	; drive code (1,2,4,8), Bit7=1: Side 1
SIDESEL:DEFB 0  	; SSO: 0=Seite 0, 80h=Seite 1 (wird nur bei USESSO=1 gesetzt fuer FD1797)
USESSO:	DEFB 0  	; 0=no SSO, 1=use SSO (nur fuer FD1797)
		
CURTRK:	DEFB 0  	; aktuelle Spur
CURSEC:	DEFB 0  	; aktueller Sektor

FORMTAB:	; Formatierbereich, hier wird ein Track gelegt.

	END start
