	.z80

	;*********************************************************************
	;* Universal Formatierer fuer Mini/Maxi                              *
	;* Rev 1.22 (C) 1984 Rolf-Dieter Klein / JS                          *
	;* FLO2-Baugruppe / MC/ NDR/                                         *
	;* FLO1-Baugruppe MC                                                 *
	;* 31.05.2026 *dg* Quellcode der Version 1.22 aus COM-Datei          *
	;*                 wiederhergestellt                                 *
	;* 22.06.2026 *dg* Quellcode ueberarbeitet und dokumentiert          *
	;*                 Binaer identisch zur Version 1.22                 *
	;*                 Work in progress...                                  *
	;*********************************************************************

	; arbeitet unabhaengig vom CP/M - Betriebsystem.
	; verwendet den Monitor

; IO ADDESSES FLO2 MINI/Maxi
FLO0	EQU 0C0H
FLO1	EQU 0C1H
FLO2	EQU 0C2H
FLO3	EQU 0C3H
FLO4	EQU 0C4H

; IO ADDESSES FLO1 MAXI
FLOA0	EQU 040H
FLOA1	EQU 041H
FLOA2	EQU 042H
FLOA3	EQU 043H
FLOA4	EQU 044H

; IO ADDESSES FLO1 MINI
FLOB0	EQU 030H
FLOB1	EQU 031H
FLOB2	EQU 032H
FLOB3	EQU 033H
FLOB4	EQU 034H

;-----------------------------------------------------------------------------

	JP START 	; Hauptprogramm

;-----------------------------------------------------------------------------

CONOUT:	JP 0F009H 	; Ausgabe eines Zeichens in C

;-----------------------------------------------------------------------------

CONIN:	CALL 0F003H 	; Eingabe eines Zeichens nach A
	AND 7FH
	RET

;-----------------------------------------------------------------------------
; Interrupt routine

INTR:	POP AF  	; spez. Int-Routine
	IN A,(FLOA0)
	IN A,(FLOB0)
	IN A,(FLO0) 	; Status FLO ist wichtig
	EI
	RETI  		; fertig

;-----------------------------------------------------------------------------
; Universal Formatierer

FORMAT:	LD HL,FMSG 
	CALL PRNMSG
	IN A,(FLOA0) 	; ggf. bei gemischtem Betrieb auch
	IN A,(FLOB0)   	; andere Ports loeschen
	IN A,(FLO0) 	; alle Interrupts loeschen

	IM 1  		; MODE 1, RST-7 verwenden
	LD A,0C3H 	; Sprungvektor setzen (JP)
	LD (38H),A
	LD HL,INTR
	LD (39H),HL 	; auf Interruptroutine

	; --- format ---

	CALL HOME 	; set head to track 0

	XOR A
	LD (CURTRK),A  	; start with track 0
	LD A,(TRKCNT) 	; number of tracks
	LD B,A

FORM1:	; loop
	PUSH BC
	CALL ECMACHK 	; check if track 0 and ECMA70
	CALL GENTRK 	; create track
	CALL FRMTRK 	; format track
	CALL ERRCHK
	
	LD A,(SSDS)
	CP 1
	JP NZ,FORM3	; single sided
	
	; double-sided
	LD A,(DRIVE)	; Rueckseite setzen
	OR 80H  	; aber kein Side-sel
	LD (DRIVE),A
	
	LD A,(USESSO)
	OR A
	JP Z,FORM2	; -> no SSO
	
	; SSO
	LD A,80H
	LD (SIDESEL),A 	; setzen

FORM2:	CALL GENTRK
	CALL FRMTRK
	CALL ERRCHK
	LD A,(DRIVE)
	AND 7FH
	LD (DRIVE),A   
	XOR A
	LD (SIDESEL),A

FORM3:	LD A,(CURTRK)
	INC A
	LD (CURTRK),A
	LD B,A
	LD A,(TRKCNT)
	CP B
	JP Z,FORM4	; AKTRK = TRKCNT
	
	CALL STEPIN
	
FORM4:	LD C,'F'
	CALL CONOUT 	; Meldung FFFFF ausgeben bei jeder Spur ein F
	POP BC
	DJNZ FORM1	; -> loop

	; verify
	
	LD HL,VMSG
	CALL PRNMSG
	CALL HOME	; set head to track 0
	XOR A
	LD (CURTRK),A  	; start with track 0
	LD A,(TRKCNT) 	; number of tracks
	LD B,A

FORM5:	; loop
	PUSH BC
	CALL ECMACHK
	CALL VERIFY
	LD A,(SSDS)
	CP 1
	JP NZ,FORM7	; -> single-sided

	; double-sided
	LD A,(DRIVE)
	OR 80H
	LD (DRIVE),A
	LD A,(USESSO)
	OR A
	JP Z,FORM6	; -> no SSO
	
	; SSO
	LD A,80H
	LD (SIDESEL),A 	; setzen

FORM6:	CALL VERIFY
	LD A,(DRIVE)
	AND 7FH
	LD (DRIVE),A 
	XOR A
	LD (SIDESEL),A 	; wieder Seite 0

FORM7:	LD A,(CURTRK)
	INC A
	LD (CURTRK),A
	LD B,A
	LD A,(TRKCNT)
	CP B
	JP Z,FORM8	; -> TRKCNT = CURTRK

	CALL STEPIN

FORM8:	LD C,'V' 
	CALL CONOUT 	; VVVVV fuer Verify
	POP BC
	DJNZ FORM5	; -> loop
	
	CALL HOME 	; set head to track 0
	RET
	
;-----------------------------------------------------------------------------
; Set ECMA70 format

ECMACHK:
	LD A,(ECMA)	; 1=ECMA70
	OR A
	RET Z  		; no ECMA70
	
	XOR A
	LD (MINMAX),A 	; always mini drive
	
	LD A,(CURTRK)
	OR A
	JP NZ,ECMAC1	; -> not track 0
	
	; track 0, format single-density
	LD HL,128
	LD (BYTCNT),HL
	
	LD A,0 		; single density
	LD (DENSITY),A 	;
	LD A,0		; single-sided
	LD (SSDS),A
	LD A,16		; 16 sectors
	LD (SECCNT),A
	LD A,27
	LD (GAPLEN),A
	LD A,40		; 40 tracks
	LD (TRKCNT),A
	JP ECMAC2
	
ECMAC1:	; not track 0, format double density
	LD HL,256
	LD (BYTCNT),HL
	
	LD A,1		; double density
	LD (DENSITY),A
	LD A,0 		; single-sided
	LD (SSDS),A
	LD A,16 	; 16 sectors
	LD (SECCNT),A
	LD A,54
	LD (GAPLEN),A 	; STD Gap
	LD A,40 	; 40 tracks
	LD (TRKCNT),A

ECMAC2:	RET

;-----------------------------------------------------------------------------
; General error check routine

; error code in A
;   bit 2 = CPU to slow
;   bit 3 = CRC error
;   bit 4 = record not found
;   bit 5 = wrong record type
;   bit 6 = write protected

ERRCHK:	OR A
	RET Z  	; =0? -> Status ok
	
	; TRACK, Spur ausgeben
	PUSH AF 	; save error code
	LD HL,TKMSG
	CALL PRNMSG
	LD A,(CURTRK)
	LD L,A
	LD H,0 
	CALL PRNTHL
	LD HL,SKMSG
	CALL PRNMSG
	LD A,(CURSEC)
	LD L,A
	LD H,0
	CALL PRNTHL
	CALL CRLF

	POP AF  	; restore error code
	
	; check bit 2
	BIT 2,A
	LD HL,F0MSG 	; error message
	JP Z,ERRC1	; -> bit 2 not set
	
	; bit 2, CPU too slow
	LD HL,F2MSG

ERRC1:	; check bit 3
	BIT 3,A
	JP Z,ERRC2	; -> bit 3 not set

	; bit 3, CRC errror
	LD HL,F3MSG

ERRC2:	; check bit 4
	BIT 4,A
	JP Z,ERRC3	; -> bit 4 not set
	
	; bit 4, record not found
	LD HL,F4MSG
	
ERRC3:	; check bit 5
	BIT 5,A
	JP Z,ERRC4	; -> bit 5 not set

	; bit 5, wrong record type
	LD HL,F5MSG

ERRC4:	; check bit 6
	BIT 6,A
	JP Z,ERRC5	; -> bit 6 not set

	; bit 6, write protected
	LD HL,F6MSG
	
ERRC5:	; check bit 7
	JP Z,ERRC6
	
	; bit 7, write protected
	LD HL,F6MSG 	; dominant is write proteced error

ERRC6:	CALL PRNMSG

ERRC7:	; wait for 'W' or 'w'
	CALL CONIN
	CP 'W'
	JP Z,ERRC8
	CP 'w'
	JP NZ,ERRC7

ERRC8:	JP START 	; no stack adjust needed
	
;-----------------------------------------------------------------------------
; PRNMSG decimal value in HL
	
PRNTHL:	XOR A
	PUSH AF

PRNTH1:	; digit loop
	LD A,16
	LD BC,10 	; div 10
	LD DE,0 	; Rest
	EX DE,HL
	
PRNTH2:	; division loop
	PUSH AF
	SLA E
	RL D
	RL L
	RL H
	SET 0,E
	XOR A
	SBC HL,BC
	JP NC,PRNTH3
	
	ADD HL,BC
	RES 0,E
	
PRNTH3:	POP AF
	DEC A
	JR NZ,PRNTH2
	
	EX DE,HL 	; HL=result, DE=remainder
	LD A,E
	OR 30H
	PUSH AF
	LD A,H
	OR L
	JR NZ,PRNTH1	; -> loop
	
PRNTH4:	;output
	POP AF
	OR A
	RET Z
	
	LD C,A
	CALL CONOUT
	JR PRNTH4
	
;-----------------------------------------------------------------------------
; Create new track
	
GENTRK:	LD IX,FORMTAB 	; start of format table

	; header
	LD A,(DENSITY)
	OR A
	JP NZ,GENT1	; -> double-density

	; single-density
	LD B,16
	LD C,0FFH 	; fuellbyte 
	JP GENT2

GENT1:	; double density
	LD B,32
	LD C,04EH
	
GENT2:
GENT3:	LD (IX+0),C
	INC IX
	DEC B
	JP NZ,GENT3

	; create sectors
	
	LD A,1		; start with sector 1
	LD (CURSEC),A 	; current sector
	LD A,(SECCNT)
	LD B,A

GENT4:	; sector loop
	PUSH BC
	
	; ID field
	LD A,(DENSITY)
	OR A
	JP NZ,GENT11	; -> double density

	; --- single density ---
	
	LD B,6

GENT5:	LD (IX+0),0
	INC IX
	DEC B
	JP NZ,GENT5
	
	LD (IX+0),0FEH 	; ID address marc
	INC IX
	LD A,(CURTRK)	; track number 0..n
	LD (IX+0),A
	INC IX

	LD A,(SIDESEL) 	; side
	AND 80H  	;
	OR A
	JP NZ,GENT6	; -> side 1

	; side 0
	LD (IX+0),0  	; Seite 0
	JP GENT7

GENT6:	; side 1
	LD (IX+0),1  	; Seite 1

GENT7:	INC IX
	LD A,(CURSEC)
	LD (IX+0),A  	; Sector 1..n
	INC IX
	LD HL,(BYTCNT)	; sector size (128,256,512,1024)
	LD A,H  	; 0,1,2,4 da 80h,100h,200h,400h
	CP 4
	JP NZ,GENT8	; -> not 4
	
	; A=4
	LD A,3

GENT8:	LD (IX+0),A  	; Laengenkennung (0,1,2,3)
	INC IX
	LD (IX+0),0F7H 	; create CRC
	INC IX

	LD B,11
GENT9:	LD (IX+0),0FFH
	INC IX
	DEC B
	JP NZ,GENT9
	
	LD B,6
GENT10:	LD (IX+0),0
	INC IX
	DEC B
	JP NZ,GENT10
	
	LD (IX+0),0FBH 	; data mark
	INC IX
	JP GENT20

	; --- double density ---

GENT11:	LD B,12
GENT12:	LD (IX+0),0
	INC IX
	DEC B
	JP NZ,GENT12
	
	LD B,3
GENT13:	LD (IX+0),0F5H
	INC IX
	DEC B
	JP NZ,GENT13
	
	LD (IX+0),0FEH 	; ID address mark
	INC IX
	LD A,(CURTRK)
	LD (IX+0),A  	; track 0..n
	INC IX
	LD A,(SIDESEL) 	; for side-sel SSO
	AND 80H
	OR A
	JP NZ,GENT14	; -> side 1

	; side 0
	LD (IX+0),0  	; side 0
	JP GENT15
	
GENT14:	LD (IX+0),1  	; side 1

GENT15:	INC IX
	LD A,(CURSEC)
	LD (IX+0),A  	; sector 1..n
	INC IX
	LD HL,(BYTCNT)	; sector size (128,256,512,1024)
	LD A,H  	; 0,1,2,4 da 80h,100h,200h,400h
	CP 4
	JP NZ,GENT16
	
	; A=4
	LD A,3

GENT16:	LD (IX+0),A  	; 0,1,2,3 Laengenkennung
	INC IX
	LD (IX+0),0F7H 	; create CRC
	INC IX
	
	LD B,22
GENT17:	LD (IX+0),04EH
	INC IX
	DEC B
	JP NZ,GENT17

	LD B,12
GENT18:	LD (IX+0),0
	INC IX
	DEC B
	JP NZ,GENT18
	
	LD B,3
GENT19:	LD (IX+0),0F5H
	INC IX
	DEC B
	JP NZ,GENT19
	
	LD (IX+0),0FBH 	; data mark
	INC IX

	; write data block

GENT20:	LD A,(FILLER) 	; data byte
	LD C,A
	LD HL,(BYTCNT) ; 128,256,512,1024

GENT21:	LD (IX+0),C
	INC IX
	DEC HL
	LD A,H
	OR L
	JP NZ,GENT21
	
	LD (IX+0),0F7H 	; write CRC
	INC IX
	LD A,(DENSITY)
	OR A
	JP NZ,GENT22	; -> double density
	
	; single density
	LD C,0FFH  	; Datenbyte SD
	JP GENT23

GENT22:	; double density
	LD C,04EH  	; Datenbyte DD

GENT23:	LD A,(GAPLEN)
	LD B,A  	; store gap 3

GENT24:	LD (IX+0),C
	INC IX
	DEC B
	JP NZ,GENT24
	
	; next sector
	LD A,(CURSEC)
	INC A
	LD (CURSEC),A 	; neue Sektorennummer
	POP BC
	DEC B
	JP NZ,GENT4	; -> sector loop
	
	; fill to the end
	LD A,(DENSITY)
	OR A
	JP NZ,GENT25	; -> double-sided

	; single-sided
	LD C,0FFH 	; store gap 4
	JP GENT26

GENT25:	; double-sided
	LD C,04EH

GENT26:	LD HL,1000	; use big number to make shure there are no
			; unwanted bytes till the index puls
GENT27:	LD (IX+0),C
	INC IX
	DEC HL
	LD A,H
	OR L
	JP NZ,GENT27
	
	RET
	
;-----------------------------------------------------------------------------
; Verify a track, test-read read all sectors
	
VERIFY:	CALL DELAY  	; head settle time

	LD A,1
	LD (CURSEC),A
	LD A,(SECCNT)

	LD B,A
	
VERIF1:	PUSH BC
	CALL READ  	; simply read
	CALL ERRCHK  	; 0=ok, otherwise message
	
	LD A,(CURSEC)
	INC A
	LD (CURSEC),A
	
	POP BC
	DEC B
	JP NZ,VERIF1
	
	RET
	
;-----------------------------------------------------------------------------
; Delay loop 40ms..10ms (???)

DELAY:	PUSH BC
	LD BC,0D05H

DELAY1:	DEC BC
	LD A,C
	OR B
	JP NZ,DELAY1
	
	POP BC
	RET
	
;-----------------------------------------------------------------------------
; Set head to track 0

HOME:	LD A,(USER)
	OR A  		; 0=FLO2
	JP NZ,HOME4
	
	; FLO2
	
	LD HL,250 	; max retries
	
HOME1:	; retry loop
	PUSH  HL
	IN A,(FLO0)
	CALL DELAY
	EI  		; enable interrupts
	CALL REXEC
	DI
	POP HL
	IN A,(FLO0) 	; check status
	AND 80H 	; <>0 dann nicht ready
	JP Z,HOME12
	
	DEC HL
	LD A,H
	OR L  		
	JR NZ,HOME1	; -> retry
	
	; error
	LD HL,RMSG	; not ready
	CALL PRNMSG

HOME2:	; wait for 'W' / 'w'
	CALL CONIN
	CP 'W'
	JP Z,HOME3
	CP 'w'
	JP NZ,HOME2

HOME3:	JP START
	
	;---------------------------------------------------------------------

HOME4:	CP 1  		; 1=FLO1-Maxi
	JP NZ,HOME8

	; FLO1 Maxi
	
	LD HL,250 	; max retries
	
HOME5:	; retry loop
	PUSH HL
	IN A,(FLOA0)
	CALL DELAY
	EI  		; enable interrupts
	CALL RAEXEC
	DI
	POP HL
	IN A,(FLOA0) 	; check status
	AND 80H
	JP Z,HOME12	; -> 0=ready
	
	DEC HL
	LD A,H
	OR L
	JR NZ,HOME5	; -> retry
	
	; error
	LD HL,RMSG	; not ready
	CALL PRNMSG

HOME6:	; wait for 'W' / 'w'
	CALL CONIN
	CP 'W'
	JP Z,HOME7
	CP 'w'
	JP NZ,HOME6

HOME7:	JP START
	
	;---------------------------------------------------------------------
	
HOME8:	; FLO1-Mini (???)

	LD HL,250 	; max retries

HOME9:	; retry loop
	PUSH  HL
	IN A,(FLOB0)
	CALL DELAY
	EI  		; enable interrupts
	CALL RBEXEC
	DI
	POP HL
	IN A,(FLOB0) 	; check status
	AND 80H
	JP Z,HOME12	; -> 0=ready
	
	DEC HL
	LD A,H
	OR L
	JR NZ,HOME9	; -> retry

	; error
	LD HL,RMSG	; not ready
	CALL PRNMSG

HOME10:	; wait for 'W' / 'w'
	CALL CONIN
	CP 'W'
	JP Z,HOME11
	CP 'w'
	JP NZ,HOME10

HOME11:	JP START

HOME12:	; finished
	RET

;-----------------------------------------------------------------------------
; Ausfuehrung FLO2

REXEC:	CALL SETCTR	; setup controller
	LD A,0BH 	; Rstore ohne Verify
	OUT (FLO0),A
	HALT  		; UEBER INT zurueck

;-----------------------------------------------------------------------------
; Ausfuehrung FLO1 Maxi

RAEXEC:	CALL SETCTR	; setup controller
	LD A,0BH 	; Rstore ohne Verify
	OUT (FLOA0),A
	HALT  		; UEBER INT zurueck

;-----------------------------------------------------------------------------
; Ausfuehrung FLO1 Mini

RBEXEC:	CALL SETCTR	; setup controller
	LD A,0BH 	; Rstore ohne Verify
	OUT (FLOB0),A
	HALT  		; UEBER INT zurueck

;-----------------------------------------------------------------------------
; Step ausfuehren

STEPIN:	CALL DELAY 	; settle head
	EI
	CALL STPEXEC
	DI
	RET

;-----------------------------------------------------------------------------

STPEXEC:
 	; Laufwerk und Dichte
	CALL SETCTR	; setup controller
	LD A,(USER)
;1 	IF A=0
	OR A
	JP NZ,.L52
	LD A,5BH
	OUT (FLO0),A 	; Step ohne Verify
;1 	ELSEIF A=1
	JP .L53
.L52:
	CP 1
	JP NZ,.L54
	LD A,5BH
	OUT (FLOA0),A
;1 	ELSEIF A=2
	JP .L53
.L54:
	CP 2
	JP NZ,.L55
	LD A,5BH 
	OUT (FLOB0),A
;1 	ENDIF
.L55:
.L53:
	HALT 

;-----------------------------------------------------------------------------

READ:	LD B,2
READ1:
	PUSH BC
	EI
	CALL READEX
	DI
	POP BC  	; Fehlerzaehler
	LD A,(USER)
;1 	IF A=0
	OR A
	JP NZ,.L56
	IN A,(FLO0) 	; Status beim Lesen pruefen
;1 	ELSEIF A=1
	JP .L57
.L56:
	CP 1
	JP NZ,.L58
	IN A,(FLOA0)
;1 	ELSEIF A=2
	JP .L57
.L58:
	CP 2
	JP NZ,.L59
	IN A,(FLOB0)
;1 	ENDIF
.L59:
.L57:
	AND 00111100B 	; =0 dann ok
	RET Z
	
	DJNZ READ1 	; max Retry
	RET

;-----------------------------------------------------------------------------

READEX:
	CALL SETCTR 	; Dichtecode setzen, Head ist down.
	LD A,(USER)
;1 	IF A=0
	OR A
	JP NZ,.L60

	LD A,(CURSEC)
	OUT (FLO2),A 	; Sektor definieren
	LD HL,FORMTAB 	; dorthin Daten legen 
	LD C,FLO3 	; Datenport
	LD A,(SIDESEL) 	; fuer Side-Control
	AND 80H
	RLCA  	; BIT 0
	RLCA  	; BIT 1
	AND 00000010B 	; 1=Seite 1
	ADD A,88H 	; kein Delay abwarten, head ist down
	OUT (FLO0),A 	; und Befehl geben
RED1:
	IN A,(FLO4)
	RLCA
	JP NC,RED1 	; warten bis DRQ-da ist
	
	INI  	; DATEN ablegen
	JP RED1 	; bis alle Daten gelesen, dann Interrupt 
;1 	ELSEIF A=1 	; flo 1 maxi
	JP .L61
.L60:
	CP 1 
	JP NZ,.L62
	LD A,(CURSEC)
	OUT (FLOA2),A 	; Sektor definieren
	LD HL,FORMTAB 	; dorthin Daten legen 
	LD C,FLOA3 	; Datenport
	LD A,(SIDESEL) 	; fuer Side-Control
	AND 80H
	RLCA  	; BIT 0
	RLCA  	; BIT 1
	AND 00000010B 	; 1=Seite 1
	ADD A,88H 	; kein Delay abwarten, head ist down
	OUT (FLOA0),A 	; und Befehl geben
RAED1:
	IN A,(FLOA4)
	RLCA
	JP NC,RAED1 	; warten bis DRQ-da ist
	INI  	; DATEN ablegen
	JP RAED1 	; bis alle Daten gelesen, dann Interrupt 
;1 	ELSEIF A=2 	; flo1 Mini
	JP .L61
.L62:
	CP 2 
	JP NZ,.L63
	LD A,(CURSEC) 
	OUT (FLOB2),A 	; Sektor definieren
	LD HL,FORMTAB 	; dorthin Daten legen 
	LD C,FLOB3 	; Datenport
	LD A,(SIDESEL) 	; fuer Side-Control
	AND 80H
	RLCA  	; BIT 0
	RLCA  	; BIT 1
	AND 00000010B 	; 1=Seite 1
	ADD A,88H 	; kein Delay abwarten, head ist down
	OUT (FLOB0),A 	; und Befehl geben
RBED1:
	IN A,(FLOB4)
	RLCA
	JP NC,RBED1 	; warten bis DRQ-da ist
	INI  	; DATEN ablegen
	JP RBED1 	; bis alle Daten gelesen, dann Interrupt 
;1 	ENDIF
.L63:
.L61:
	RET 

;-----------------------------------------------------------------------------
; Setup controller

SETCTR:	PUSH BC
	LD A,(DRIVE) 	; Laufwerkscode
	LD B,A 
	LD A,(DENSITY)
;1 	IF A=0   	; SD
	OR A
	JP NZ,.L64
	LD A,B
	OR 10H
	LD B,A
;1 	ENDIF
.L64:
	LD A,(MINMAX)
;1 	IF A=0   	; Mini
	OR A
	JP NZ,.L65
	LD A,B
	OR 20H
	LD B,A
;1 	ENDIF
.L65:
	LD A,(USER)
;1 	IF A=0   	; FLO2
	OR A
	JP NZ,.L66
	; V1.22
	LD A,(FLOTYP)
	CP 01H
	JP NZ,L0653
	
	LD A,B  	; OK Code fertig
	XOR 10H
	JP L0654
L0653:
	LD A,B
L0654:
	POP BC
	OUT (FLO4),A	;
;1 	ELSEIF A=1  	; MAXI
	JP .L67
.L66:
	CP 1  
	JP NZ,.L68
	LD A,B
	POP BC
	XOR 10H  	; DENSE invertiert bei FLO1
	OUT (FLOA4),A
;1 	ELSEIF A=2
	JP .L67
.L68:
	CP 2
	JP NZ,.L69
	LD A,B
	POP BC
	XOR 10H  	; DENSE invertiert bei FLO1
	OUT (FLOB4),A
;1 	ENDIF
.L69:
.L67:
	RET
	
;-----------------------------------------------------------------------------
; Format track

FRMTRK:	CALL DELAY
	EI
	CALL FMT
	DI
	LD A,(USER)
;1 	IF A=0
	OR A
	JP NZ,.L70
	IN A,(FLO0) 	; pruefen auf Schreibschutz, Datalost
;1 	ELSEIF A=1
	JP .L71
.L70:
	CP 1
	JP NZ,.L72
	IN A,(FLOA0)
;1 	ELSEIF A=2
	JP .L71
.L72:
	CP 2
	JP NZ,.L73
	IN A,(FLOB0)
;1 	ENDIF
.L73:
.L71:
	AND 44H
	RET

;-----------------------------------------------------------------------------

FMT:	CALL SETCTR 	; Dichte einstellen etc., auf Port FLO4
	LD A,(USER)
;1 	IF A=0  	; FLO 2
	OR A
	JP NZ,.L74
	LD HL,FORMTAB 	; Startadresse 
	LD C,FLO3 	; Datenport
	LD A,(SIDESEL) 	; Side-Flag setzen, fuer SSO-Ausgang
	AND 80H 	; wenn USESSO auf 80h gesetzt wird
	RLCA  	; BIT 0
	RLCA  	; BIT 1
	AND 00000010B 	; 1=Seite 1
	OR 0F4H 	; Formatier-Befehl+nicht documentierter
	OUT (FLO0),A 	; Side-Select-Befehl fuer SSO
FMTLP::
	IN A,(FLO4) 	; drq int head
	RLCA  	; BIT 7 ins carry
	JP NC,FMTLP 	; 0=warten 1=fertig i
	OUTI  	; UND BYte ausgeben
	JP FMTLP 	; durch INT wird die Routine gestoppt.
;1 	ELSEIF A=1 	; FLO1 maxi
	JP .L75
.L74:
	CP 1 
	JP NZ,.L76
	LD HL,FORMTAB 	; Startadresse 
	LD C,FLOA3 	; Datenport
	LD A,(SIDESEL) 	; Side-Flag setzen, fuer SSO-Ausgang
	AND 80H 	; wenn USESSO auf 80h gesetzt wird
	RLCA  	; BIT 0
	RLCA  	; BIT 1
	AND 00000010B 	; 1=Seite 1
	OR 0F4H 	; Formatier-Befehl+nicht documentierter
	OUT (FLOA0),A 	; Side-Select-Befehl fuer SSO
FAMTLP::
	IN A,(FLOA4) 	; drq int head
	RLCA  	; BIT 7 ins carry
	JP NC,FAMTLP 	; 0=warten 1=fertig i
	OUTI  	; UND BYte ausgeben
	JP FAMTLP 	; durch INT wird die Routine gestoppt.
;1 	ELSEIF A=2 	; FLO1 mini
	JP .L75
.L76:
	CP 2 
	JP NZ,.L77
	LD HL,FORMTAB 	; Startadresse 
	LD C,FLOB3 	; Datenport
	LD A,(SIDESEL) 	; Side-Flag setzen, fuer SSO-Ausgang
	AND 80H 	; wenn USESSO auf 80h gesetzt wird
	RLCA  	; BIT 0
	RLCA  	; BIT 1
	AND 00000010B 	; 1=Seite 1
	OR 0F4H 	; Formatier-Befehl+nicht documentierter
	OUT (FLOB0),A 	; Side-Select-Befehl fuer SSO
FBMTLP::
	IN A,(FLOB4) 	; drq int head
	RLCA  	; BIT 7 ins carry
	JP NC,FBMTLP 	; 0=warten 1=fertig i
	OUTI  	; UND BYte ausgeben
	JP FBMTLP 	; durch INT wird die Routine gestoppt.
;1 	ENDIF
.L77:
.L75:
	RET

;-----------------------------------------------------------------------------
; Main input loop
	
START:

MAINLOOP:

	LD HL,HEADTXT	; Programm start message and format type
	CALL PRNMSG

	; --- format ---
	
MAIN1:	; wait for 1..6
	CALL CONIN
	CP '6'+1
	JP NC,MAIN1
	CP '1'+0
	JP C,MAIN1
	
MAIN2:	PUSH AF
	XOR A
	LD (ECMA),A 	; 0=no ECMA70 (default)
	LD (USER),A 	; 0=FLO2
	LD A,0E5H
	LD (FILLER),A 	; Filler ist normalerweise E5
	XOR A
	LD (SIDESEL),A 	; no SSO (default)
	LD (USESSO),A	; auch nicht bei Kopfwechsel 
	POP AF
	
	CP '1' 
	JP NZ,MAIN3
	
	; Format 1: Mini 5 1/4"
	XOR A		; 0 = Mini
	LD (MINMAX),A
	CALL SETTRK
	CALL SETDRV
	CALL SETDEN
	CALL SETSEC
	JP MAIN8
	
MAIN3:	CP '2' 
	JP NZ,MAIN4
	
	; Format 2: Maxi 8"
	LD A,1		; 1 = Maxi
	LD (MINMAX),A
	CALL SETTRK
	CALL SETDRV
	CALL SETDEN
	CALL SETSEC
	JP MAIN8

MAIN4:	CP '3'
	JP NZ,MAIN5
	
	; Format 3: Std  8" SD SD 77 Spur
	LD A,1
	LD (MINMAX),A
	LD HL,128 	; 128 Bytes pro Sektor
	LD (BYTCNT),HL
	LD A,0
	LD (DENSITY),A 	; SD
	LD A,27 	; Gaplaenge
	LD (GAPLEN),A
	LD A,0
	LD (SSDS),A 	; single-sided
	LD A,26 	; Sektorenzahl
	LD (SECCNT),A
	LD A,77 	; 0..76
	LD (TRKCNT),A 	; Anzahl Spuren
	JP MAIN8

MAIN5:	CP '4' 
	JP NZ,MAIN6

	; Format 4: ECMA 70 DD SD 40 Spur
	XOR A
	LD (MINMAX),A 	; rev 1.1, loeschen
	LD A,1
	LD (ECMA),A 	; Spezialformat SD erste Spur
	LD (USESSO),A 	; wenn rueckseite dann mit Bit
			; REST In ecma doppelt
	LD HL,256 	; rest DD
	LD (BYTCNT),HL
	LD A,1
	LD (DENSITY),A 	; DD
	LD A,0
	LD (SSDS),A 	; single-sided
	LD A,16 	; Sektorenzahl
	LD (SECCNT),A
	LD A,54
	LD (GAPLEN),A 	; STD Gap
	LD A,40 	; und 40 Spuren
	LD (TRKCNT),A
	JP MAIN8

MAIN6:	CP '5' 
	JP NZ,MAIN7

	; Format 5: NDR- DD DS 80 Spur
	LD A,0 		; MINI
	LD (MINMAX),A
	LD HL,1024 	; Anzahl Bytes
	LD (BYTCNT),HL
	LD A,1 		; DD
	LD (DENSITY),A
	LD A,54 	; Gaplaenge 3
	LD (GAPLEN),A
	LD A,5
	LD (SECCNT),A
	LD A,1
	LD (SSDS),A 	; double-sided
	LD A,1
	LD (USESSO),A 	; und mit Side-Bit
	LD A,80 	; Spuren 0..79
	LD (TRKCNT),A
	JP MAIN8
	
MAIN7:	CP '6' 
	JP NZ,MAIN8
	
	JP MAIN35	; -> exit
	
	; --- FLO type ---

MAIN8:	LD HL,MENUE7 	; FLO type
	CALL PRNMSG

MAIN9:	; wait for 1..3
	CALL CONIN
	CP '4'+1
	JR NC,MAIN10
	CP '1'+0
	JP NC,MAIN11
	
MAIN10:	CP 0DH
	JP NZ,MAIN9

MAIN11:	CP '2'
	JP NZ,MAIN12
	
	; FLO type 2: FLO1 Maxi (40h)
	LD A,1 	; FLO1, maxi
	JP MAIN15
	
MAIN12:	CP '3'
	JP NZ,MAIN13

	; FLO type 3: FLO1 Mini (30h)
	LD A,2 	; FLO2, mini
	JP MAIN15
	
MAIN13:	CP '4'
	JP NZ,MAIN14
	
	; FLO type 4: FLO1-Maxi/Mini (0C0h)
	LD A,01H
	LD (FLOTYP),A
	XOR A  	; FLO2 Mini/maxi
	JP MAIN15
	
MAIN14:	CP '1'
	JP NZ,MAIN15
	
	; FLO type 1: FLO2-Maxi/Mini (0C0h)
	XOR A
	LD (FLOTYP),A
	
MAIN15:	LD (USER),A


	; --- drive ---

MAIN16:	LD HL,MENUE6 	; drive
	CALL PRNMSG

MAIN17:	; wait for 0..9
	CALL CONIN
	CP '9'+1
	JP NC,MAIN17
	CP '0'+0
	JP C,MAIN17
	
	; 1..8
	CP '8'+1
	JP NC,MAIN27
	CP '1'+0
	JP C,MAIN27

	CP '1'
	JP NZ,MAIN18
	
	; drive 1: A
	LD A,1
	JP MAIN25

MAIN18:	CP '2'
	JP NZ,MAIN19
	
	; drive 2: B
	LD A,2
	JP MAIN25

MAIN19:	CP '3'
	JP NZ,MAIN20
	
	; drive 3: C
	LD A,4
	JP MAIN25
	
MAIN20:	CP '4'
	JP NZ,MAIN21
	
	; drive 4: D
	LD A,8
	JP MAIN25
	
MAIN21:	CP '5'
	JP NZ,MAIN22

	; drive 5: A backside A
	LD A,81H
	JP MAIN25
	
MAIN22:	CP '6'
	JP NZ,MAIN23

	; drive 6: B backside B
	LD A,82H
	JP MAIN25
	
MAIN23:	CP '7'
	JP NZ,MAIN24
	
	; drive 7: C backside C
	LD A,84H
	JP MAIN25
	
MAIN24:	CP '8'
	JP NZ,MAIN25
	
	LD A,88H

MAIN25:	LD (DRIVE),A
	LD A,(USESSO)
	OR A
	JP Z,MAIN26		; -> no SSO

	; SSO
	LD A,(DRIVE)
	AND 80H
	JP Z,MAIN26
	
	LD (SIDESEL),A 	; wenn Flag, dann Rueckseite mit side-bit
			; FUER ECMA-70 wichtig.
MAIN26:	JP MAIN30

MAIN27:	CP '9'
	JP NZ,MAIN28
	
	; '9'
	JP MAINLOOP 	; neue Parameter
	JP MAIN30
	
MAIN28:	CP '0'
	JP NZ,MAIN29

	; '0'
	JP MAIN35 	; -> exit
	JP MAIN30
	
MAIN29:	JP MAIN16 	; -> inner loop, mit gleichen Parametern

	;---------------------------------------------------------------------
	; call formatter, when ready output control values

MAIN30:	CALL PRNPRM

	LD HL,FORMTXT
	CALL PRNMSG
	
	; wait for 'J' / 'j'
	CALL CONIN
	CP 'J'
	JP Z,MAIN31
	CP 'j'
	JP Z,MAIN31
	CP 'n'
	JP Z,MAIN31
	CP 'N'
	JP Z,MAIN31
	CP 3		; ctrl-c
	JP NZ,MAIN30

MAIN31:	CP 'n'
	JP Z,MAIN32
	CP 'N'
	JP NZ,MAIN33

MAIN32:	JP START 	; Neustarten, von vorne

MAIN33:	CP 3		; ctrl-c
	JP NZ,MAIN34

	; ctrl-c
	JP MAIN35 	; Abbruch CTRL-C
	
MAIN34:	CALL FORMAT

	; end of formatting
	JP MAIN16 	; -> inner loop, mit gleichen Parametern
		
MAIN35:	LD HL,FIMSG	; end messaghe (insert system-disk)
	CALL PRNMSG

MAIN36:	; wait for CR
	CALL CONIN
	CP 0DH
	JP NZ,MAIN36
	
	IM 0  		; SAVETY bei FLO1, ggf IM0-Mode verwendet
	CALL 0  	; daher ruecksetzen.
	RET

;-----------------------------------------------------------------------------
; Track settings menu

SETTRK:	LD HL,MENUE3
	CALL PRNMSG
;1 	REPEAT
.L119:
	CALL CONIN
;1 	UNTIL A IN ['1'..'5']
	CP '5'+1
	JP NC,.L119
	CP '1'+0
	JP C,.L119
.L120:
;1 	IF A='1'
	CP '1'
	JP NZ,.L121
	LD A,35
;1 	ELSEIF A='2'
	JP .L122
.L121:
	CP '2'
	JP NZ,.L123
	LD A,40
;1 	ELSEIF A='3'
	JP .L122
.L123:
	CP '3'
	JP NZ,.L124
	LD A,70
;1 	ELSEIF A='4'
	JP .L122
.L124:
	CP '4'
	JP NZ,.L125
	LD A,77
;1 	ELSEIF A='5'
	JP .L122
.L125:
	CP '5'
	JP NZ,.L126
	LD A,80
;1 	ENDIF
.L126:
.L122:
	LD (TRKCNT),A
	RET
	
;-----------------------------------------------------------------------------
; Drive settings menu

SETDRV:	LD HL,MENUE4
	CALL PRNMSG
	
;1 	REPEAT
.L127:
	CALL CONIN
;1 	UNTIL A IN ['1'..'3']
	CP '3'+1
	JP NC,.L127
	CP '1'+0
	JP C,.L127
.L128:
;1 	IF A='1'
	CP '1'
	JP NZ,.L129
	LD A,0  
	LD (SSDS),A	; single-sided
;1 	ELSEIF A='2'
	JP .L130
.L129:
	CP '2'
	JP NZ,.L131
	LD A,1
	LD (SSDS),A	; double-sided
;1 	ELSE
	JP .L132
.L131:
	LD A,1
	LD (SSDS),A	; double-sided
	LD A,1
	LD (USESSO),A 	; Seite 0 beginnt
;1 	ENDIF
.L132:
.L130:
	LD (SSDS),A 	; single-sided=0, double-sided=1
	RET

;-----------------------------------------------------------------------------
; Setup density settings

SETDEN:	LD HL,MENUE2
	CALL PRNMSG
;1 	REPEAT
.L133:
	CALL CONIN
;1 	UNTIL A IN ['1'..'2']
	CP '2'+1
	JP NC,.L133
	CP '1'+0
	JP C,.L133
.L134:
;1 	IF A='1'
	CP '1'
	JP NZ,.L135
	LD A,0 	; EINFAChe Dichte
;1 	ELSE
	JP .L136
.L135:
	LD A,1 	; DOPPELte Dichte
;1 	ENDIF
.L136:
	LD (DENSITY),A
	RET
	
;-----------------------------------------------------------------------------
; Sector settings menu

SETSEC:	LD A,(MINMAX)
;1 	IF A=0  	; Mini
	OR A
	JP NZ,.L137
	LD A,(DENSITY)
;2 	IF A=0 	; SD
	OR A
	JP NZ,.L138
	LD HL,MENUE5A
	CALL PRNMSG
;3 	REPEAT
.L139:
	CALL CONIN
;3 	UNTIL A IN ['1'..'3']
	CP '3'+1
	JP NC,.L139
	CP '1'+0
	JP C,.L139
.L140:
;3 	IF A='1'
	CP '1'
	JP NZ,.L141
	LD HL,128
	LD (BYTCNT),HL
	LD A,16
	LD (SECCNT),A
	LD A,27
	LD (GAPLEN),A
;3 	ELSEIF A='2'
	JP .L142
.L141:
	CP '2'
	JP NZ,.L143
	LD HL,128
	LD (BYTCNT),HL
	LD A,18
	LD (SECCNT),A
	LD A,10
	LD (GAPLEN),A
;3 	ELSEIF A='3'
	JP .L142
.L143:
	CP '3'
	JP NZ,.L144
	LD HL,256
	LD (BYTCNT),HL
	LD A,10
	LD (SECCNT),A
	LD A,16
	LD (GAPLEN),A
;3 	ENDIF
.L144:
.L142:
;2 	ELSE  	; DD
	JP .L145
.L138:
	LD HL,MENUE5B
	CALL PRNMSG
;3 	REPEAT
.L146:
	CALL CONIN
;3 	UNTIL A IN ['1'..'4']
	CP '4'+1
	JP NC,.L146
	CP '1'+0
	JP C,.L146
.L147:
;3 	IF A='1'
	CP '1'
	JP NZ,.L148
	LD HL,256
	LD (BYTCNT),HL
	LD A,16
	LD (SECCNT),A
	LD A,54
	LD (GAPLEN),A
;3 	ELSEIF A='2'
	JP .L149
.L148:
	CP '2'
	JP NZ,.L150
	LD HL,512
	LD (BYTCNT),HL
	LD A,9
	LD (SECCNT),A
	LD A,54
	LD (GAPLEN),A
;3 	ELSEIF A='3'
	JP .L149
.L150:
	CP '3'
	JP NZ,.L151
	LD HL,512
	LD (BYTCNT),HL
	LD A,10
	LD (SECCNT),A
	LD A,40
	LD (GAPLEN),A
;3 	ELSEIF A='4'
	JP .L149
.L151:
	CP '4'
	JP NZ,.L152
	LD HL,1024
	LD (BYTCNT),HL
	LD A,5
	LD (SECCNT),A
	LD A,54
	LD (GAPLEN),A
;3 	ENDIF
.L152:
.L149:
;2 	ENDIF
.L145:
;1 	ELSE  	; MAXI
	JP .L153
.L137:
	LD A,(DENSITY)
;2 	IF A=0 	; SD
	OR A
	JP NZ,.L154
	LD HL,MENUE5C
	CALL PRNMSG
;3 	REPEAT
.L155:
	CALL CONIN
;3 	UNTIL A IN ['1'..'2']
	CP '2'+1
	JP NC,.L155
	CP '1'+0
	JP C,.L155
.L156:
;3 	IF A='1'
	CP '1'
	JP NZ,.L157
	LD HL,128
	LD (BYTCNT),HL
	LD A,26
	LD (SECCNT),A
	LD A,27
	LD (GAPLEN),A
;3 	ELSE
	JP .L158
.L157:
	LD HL,256
	LD (BYTCNT),HL
	LD A,15
	LD (SECCNT),A
	LD A,27
	LD (GAPLEN),A
;3 	ENDIF
.L158:
;2 	ELSE   	; DD
	JP .L159
.L154:
	LD HL,MENUE5D
	CALL PRNMSG
;3 	REPEAT
.L160:
	CALL CONIN
;3 	UNTIL A IN ['1'..'6']
	CP '6'+1
	JP NC,.L160
	CP '1'+0
	JP C,.L160
.L161:
;3 	IF A='1'
	CP '1'
	JP NZ,.L162
	LD HL,256
	LD (BYTCNT),HL
	LD A,26
	LD (SECCNT),A
	LD A,54
	LD (GAPLEN),A
;3 	ELSEIF A='2'
	JP .L163
.L162:
	CP '2'
	JP NZ,.L164
	LD HL,512
	LD (BYTCNT),HL
	LD A,14
	LD (SECCNT),A
	LD A,54
	LD (GAPLEN),A
;3 	ELSEIF A='3'
	JP .L163
.L164:
	CP '3'
	JP NZ,.L165
	LD HL,512
	LD (BYTCNT),HL
	LD A,15
	LD (SECCNT),A
	LD A,54
	LD (GAPLEN),A
;3 	ELSEIF A='4'
	JP .L163
.L165:
	CP '4'
	JP NZ,.L166
	LD HL,512
	LD (BYTCNT),HL
	LD A,16
	LD (SECCNT),A
	LD A,40
	LD (GAPLEN),A
;3 	ELSEIF A='5'
	JP .L163
.L166:
	CP '5'
	JP NZ,.L167
	LD HL,1024
	LD (BYTCNT),HL
	LD A,8
	LD (SECCNT),A
	LD A,54
	LD (GAPLEN),A
;3 	ELSEIF A='6'
	JP .L163
.L167:
	CP '6'
	JP NZ,.L168
	LD HL,1024
	LD (BYTCNT),HL
	LD A,9
	LD (SECCNT),A
	LD A,40
	LD (GAPLEN),A
;3 	ENDIF
.L168:
.L163:
;2 	ENDIF
.L159:
;1 	ENDIF
.L153:
	RET
	
;-----------------------------------------------------------------------------
; Print 0-terminated message, address in HL
	
PRNMSG:	LD A,(HL)

PRNTM1:	OR A
	JP Z,PRNTM2
	
	LD C,A
	CALL CONOUT
	INC HL
	LD A,(HL)
	JP PRNTM1

PRNTM2:	RET

;-----------------------------------------------------------------------------
; Print floppy parameters

PRNPRM:	LD C,1AH	; clear screen
	CALL CONOUT

	LD A,(MINMAX)
;1 	IF A=0  	; 0=Mini
	OR A
	JP NZ,.L171
	LD HL,TMINI
;1 	ELSE
	JP .L172
.L171:
	LD HL,TMAXI
;1 	ENDIF
.L172:
	CALL PRNMSG
	LD A,(USER)
;1 	IF A=0  	; FLO 2
	OR A
	JP NZ,.L173
	
	; V1.22
	LD A,(FLOTYP)
	OR A
	JP NZ,L0BD4
	LD HL,TFLO2
	JP L0BD7
	
L0BD4:	
	LD HL,TFLO1C
L0BD7:
;1 	ELSEIF A=1
	JP .L174
.L173:
	CP 1
	JP NZ,.L175
	LD HL,TFLO1A
;1 	ELSE A=2
	JP .L176
.L175:
	LD HL,TFLO1B
;1 	ENDIF
.L176:
.L174:
	CALL PRNMSG
	LD A,(DENSITY)
;1 	IF A=0  	; 0=SD
	OR A
	JP NZ,.L177
	LD HL,TFM
;1 	ELSE
	JP .L178
.L177:
	LD HL,TMFM
;1 	ENDIF
.L178:
	LD A,(ECMA)
;1 	IF A=1
	CP 1
	JP NZ,.L179
	LD HL,TECMA 	; Sonderfall, Ecma-Format
;1 	ENDIF
.L179:
	CALL PRNMSG
	CALL CRLF
	CALL CRLF
	LD HL,TSPUREN
	CALL PRNMSG
	LD A,(TRKCNT)
	LD L,A
	LD H,0
	CALL PRNTHL 	; Anzahl Spuren
	CALL CRLF
	LD HL,TSEKTOREN
	CALL PRNMSG
	LD A,(SECCNT)
	LD L,A
	LD H,0
	CALL PRNTHL 	; Anzahl SECCNT
	CALL CRLF
	LD HL,TBYTES
	CALL PRNMSG
	LD HL,(BYTCNT)
	CALL PRNTHL 	; Bytes pro Sektor
	CALL CRLF
		;
	LD HL,TLAUFWERK
	CALL PRNMSG
	LD A,(DRIVE)
	AND 0FH 	; 1,2,4,8
;1 	IF A=1
	CP 1
	JP NZ,.L180
	LD C,'A'
;1 	ELSEIF A=2
	JP .L181
.L180:
	CP 2
	JP NZ,.L182
	LD C,'B'
;1 	ELSEIF A=4
	JP .L181
.L182:
	CP 4
	JP NZ,.L183
	LD C,'C'
;1 	ELSEIF A=8
	JP .L181
.L183:
	CP 8
	JP NZ,.L184
	LD C,'D'
;1 	ELSE
	JP .L185
.L184:
	LD C,'?'
;1 	ENDIF
.L185:
.L181:
	CALL CONOUT
	CALL CRLF
	CALL CRLF
		; 
	LD A,(SSDS)
;1 	IF A=1  	; zweiseitig
	CP 1  
	JP NZ,.L186	; -> single-sided
	
	; double-sided
	LD A,(USESSO)
;2 	IF A=0 	; OHNE SSO
	OR A
	JP NZ,.L187	; -> SSO
	
	; no SSO
	LD HL,TZWEISEITIg
;2 	ELSE  	; MIT SSO
	JP .L188
.L187:
	LD HL,TZWEISSO
;2 	ENDIF
.L188:
	CALL PRNMSG
;1 	ELSE  	; EINSEItig
	JP .L189
.L186:
	LD A,(DRIVE) 
	AND 80H
;2 	IF Z  	; VORDERseite
	JP NZ,.L190
	LD HL,TEINSEITIG
	CALL PRNMSG
;2 	ELSE  	; RUECKSeite
	JP .L191
.L190:
	LD A,(USESSO)
;3 	IF A=0 	; OHNE Sso
	OR A
	JP NZ,.L192	; -> SSO
	
	; no SSO
	LD HL,TRUECKSEITe
;3 	ELSE  	; SSO
	JP .L193
.L192:
	LD HL,TRUECKSSO
;3 	ENDIF
.L193:
	CALL PRNMSG
;2 	ENDIF
.L191:
;1 	ENDIF
.L189:
	CALL CRLF 
	CALL CRLF
		; KAPAZItaet ausrechnen
	LD HL,TKAP
	CALL PRNMSG
	LD A,(SECCNT)
	LD L,A
	LD H,0
	LD A,(TRKCNT)
	LD E,A
	LD D,0
	CALL MULHLDE 	; sektoren*tracks
	LD A,(SSDS)
;1 	IF A=1
	CP 1
	JP NZ,.L194	; -> single-sided
	
	; double-sided
	LD DE,2
	CALL MULHLDE 	; wenn zweiseitig, dann doppelt
;1 	ENDIF
.L194:
	LD DE,(BYTCNT) 	; de=1024,512,256,128
		; DE=400h,200h,100h,80h
;1 	IF D=0
	LD A,D
	OR A
	JP NZ,.L195
;2 	DO B,3 	; DIV 8
	LD B,3 
.L196:
	SRA H
	RR L
;2 	ENDDO
	DEC B
	JP NZ,.L196
;1 	ELSEIF D=1
	JP .L197
.L195:
	LD A,D
	CP 1
	JP NZ,.L198
	SRA H  	; DIV 4
	RR L
	SRA H
	RR L
;1 	ELSEIF D=2
	JP .L197
.L198:
	LD A,D
	CP 2
	JP NZ,.L199
	SRA H  	; DIV 2
	RR L
;1 	ELSEIF D=4
	JP .L197
.L199:
	LD A,D
	CP 4
	JP NZ,.L200
	NOP  	; HL = KBytes
;1 	ENDIF
.L200:
.L197:
	CALL PRNTHL 	; ausgeben
	LD HL,TKAP1
	CALL PRNMSG
	CALL CRLF
	RET
	
;-----------------------------------------------------------------------------
; HL = HL * DE
; for capacity calculation

MULHLDE:
	LD A,16
	PUSH DE
	POP BC
	LD DE,0
	EX DE,HL

MULHL1:	PUSH AF
	BIT 0,E
	JP Z,MULHL2
	
	ADD HL,BC

MULHL2:	SRA H
	RR L
	RR D
	RR E
	POP AF
	DEC A
	JR NZ,MULHL1
	
	EX DE,HL 	; LSB to HL
	RET
	
;-----------------------------------------------------------------------------
; Print CR/LF

CRLF:	LD HL,TCRLF
	CALL PRNMSG
	RET

;-----------------------------------------------------------------------------

TKAP:	DEFB 'Speicherkapazitaet :  ',0

TKAP1:	DEFB ' KBytes',0

TMINI:	DEFB 'Mini-Laufwerk  ',0

TMAXI:	DEFB 'Maxi-Laufwerk  ',0

TFLO2:	DEFB 'FLO2 (C0h)  ',0

TFLO1A:	DEFB 'FLO1 (40h)  ',0

TFLO1B:	DEFB 'FLO1 (30h)  ',0

TFLO1C:	DEFB 'FLO1 (C0h)  ',0

TFM:	DEFB 'FM  ',0

TMFM:	DEFB 'MFM  ',0

TECMA:	DEFB 'ECMA70 ',0

TSPUREN:
	DEFB 'Anzahl Spuren    = ',0

TSEKTOREN:
	DEFB 'Anzahl Sektoren  = ',0

TBYTES:	DEFB 'Bytes/pro Sektor = ',0

TLAUFWERK:
	DEFB 'Laufwerk ',0

TEINSEITIG:
	DEFB 'Vorderseite wird formatiert',0

TRUECKSEITE:
	DEFB 'Rueckseite wird formatiert',0

TRUECKSSO:
	DEFB 'Rueckseite wird mit SSO formatiert',0

TZWEISEITIG:
	DEFB 'beide Seiten werden formatiert',0

TZWEISSO:
	DEFB 'beide Seiten werden formatiert',0dh,0ah
	DEFB 'Seite 1 mit SSO, Seite 0 normal',0

FORMTXT:
	DEFB 0dh,0ah
	DEFB 'ACHTUNG Diskette wird formatiert',0dh,0ah
	DEFB 'Start = "J"',0dh,0ah
	DEFB 0

HEADTXT:
	DEFB 1ah,0dh,0ah
	DEFB ' Universal Formatierer  V 1.22 , Rolf-Dieter Klein / JS ',0dh,0ah
	DEFB ' (C) 1984, Muenchen ',0dh,0ah
	DEFB 0dh,0ah
	DEFB ' --   Bitte Systemdiskette herausnehmen    -- ',0dh,0ah
	DEFB ' -- und zu formatierende Diskette einlegen -- ',0dh,0ah
	DEFB 0dh,0ah
	DEFB 'Minilaufwerke (5 1/4") = 1',0dh,0ah
	DEFB 'Maxilaufwerke (8"    ) = 2',0dh,0ah
	DEFB 'Std  8" SD SD 77 Spur  = 3',0dh,0ah
	DEFB 'ECMA 70 DD SD 40 Spur  = 4',0dh,0ah
	DEFB 'NDR- DD DS 80 Spur     = 5',0dh,0ah
	DEFB 'ENDE                   = 6',0dh,0ah
	DEFB 0dh,0ah,0

MENUE2:	DEFB 1ah,0dh,0ah
	DEFB 'einfache Schreibdichte = 1',0dh,0ah
	DEFB 'doppelte Schreibdichte = 2',0dh,0ah
	DEFB 0dh,0ah,0

MENUE3:	DEFB 1ah,0dh,0ah
	DEFB '35 Spuren  = 1',0dh,0ah
	DEFB '40 Spuren  = 2',0dh,0ah
	DEFB '70 Spuren  = 3',0dh,0ah
	DEFB '77 Spuren  = 4',0dh,0ah
	DEFB '80 Spuren  = 5',0dh,0ah
	DEFB 0dh,0ah,0

MENUE4:	DEFB 1ah,0dh,0ah
	DEFB 'Einseitiges Laufwerk     = 1',0dh,0ah
	DEFB 'Doppeltseitiges Laufwerk = 2',0dh,0ah
	DEFB 'Doppeltseitig und SSO    = 3',0dh,0ah
	DEFB 0dh,0ah,0

MENUE5A:
; einfache Dichte, Minifloppy
	DEFB 1ah,0dh,0ah
	DEFB '128 Bytes pro Sektor  (16 pro Track) = 1',0dh,0ah
	DEFB '128 Bytes pro Sektor  (18 pro Track) = 2',0dh,0ah
	DEFB '256 Bytes pro Sektor  (10 pro Track) = 3',0dh,0ah
	DEFB 0dh,0ah,0

MENUE5B:
	; doppelte Dichte, Minifloppy
	DEFB 1ah,0dh,0ah
	DEFB '256 Bytes pro Sektor  (16 pro Track) = 1',0dh,0ah
	DEFB '512 Bytes pro Sektor  (9 pro Track)  = 2',0dh,0ah
	DEFB '512 Bytes pro Sektor  (10 pro Track) = 3',0dh,0ah
	DEFB '1024 Bytes pro Sektor (5 pro Track)  = 4',0dh,0ah
	DEFB 0dh,0ah,0

MENUE5C:
	; einfache Dichte Maxifloppy
	DEFB 1ah,0dh,0ah
	DEFB '128 Bytes pro Sektor (26 pro Track) = 1',0dh,0ah
	DEFB '256 Bytes pro Sektor (15 pro Track) = 2',0dh,0ah
	DEFB 0dh,0ah,0

MENUE5D:
	; doppelte Dichte Maxifloppy
	DEFB 1ah,0dh,0ah
	DEFB '256 Bytes pro Sektor (26 pro Track) = 1',0dh,0ah
	DEFB '512 Bytes pro Sektor (14 pro Track) = 2',0dh,0ah
	DEFB '512 Bytes pro Sektor (15 pro Track) = 3',0dh,0ah
	DEFB '512 Bytes pro Sektor (16 pro Track) = 4',0dh,0ah
	DEFB '1024 Bytes pro Sektor (8 pro Track) = 5',0dh,0ah
	DEFB '1024 Bytes pro Sektor (9 pro Track) = 6',0dh,0ah
	DEFB 0dh,0ah,0

MENUE6:	DEFB 1ah,0dh,0ah
	DEFB 'Laufwerk              A = 1',0dh,0ah
	DEFB 'Laufwerk              B = 2',0dh,0ah
	DEFB 'Laufwerk              C = 3',0dh,0ah
	DEFB 'Laufwerk              D = 4',0dh,0ah
	DEFB 'Laufwerk A Rueckseite A = 5',0dh,0ah
	DEFB 'Laufwerk B Rueckseite B = 6',0dh,0ah
	DEFB 'Laufwerk C Rueckseite C = 7',0dh,0ah
	DEFB 'Laufwerk D Rueckseite D = 8',0dh,0ah
	DEFB 'NEUSTART    = 9',0dh,0ah
	DEFB 'ENDE        = 0',0dh,0ah
	DEFB 0dh,0ah,0

MENUE7:	DEFB 1ah,0dh,0ah
	DEFB 'FLO2-Maxi/Mini (0C0h) = 1',0dh,0ah
	DEFB 'FLO1-Maxi (40h)       = 2',0dh,0ah
	DEFB 'FLO1-Mini (30h)       = 3',0dh,0ah
	DEFB 'FLO1-Maxi/Mini (0C0h) = 4',0dh,0ah
	DEFB 0dh,0ah,0

FMSG:	DEFB 1ah,0dh,0ah
	DEFB 'Diskette wird formatiert ... bitte warten ',0dh,0ah
	DEFB 0dh,0ah,0

F6MSG:	DEFB 0dh,0ah
	DEFB 'Schreibschutz gesetzt',0dh,0ah
	DEFB 'Neustart = Taste W druecken',0dh,0ah,0

F5MSG:	DEFB 0dh,0ah
	DEFB 'Record Typ ist falsch',0dh,0ah
	DEFB 'Neustart = Taste W druecken',0dh,0ah,0

F4MSG:	DEFB 0dh,0ah
	DEFB 'Record nicht gefunden',0dh,0ah
	DEFB 'Neustart = Taste W druecken',0dh,0ah,0

F3MSG:	DEFB 0dh,0ah
	DEFB 'CRC Fehler aufgetreten',0dh,0ah
	DEFB 'Neustart = Taste W druecken',0dh,0ah,0

F2MSG:	DEFB 0dh,0ah
	DEFB 'CPU zu langsam fuer gewaehltes Format-- Datenverlust',0dh,0ah
	DEFB 'hoeherer Takt erforderlich',0dh,0ah
	DEFB 'Neustart = Taste W druecken',0dh,0ah,0

F0MSG:	DEFB 0dh,0ah
	DEFB 'Fehler aufgetreten. Neustart = Taste W druecken',0dh,0ah,0

TKMSG:	DEFB 0dh,0ah
	DEFB 'Track = ',0

SKMSG:	DEFB ', Sektor = ',0

TCRLF:	DEFB 0dh,0ah,0

RMSG:	DEFB 0dh,0ah
	DEFB 'Laufwerk nicht READY ... bitte pruefen:',0dh,0ah
	DEFB ' 1. Diskette falschherum eingelegt',0dh,0ah
	DEFB ' 2. Laufwerkstuere nicht geschlossen',0dh,0ah
	DEFB ' 3. falsche Laufwerksnummer angegeben',0dh,0ah
	DEFB ' 4. Laufwerksmotor dreht sich nicht',0dh,0ah
	DEFB ' 5. READY-Leitung nicht ok',0dh,0ah 
	DEFB 0dh,0ah
	DEFB 'Neustart = Taste W druecken',0dh,0ah,0

VMSG:	DEFB 0dh,0ah
	DEFB 'Diskette wird geprueft ... bitte warten',0dh,0ah
	DEFB 0dh,0ah,0

FIMSG:	DEFB 1ah,0dh,0ah
	DEFB 'Systemdiskette in Laufwerk A einlegen,',0dh,0ah
	DEFB 'dann CR (carriage return) druecken.',0dh,0ah,0

	DEFB 0	; v1.22
	
USER:	DEFB 0  	; NDR=1, MC+Term1=2, sonst=3
FLOTYP:	DEFB 0    	; 0=FLO2, 1=FLO1 Maxi, 2=FLO1 Mini
MINMAX:	DEFB 0  	; 0=Mini 1=Maxi
ECMA:	DEFB 0  	; 1=ECMA70 format (SD,128 on track 0)
BYTCNT:	DEFW 0  	; Anzahl der Bytes pro Sektor
FILLER:	DEFB 0E5h 	; fill byte std=E5
DENSITY:DEFB 0  	; 0=single-density, 1=double-density
GAPLEN:	DEFB 0  	; Gap 3 Laenge zwischen Sektoren
TRKCNT:	DEFB 0  	; Anzahl der Spuren
SSDS:	DEFB 0  	; 0=single-sided, 1=double-sided
SECCNT:	DEFB 0  	; Anzahl der Sektoren pro Spur
DRIVE:	DEFB 0  	; drive code (1,2,4,8)
			; 81,82,84,88 = Rueckseite
SIDESEL:DEFB 0  	; SSO: 0=Seite 0, 80h=Seite 1
USESSO:	DEFB 0  	; 0=no SSO, 1=use SSO
		
CURTRK:	DEFB 0  	; aktuelle Spur
CURSEC:	DEFB 0  	; aktueller Sektor

FORMTAB:; Formatierbereich, hier wird ein Track gelegt.

	end start
