;Putsys by Donn Stewart, June 2019
;geändert 4/2026 Ulrich Haumann
;Copies the memory image of CP/M loaded at cpm_start onto track 0 of the first CP/M disk
;Image size is 6400 bytes, so need to save 6400/128 = 50 sectors
;For system with 64-sector tracks, image can all be on track 0
;Load and run from ROM monitor
;Uses calls to cbios, in memory at EA00h
;benuzt calls zum Monitor im oberen RAM F000h
;
;Writes track 0, sectors 1 to 50 (sector 0 has cpm loader)
;
cpm_start		equ	0D400h
;
;nachfolgend die BIOS Einspruenge:
;
seldsk		equ	0EA1Bh		;pass disk no. in c
setdma		equ	0EA24h		;pass address in bc
settrk		equ	0EA1Eh		;pass track in reg C
setsec		equ	0EA21h		;pass sector in reg c
write			equ	0EA2Ah		;write one CP/M sector to disk
;
;Monitor Einspruenge:
;
mon_warm_start	equ	0F033h		;Monitor Einsprung
;
;
		org	08000h			;Programm wird auf 8000H abgelegt
;
		ld	c,00h				;CP/M disk a
		call	seldsk
;Write track 0, sectors 1 to 50
		ld	a,1				;starting sector
		ld	(sector),a
		ld	hl,cpm_start		;memory address to start
		ld	(address),hl
		ld	c,0				;CP/M track
		call	settrk
wr_trk_0_loop:	
		ld	a,(sector)
		ld	c,a				;CP/M sector
		call	setsec
		ld	bc,(address)		;memory location
		call	setdma
		call	write
		ld	a,(sector)
		cp	50
		jp	z,done
		inc	a
		ld	(sector),a
		ld	hl,(address)
		ld	de,128
		add	hl,de
		ld	(address),hl
		jp	wr_trk_0_loop
done:		jp	mon_warm_start		;zurueck zum Monitor
;
sector:	db	00h
address:	dw	0000h
		end


