	.Z80
;---------------------------------------------------------------
;Monitor fuer MC-Computer Platine SYS-80 und SYS-80s
;Assembliert mit Z80ASM von SLR Systems wegen der langen
;Label die mit einigen anderen Assemblern nicht moeglich sind.
;
;Erstellt 05/2026 von U. Haumann
;Enthaelt weitgehend Routinen aus RDK Monitor 1.1 850129
;V7.2 851216, sowie Teile aus dem Monitor von Donn Stewart 
;fuer den "CPU-Ville" Z80 Computer.
;Treiber fuer Serielle Schnittstelle auf CPU-Platine mit UART 8251
;implementiert.
;Flo1 und Flo2 waehlber auf Hardware Basis Adresse 0C0h.
;Der Mointor erwartet 64KB Ram Memory. Er darf selbst nicht
;groesser als 4KB werden, es sein denn man schiebt die MON_ADR
;und CCP weiter nach unten. Der CPM Bereich verkleinert sich dann.
;Der Monitor kopiert sich nach Reset an das Speicherende
;auf den Wert in MON_ADR und gibt den unteren RAM Bereich frei.
;Dies wird auf der SYS CPU Platine mit einem Lesebefehl auf
;Adresse 7000h erreicht. Das Eprom ist dann ausgeblendet.
;Somit steht der Speicher durchgaengig ab 0000h bis zu MON_ADR
;zur Verfuehgung.
;Das CPM BIOS fuer den MC-Computer ueberschreibt den Monitorbereich
;ab FC00h. Alle relevanten Teile für den Betrieb des Rechners 
;muessen vor FC00h plaziert werden.

;------------------------------------------------------------------------------

	ORG 0000h		; Im ROM auf Adresse 0

	; Kopieren des ROMs von ROMSTRT nach F000

BEGIN:	LD SP,0FFFFH 		; Stack auf Speicherende
	LD A,0C9H 		; RET-Befehl auf F000h speichern
	LD (0F000H),A 		; 
	CALL 0F000H 		; eigene Speicheradresse ermitteln

ANF:	DEC SP  		; Um kopieren von beliebiger Adresse zu
	DEC SP  		; ermoeglichen (fuer Tests)
	POP DE
	LD HL,ROMSTRT-ANF
	ADD HL,DE		; Quelladresse in HL
	LD DE,0F000H 		; Zieladresse in DE
	LD BC,0FFFH 		; Laenge in BC (4KB - 1)
	LDIR  			; 
	JP 0F000H 		; Monitor im ROM aufrufen

;------------------------------------------------------------------------------
; START DES EIGENTLICHEN MONITORS

ROMSTRT:	; Start address of Monitor in ROM, before .PHASE!!!

	.PHASE 0F000H

CR 	EQU 0DH
LF 	EQU 0AH
BELL	EQU 7
RUB 	EQU 0FFH
FIL 	EQU 0
MAX	EQU 7
ESC	EQU 1BH

RST7	EQU 38H		; der Vektor RST7 wird fuer Breakpoints gebraucht

	; Adressen des seriell Port MC Computer OUT SIO/PIO Karte

SA_DAT	EQU 0F0H	; SIO A Daten
SA_STS	EQU 0F1H	; SIO A Control
SB_DAT	EQU 0F2H	; SIO B Daten
SB_STS	EQU 0F3H	; SIO B Control
S_RXB	EQU 01h		; SIO RX Ready Bit
S_TXB	EQU 04h		; SIO TX Ready Bit
	
	; Adressen des Seriell Port UART 8251 auf SYS-80s CPU Karte
	; bei SYS-1 oder SYS-80 sind die entsprechenden Daten der
	; SIO A einzutragen, siehe Auskommentierung
	IF 0
U_DAT	EQU SA_DAT	; SIO A Daten
U_STS	EQU SA_STS	; SIO A Control
U_RXB	EQU S_RXB	; RX Ready Bit SIO A
U_TXB	EQU S_TXB	; TX Ready Bit SIO A
	ENDIF

	; Serial Port A is redirected to UART on SYS-80s

U_DAT	EQU 020H	; UART 8251 Daten
U_STS	EQU 021H	; UART 8251 Control
U_RXB	EQU 002h	; RX Ready Bit UART 8251
U_TXB	EQU 001h	; TX Ready Bit UART 8251

	; Address of IDE Port CF-80 card

IDEDATA	EQU 018h	; IDE Daten Register
SECCND	EQU 01ah	; Sector Count Register
LBA7	EQU 01bh	; LBA Bits 0-7
LBA15	EQU 01ch	; LBA Bits 8-15
LBA23	EQU 01dh	; LBA Bits 16-23
IDEHEAD	EQU 01eh	; IDE Drive Head Register
IDESTAT	EQU 01fh	; IDE Command/Status Register

;------------------------------------------------------------------------------
; Start of Monitor program, ROM address 0F000h

	JP INIT
	JP CI		; Console in
	JP RI		; Reader In
	JP CO		; Console Out
	JP POO		; Punch Out
	JP LO		; List Out
	JP CSTS		; main status routine, 0FFH IN A, FALLS ZEICHEN DA
	JP IOGET	; get iobyte, IN A AKTUELLE IO-KONFIGURATION
	JP IOSET	; set iobyte, VERAENDERN, IO IN C-REG
	JP MEMCK	; IN B HIGH IN A LOW MEMORY

TRAP:	; trap/breakpoint entry

	JP RSTRT
	JP FLOP	 	; neue Floppy-Schnittstelle rev 1.0
	JP MAXI		; FLOPPY EXEC VEKTOR SOFT (alt)
	JP MINI		; FLOPPY EXEC VEKTOR MINI (alt)
	JP IDERD	; IDE Sektor lesen
	JP IDEWR	; IDE Sektor schreiben
	JP COLD		; Monitor Cold Start (no Hardware init)
	JP WARM		; Monitor Warm Start
	JP WRSTR	; gibt mit 0 terminierten String aus

	DEFW TABSTART 	; TABELLEN-START, USER-BEREICH SPRUNGTABELLE,
			; IMMER INDIREKT VERWENDEN
	DEFW LASTMON 	; ADRESSE LETZTE BELEGTE ZELLE
			; DES MONITORS DANACH PATCH FREI
	DEFW FREEMEM 	; Lade-Adresse hinter IO-Gebiet

	; Sprungtabelle, um mit FLOMON kompatibel zu sein (NDR-Computer)
	
	DEFS 13 	; f033,34,35,36,37,38,39,3a,3b,3c,3d,3e,3f
			; BASIS F040h
	JP ILLEGAL 	; loeschen alle seiten
	JP ILLEGAL     	; loeschen unsichtbar
	JP ILLEGAL 	; moveto hl=x de=y
	JP ILLEGAL 	; drawto hl=x de=y
	JP ILLEGAL 	; c=schreibseite 0,1,2,3
	JP ILLEGAL 	; c=leseseite    0,1,2,3
	JP ILLEGAL      ; c=rmwmode      0=norm 1=rmw
	JP ILLEGAL 	; warten bis gdp fertig
	JP ILLEGAL      ; c=befehl fuer gdp  ACHTUNG in C-Register nicht A
	JP ILLEGAL 	; hl=quelle,de=ziel,c=bank quelle, b=bank ziel
			; carry wenn bankram auf f000h nicht da ist

	; --- Ende Sprungtabelle ---

;------------------------------------------------------------------------------

ILLEGAL:
	LD A,0FFh
	SCF
	RET  		; return with error

;------------------------------------------------------------------------------

RSTRT:	JP RSTRTB 	; kann kurzgeschlossen werden
			; nach freemem ueberschreibung
INIT:	JP INIT1 	; kurzschliessen ggf.
			; ende fixed gebiet

;==============================================================================
; IO Routinen
;==============================================================================
; output 0-terminated string, address in HL

WRSTR:	IN  A,(U_STS)	; read status
	AND U_TXB	; check TxRDY bit
	JP Z,WRSTR	; loop if not set
	LD A,(HL)	; get char from string
	AND A		; check if 0
	RET Z		; alles ausgegeben, dann zurueck
	OUT (U_DAT),A	; no, write char to output
	INC HL		; next char in string
	JP WRSTR	; start over

;------------------------------------------------------------------------------
; Console In main routine

CI:	LD A,(IOBYT)
	AND 3 			; console mask
	JR NZ,CI2		; other device

CI1:	IN A,(U_STS)
	AND U_RXB
	JR Z,CI1
	IN A,(U_DAT)
	RET

CI2:	JP USERCI  		; user CI

;------------------------------------------------------------------------------
; Reader In routine

RI:	LD A,(IOBYT)
	AND 00001100B
	JP Z,CI  	; AR=T
	CP 00000100B 
	JP NZ,USERRI
	
RI1:	;AR = P
	IN A,(SB_STS)
	AND S_RXB
	JR Z,RI1
	IN A,(SB_DAT)
	RET

;------------------------------------------------------------------------------
; Console Out main routine

CO:	LD A,(IOBYT)
	AND 3
	JR NZ,CO2

CO1:	IN A,(U_STS)
	AND U_TXB
	JR Z,CO1
	
	LD A,C
	OUT (U_DAT),A
	RET

CO2:	JP USERCO	; user CO

;------------------------------------------------------------------------------
; Punch Out main routine
; HIER ABFRAGE IOBYT MOEGLICH
;
POO:	LD A,(IOBYT)
	AND 00110000B
	JP Z,CO  			; AP=T
	
	CP 00010000B
	JP NZ,USERPOO
	
POO1:	; AP=P
	IN A,(SB_STS)
	AND S_TXB
	JR Z,POO1
	
	LD A,C
	OUT (SB_DAT),A
	RET

;------------------------------------------------------------------------------
; List Out main routine

LO:	LD A,(IOBYT)
	AND 0C0H
	JP Z,CO1 		; AL=T
	
	CP 10000000B 		
	JP NZ,USERLO
					
LO1:	; AL=L
	IN A,(SB_STS)
	AND S_TXB
	JR Z,LO1
	
	LD A,C
	OUT (SB_DAT),A
	RET

;------------------------------------------------------------------------------
; Console Status main routine

CSTS:	LD A,(IOBYT)
	AND 3
	JR NZ,CSTS2
	
CSTS1:	IN A,(U_STS)
	AND U_RXB
	RET Z
	
	LD A,0FFH
	OR A
	RET

CSTS2:	JP USERCSTS	; user csts

;------------------------------------------------------------------------------
; The IOBYTE is used to switch from physical to logical device. It has the
; same meaning as in the CP/M BIOS.

IOGET:	LD A,(IOBYT)
	RET

;------------------------------------------------------------------------------
; IOSET, can be set in BIOS

IOSET:	LD A,C
	LD (IOBYT),A
	RET
	
;------------------------------------------------------------------------------
; prueft den Speicherbereich und gibt die hoechste verfuegbare Zelle an
; MEMCK IN B HIGH IN A LOW MEMORY

MEMCK:	PUSH HL
	CALL MEMSIZ
	LD A,L
	SUB 3CH
	JR NC,MEMCK1
	
	DEC H
	
MEMCK1:	LD B,H
	POP HL
	RET

;------------------------------------------------------------------------------
; Detect end of memory from 0000h to EFFFh

MEMSIZ:	PUSH BC

	; Einsprung
MEMSIZ1:
	LD HL,-1

MEMS1:	INC H
	LD A,(HL)
	CPL
	LD (HL),A
	CP (HL)
	CPL
	LD (HL),A
	JR NZ,MEMS1

MEMS2:	INC H
	LD A,H
	CP 0F0H		; ALL RAM
	JR Z,MEMS3 	; READY 0F000H
	
	LD A,(HL) 	; max 0F000h, da dort Monitor startet
	CPL
	LD (HL),A
	CP (HL)
	CPL
	LD (HL),A
	JR Z,MEMS2

MEMS3:	DEC H
	LD BC,EXIT-ENDX
	ADD HL,BC
	POP BC
	RET

; -----------------------------------------------------------------------------

TABSTART:
	;TABELLE SPRUNG-VEKTOREN

; Hier können eigene Routinen stehen für Input/Output

USERCI:	JP CI1
USERRI:	JP CI1
USERCO:	JP CO1
USERPOO:
	JP CO1
USERLO:	JP CO1
USERCSTS:
	JP CSTS1

IOBYT:	DEFB 0		; IOBYTE-SPEICHER 
OEXEC:	DEFS 3
IEXEC:	DEFS 3
KEXEC:	DEFS 3

;==============================================================================
; FLO2 floppy routines

; Autobestimmung des Formats
; in C ist danach der gueltige ; Laufwerkscode,
; Vorgabe ist in C die Laufwerksnummer und ggf. Seite.
; testet mini,sd =11
;        mini,dd =10
;        maxi,sd =01
;        maxi,dd =00

getfl:	DI  		; ohne Interrupts
	LD A,0D0H
	OUT (FLO0),A 	; Stop Controller
	IN A,(FLO0) 	; Ints loeschen
	LD A,C
	AND 8FH 	; nur Drivecode ok
	LD C,A
	CALL WAWA
	LD A,C
	OR 00110000B	; mini sd vorgeben		
	LD C,A
	CALL GET1FL
	RET NC  	; kein Fehler, no carry
	LD A,C
	AND 10101111B
	LD C,A
	CALL GET1FL
	RET NC
	LD A,C
	AND 10001111B
	OR  00010000B
	LD C,A
	CALL GET1FL
	RET NC
	LD A,C
	AND 10001111B
	LD C,A
	CALL GET1FL
	RET  		; carry, dann Fehler

; get1fl

get1fl:	LD A,(FLOC0)
	CP 1  		; if a=1 -> FLO1 
	JP NZ,GET1FL1
	
	LD A,C
	XOR 10H		;wenn Flo1 dann invertieren Dichtebit
	JP GET1FL2
	
get1fl1:
	; ELSE FLO2
	LD A,C
	
get1fl2:
	OUT (FLO4),A 	; Drive-Code probieren
	LD A,0FH 	; RSTORE-Befehl mit Verify verwenden
	OUT (FLO0),A 	; und ausgeben
get1fl3:
	IN A,(FLO4)
	AND 40H 	; Bit 6 pruefen
	JR Z,GET1FL3 	; bis INT da
	IN A,(FLO0) 	; und dann status lesen, int loeschen
	AND  10011000B 	; krit. Bit testen 
	SCF  		; falls Fehler, dann setzen
	RET NZ  	; carry=Fehler
	XOR A
	RET  		; sonst ok nocarry (c=Code)

;==============================================================================
; Floppy Interface Paket Rev 1.0   841031
; (C) 1984 Muenchen, Rolf-Dieter Klein

; Routinen fuer MC-Kompatibilitaet
; wie floppy, jedoch Drive-Codierung anders
; nur fuer bestehende BIOS-Routinen gedacht
 
; bei Maxi wird die Seite 1 mit Seitenpruefung auf 0
; angesprochen, bei Mini mit Seitenpruefung auf 1.
; nur fuer SD

; c=0,1,2,3
; 	0,2 gekoppelt  1,3 gekoppelt					

maxi:	CALL SETCOD
	JP FLOP		; sso-flag auf 0 setzen, jedoch stepflag
			; gueltig wenn bit 7 gesetzt.

;------------------------------------------------------------------------------

setcod:	LD A,C  	; SD MAXI
	AND 3  		; muss Bereich 0..3 sein
	CP 0  		; 0 seite 0
	JR NZ,MAX1
	
	LD C,00010001B 	; LW 1
	RET

max1:	CP 1
	JR NZ,MAX2
	
	LD C,00010010B 	; LW 2 seite 0
	RET

max2:	CP 2
	JR NZ,MAX3
	
	LD C,10010001B 	; LW 1 seite 1
	RET
max3:
	LD C,10010010B 	; LW 2 seite 1
	RET

;------------------------------------------------------------------------------

set2cod:
	AND 3  		; 0,1,2,3 erlaubt
	CP 0
	JR NZ,SET2C1
	
	LD C,00000001B 	; LW 1 seite 0
	RET

set2c1:	CP 1
	JR NZ,SET2C2
	
	LD C,10000001B 	; LW 1 seite 1
	RET

set2c2:	CP 2
	JR NZ,SET2C3
	
	LD C,00000010B 	; LW 2 seite 0
	RET

set2c3:	LD C,10000010B 	; LW 2 seite 1 
	RET

;------------------------------------------------------------------------------
; rest unzul.
; 10,11 12,13 gekoppelt, d0,d1,d2,d3
; bit 6 =Dichtecode 1=Double dense

mini:	LD A,C
	AND 7FH 	; bit 7 interessiert nicht
	LD C,A
	PUSH AF
	CALL SET2COD 	; codierung 2
	POP AF
	AND 40H 	; dd,sd 
	JP NZ,MINI3
	
	; IF Z=0 SD
	LD A,C
	OR 00110000B 	; SD MINI
	LD C,A
	; ELSE
	JP MINI4

mini3:	; DD
	LD A,C
	OR 00100000B 	; DD MINI
	LD C,A

mini4:	LD A,2  	; sso-flag setzen
	JP FLOP1 	; ok ausfuehren

;==============================================================================
; Floppy-Unterprogramme fuer FLO2
; verwendet 1797 als Controller
; Version 1.0   840506
; Rolf-Dieter Klein (C) 1984 Muenchen
;
; Die Routinen ermoeglichen sowohl den Anschluss von Mini-,Mikro- als auch
; von Maxi-Laufwerken. Die Routinen muessen im RAM stehen, da die Buffer
; am Ende stehen. Alle Buffer sind jedoch gesammelt.

; FLO4    als Leseport
;
; 7 6 5 4 3 2 1 0
;
; DRQ   INTRQ   headld x      x x x x
; 0=request
;      0=request
;  1=head down
;

; FLO4    als Schreibport
;
; 7 6 5 4 3 2 1 0
;
; sso moton mini dense d c b a
;
; 1=Seite 1
; 0=Motor an
;  1=Minilaufwerk
;   1=Single Dense
;    -------------------------
;      1=Laufwerk an



FLO	EQU 0C0H 	; Basisadresse Floppy-Controller
FLO0	EQU 0C0H   	
FLO1	EQU 0C1H
FLO2	EQU 0C2H
FLO3	EQU 0C3H
FLO4	EQU 0C4H 	; Port fuer Zusatzstatus etc.

	; Bei einem Interrupt wird an diese Stelle gesprungen
	; Der Interrupt erfolgt vom Floppy-Controller

intex:	; Das INT-Program arbeitet nicht als Unterprogramm
	POP AF  	; alte Ret-Adresse vernichten
	IN A,(FLO) 	; Status lesen und INT loeschen
	EI  		; Interrupt wieder freigeben
	RETI  		; zurueck zum vorherigen Aufrufer

;------------------------------------------------------------------------------

iniflp:			; Floppy Routinen Init
	LD A,2  	; 3= langsamste Steprate
	LD (STEPRATE),A	; einstellen, kein SSO
	LD A,0FFH
	LD (DRVAT),A 	; Drive ungueltig
	RET 

;------------------------------------------------------------------------------

intvek	EQU 38h 	; Interruptziel

flop:			; Haupteingang der Floppy-Routinen
	XOR A  		; sso-Flag auf 0 setzen
flop1:			; a=sso flag, nur 2 zunlaessig
	LD (SSOFLAG),A 	; ok setzen hier moeglich
				; hl = Ziel oder Quelladresse
				; E= Sektor D= Track
				; C= Laufwerkscode+Dichtecode+Seite
				; B= 0 dann Steprate setzen+SSO-Flag
				;  = 1 dann lesen
				;  = 2 dann schreiben

cflo1:	PUSH AF			; entscheiden FLO1 oder FLO2
	LD A,(FLOC0)
	; IF A=1 -> FLO1
	CP 1  
	JP NZ,CFLO2
	
	; FLO1
	LD A,C
	AND 10111111B 		; kein autowait 
	XOR 10H 		; invertieren Dichtebit fuer FLO1
	LD C,A
	; ENDIF

cflo2:	POP AF
	LD (SP0),SP 		; Stack umsetzen, da Tiefe ggf zu gross
	LD SP,TSTACK 		; fuer BDOS

	LD A,0D0H
	OUT (FLO),A 		; Floppy-Controller ruecksetzen
	LD A,(INTVEK)
	LD (LOCINT),A
	LD A,0C3H 		; JP-Befehl
	LD (INTVEK),A
	PUSH HL 		; Ziel, Quelladresse
	LD HL,(INTVEK+1)
	LD (LOCINT+1),HL
	LD HL,INTEX 		; JP INTEX ablegen auf intvek
	LD (INTVEK+1),HL
	POP HL
	IN A,(FLO)		; Status - Port
	IM 1  			; Mode 1 einstellen
	EI  			; Interrupt freigeben
	CALL SOFTEX
	DI  			; Sperren Int
	PUSH AF 		; Status
	LD A,(LOCINT)
	LD (INTVEK),A 		; zurueckspeichern
	PUSH HL
	LD HL,(LOCINT+1)
	LD (INTVEK+1),HL
	POP HL
	POP AF
	LD SP,(SP0) 		; und wieder user-stack verwenden
	RET

;------------------------------------------------------------------------------
; Diverse Unterprogramme

setup:				; testet ob der Kopf noch
				; geladen ist und setzt die
	LD B,0  		; Flag fuer SSO-Bit
	LD A,(CCODE) 		; wenn Bit 7 gesetzt, dann abfragen
	AND 80H
	JR Z,SET2UP 		; Seite 0, immer mit SSO=0
	LD A,(STEPRATE) 	; jetzt pruefen ob flags da
	AND 80H 			;<>0, dann SSO setzen, wenn seite 1
	JR Z,SET1UP 		;=0, dann code 0, oder SSOFLAG
	LD B,2  			;SSO setzen 
	JR SET2UP
set1up:				; pruefen ob SSO-Flag
	LD A,(SSOFLAG) 		; ok, 2=Flag
	AND 2  			; SSO-Bit
	LD B,A  			; 0,2 erlaubt 
set2up:		
					; entsprechenden Bits
	IN A,(FLO4) 		; Status Port
	AND 20H 			; Head-Load Bit
	JR NZ,NOSET 		; =1 dann Kopf auf Diskette
	LD A,B
	OR 4  			; sonst Bitmaske fuer headdown
	RET
noset:
	LD A,B
	RET 			; Code belassen
	
;------------------------------------------------------------------------------

rdflp:				; einen Sektor lesen
				; e=sektor nr
	LD A,C
	OUT (FLO4),A 		; erst mal Dichtecode setzen und Seite
	LD A,E
	OUT (FLO2),A 		; ins Sektorregister
	LD C,FLO3 			; Adresse Datenport dann nach c
	CALL SETUP 			; Register A vorbereiten
	ADD A,88H 			; Lese-Befehl, sidesel=0
	OUT (FLO),A 		; Befehl ausfuehren
rd1:
	IN A,(FLO4) 		; DRQ schon da ?
	RLCA  			; bit7 = drq bit6 = int
	JP NC,RD1 			; bis drq=1 da ist
	INI  				; dann Transport moeglich
	JP RD1  			; und alles wiederholen bis INT

;------------------------------------------------------------------------------

wrflp:				; Floppy-Sektor schreiben
	LD A,C
	OUT (FLO4),A 		; erst mal Seite anwaehlen und Dichte
	LD A,E  			; Sektorregister setzen
	OUT (FLO2),A
	LD C,FLO3			; Adresse Datenport laden
	CALL SETUP			; E-Code in A laden
	ADD A,0A8H			; Befehl Schreibe-Sektor
	OUT (FLO),A 		; und Befehl ausfuehren
wr1:
	IN A,(FLO4)			; warten bis DRQ da
	RLCA
	JP NC,WR1 			; dann Wert ausgeben
	OUTI  			; mit Blockbefehl
	JP WR1  			; verlassen nur durch INT

;------------------------------------------------------------------------------

wawa:				; Warteschleife fuer einige ms
	PUSH BC 		; pro Schleife ca 6ys bei 4MHz
	LD BC,500 		; 500*6ys Dauer
	CALL DELAY
	POP BC
	RET
	
;------------------------------------------------------------------------------

delay:	DEC BC
	LD A,B
	OR C
	JP NZ,DELAY
	RET

;------------------------------------------------------------------------------

seek:				; Spur anfahren C=Drive D=Spur E=Sektor
	CALL WAWA 		; Sicherheitshalber warten
	LD A,C
	OUT (FLO4),A 		; Drive-Code und Dichte sowie Seite
	LD A,E
	OUT (FLO2),A 		; Sektor
	LD A,D
	OUT (FLO3),A 		; Spur
	LD B,1CH 			; Seek-Befehl
	LD A,(STEPRATE)
	AND 3  			; 0,1,2,3  zulaessig
	OR B  			; Seek Befehl zusammen mit Steprate
	OUT (FLO),A 		; als Befehl ausgeben
	HALT  			; warten bis INT

;------------------------------------------------------------------------------

rstore:				; Kopf auf Spur 0 stellen
	CALL WAWA
	LD A,C  			; Laufwerkscode (drive)
	OUT (FLO4),A 		; mit Dichtecode etc. ausgeben
	LD B,8  			; nur Head-load, kein verify
	LD A,(STEPRATE)
	AND 3  			; 0,1,2,3 zulaessig
	OR B  			; als Befehl kombiniert
	OUT (FLO),A 		; und ausfuehren
	HALT  			; bis INT dort warten

;------------------------------------------------------------------------------
; Floppy-Kernroutinen

; hl=adresse, d=track e=sektor
; b=Befehl 0=Steprate setzen 1=read 2=write
; c=Laufwerkscode
;   aufgebaut wie Statusregister
; 7    6    5    4    3    2    1    0
; sso  mot  min  dens d    d    d    d
; sso  = seitenauswahl 1=seite 1
; mot  = motor on code std=0
; min  = 1 bei Minilaufwerken
; dens = 1 bei Single Dense Aufzeichnung
; d=binaerer Laufwerkscode
;   normalerweise nur 1,2,4,8 moeglich
;   Kombinationen moeglich, wenn binaere
;   Dekodierung beim Laufwerk verwendet wird

softex:	LD A,B
	OR A
	JR NZ, SOFT1  		; dann Steprate in Register D (0..3)
	LD A,D   			;(+80h =SSO verwenden und pruefen).
	AND 83H  			; Bit 7=SSO-Flag bei Zugriffen wichtig,
	LD (STEPRATE),A		; die die zweite Seite verwenden.
	XOR A
	RET

soft1:	XOR A
	LD (FEHZA),A 		; Fehlerzahl 0
	LD A,C
	LD (CCODE),A 		; Drive-Code
	AND 0FH 			; fuer Vergleich
	LD C,A  			; wieder zurueck
	LD A,(DRVAT)
	CP 0FFH 			; ungueltig, dann setzen noetig
	JR Z,NOTDEF
	AND 0FH 			; nur Laufwerksnummer relevant
	CP C  			; Vergleich ob Laufwerkewechsel
	JP Z,NURSEEK 		; nur Seek noetig
	PUSH HL
	PUSH BC
	LD HL,DRVTAB 		; Basisadresse
	LD C,A
	LD B,0  			; Alter Laufwerktrack merken
	ADD HL,BC
	IN A,(FLO1) 		; Tracknr
	LD (HL),A 			; und dort ablegen
	POP BC
	POP HL
	
notdef:				; Drive nur laden
	PUSH HL
	PUSH BC
	LD A,(CCODE) 		; neues Laufwerk
	AND 0FH 			; nur Laufwerkscode
	LD C,A
	LD B,0
	LD HL,DRVTAB 		; Tabellenstart
	ADD HL,BC 			; hl zeigt auf Laufwerkstrack
	LD A,(HL)
	OUT (FLO1),A 		; und ins Register des FDs
	POP BC
	POP HL
	LD A,(CCODE)
	LD (DRVAT),A 		; ist nun neues Laufwerk
	PUSH BC
	LD BC,1000*3/12		; ca 1ms warten
	CALL DELAY
	LD A,(CCODE) 		; Dann neues Laufwerk ansprechen
	OUT (FLO4),A
	LD BC,2917			; ca 35ms .. 15ms
	CALL DELAY			; um head-load-Zeit zu beruecksichtigen 
	POP BC  			; alte Codes zurueck
	JR NUR1 			; Immer auf ready pruefen, da
					; head down sein kann und dennoch
					; nicht ready

nurseek:
	IN A,(FLO4) 		; wenn head down dann kein dummyseek
	AND 20H
	JR NZ,NODUM
nur1:					; immer einsprung
	LD A,(CCODE)
	LD C,A
	CALL SEEKEX 		; seek selekt dummy nur fuer readytest
	IN A,(FLO)			; test Status
	AND 80H 			; fuer Ready
	JR NZ,NUR1			; Wiederhole solange bis Laufwerk READY
nodum:				; Einsprung head down ok
	IN A,(FLO1) 		; nun pruefen of Tracks gleich sind
	CP 0FFH 			; nicht definiert
	JR Z,TRY1 			; dann zuerst RESTORE
	CP D  			; oder schon auf dem Track
	JP Z,SK11 			; ja dann nur lesen,schreiben
	TRYº  			; SEEK ausfuehren
	LD A,(CCODE)
	LD C,A
	CALL SEEKEX 		; und Track anfahren Reg retten
	AND 10010000B 		; Fehlermaske
	JR Z,SK11 			; ja dann R/W moeglich
try1:					; Laufwerk normieren und RSTORE
	LD A,(CCODE)
	LD C,A
	PUSH HL
	PUSH DE
	PUSH BC
	CALL RSTORE
	POP BC
	POP DE
	POP HL
	LD A,(FEHZA) 		; Fehler erhoehen
	INC A
	LD (FEHZA),A
	CP 10  			; bei 10 Fatal-Fehler
	JR C,TRY 			; sonst nochmals mit SEEK probieren
error1:
	LD A,0FFH
	OR A
	SCF  				; 0ffh, carry als Fehlerflag
	RET  				; ABBRUCH FATAL

noerr1:				; Ausgang wenn kein Fehler da
	XOR A
	RET
;
sk11:					; r/w ausfuehren
	LD A,B
	CP 2
	JP Z,WRTEX			; Schreibbefehl
	LD A,(CCODE)
	LD C,A
	PUSH HL
	PUSH DE
	PUSH BC
	CALL RDFLP			; und Lesen
	POP BC
	POP DE
	POP HL
	AND 10011100B 		; Fehlermaske incl. Lost data
	JR Z,NOERR1 		; ende
	AND 00010000B 		; bei record not found SEEK
	JR NZ,TRY1			; mit vorherigem Restore
	LD A,(FEHZA)
	INC A
	LD (FEHZA),A 		; CRC Fehler sonst
	CP 5  			; kleiner als 5 dann nochmals probieren
	JR C,SK11
	CP 10
	JR C,TRY1 			; sonst rstore und seek
	JR ERROR1 			; sonst FATAL - Fehler

wrtex:				; Schreiben
	LD A,(CCODE)
	LD C,A
	PUSH HL
	PUSH DE
	PUSH BC
	CALL WRFLP
	POP BC
	POP DE
	POP HL
	AND 11111100B
	JR Z,NOERR1 		; alles ok
	AND 00010000B 		; record not found
	JR NZ,TRY1			; gleich neuen Seek ausfuehren
	LD A,(FEHZA)
	INC A
	LD (FEHZA),A 
	CP 4  			; recht bald, da i.A. nur record not fnd
	JR C,TRY1 			; daher nur 4 Versuche
	JR ERROR1 			; FATAL FEHLER

seekex:				; Seek ausfuehren
	PUSH HL
	PUSH DE
	PUSH BC
	CALL SEEK
	POP BC
	POP DE
	POP HL
	RET

;==============================================================================
; *** ENDE der Floppy-Routinen ***
;==============================================================================
; RAM

		; Buffer Bereich fuer Floppy-Routinen

steprate:
	DEFB 0    		; Merker fuer die Steprate + SSO-Option
ssoflag:
	DEFB 0    		; zusaetzlich, dominant, fuer MINI
sp0:	DEFW 0 			; Stackmerker fuer BDOS
				; =2, dann mit sso, sonst 0
locint:	DEFB 0,0,0 		; Merker fuer alten Inhalt Intvektor
fehza:	DEFB 0    		; Fehlerzaehler fuer retry
ccode:	DEFB 0    		; Drive-Code
drvat:	DEFB 0FFH  		; letztes Laufwerk
drvtab:	DEFB 0FFH,0ffh,0ffh,0ffh 	; 16 moegliche Laufwerke
	DEFB 0FFH,0ffh,0ffh,0ffh
	DEFB 0FFH,0ffh,0ffh,0ffh
	DEFB 0FFH,0ffh,0ffh,0ffh
	
	DEFS 100   		; lokaler Stack
tstack:	DEFB 0

;==============================================================================
; ENDE FLO2-Routinen
;==============================================================================

task:	DEFS 6  		;task block
oldsec:	DEFW 0  		;frueherer sector a 128
imwr:	DEFB 0ffh 		;wichtig init auf ff,wiini etc
hstbuf:	DEFS 256 		;sector buffer
imbef:	DEFB 0  		;befehl =1 read =2 write
sectrk:	DEFW 0  		;sectoradresse a 128
imdma:	DEFW 0  		;adresse ziel,quelle
floc0:	DEFB 0  		;0=FLO2, 1=FLO1

;==============================================================================
; IDE Karten Interface für CF-Karte
;
; Subroutine to read one IDE/ATA Disk sector (256 bytes)
; Address to place data passed in HL
; LBA bits 0 to 7 passed in C, bits 8 to 15 passed in B
; LBA bits 16 to 23 passed in E
;

IDERD:
IDERD1:	IN	A,(IDESTAT)	; check status
	AND	80H		; check BSY bit
	JP	NZ,IDERD1	; loop until not busy

IDERD2:	IN	A,(IDESTAT)	; check	status
	AND	40H		; check DRDY bit
	JP	Z,IDERD2	; loop until ready

	LD	A,01H		; number of sectors = 1
	OUT	(SECCND),A	; sector count register
	LD	A,C
	OUT	(LBA7),A	; lba bits 0 - 7
	LD	A,B
	OUT	(LBA15),A	; lba bits 8 - 15
	LD	A,E
	OUT	(LBA23),A	; lba bits 16 - 23
	LD	A,11100000B	; LBA mode, select drive 0
	OUT	(IDEHEAD),A	; drive/head register
	LD	A,20H		; Read sector command
	OUT	(IDESTAT),A

IDERD3:	; WAIT FOR DRQ SET
	IN	A,(IDESTAT)	; read status
	AND	08H		; DRQ bit
	JP	Z,IDERD3	; loop until bit set
	
IDERD4:	; WAIT FOR BUSY CLEay
	IN	A,(IDESTAT)
	AND	80H
	JP	NZ,IDERD4
	
	IN	A,(IDESTAT)	; clear INTRQ

IDERD5: ; READ LOOP
	IN	A,(IDEDATA)	; get data
	LD	(HL),A
	INC	HL
	IN	A,(IDESTAT)	; check status
	AND	08H		; DRQ bit
	JP	NZ,IDERD5	; loop until cleared
	
	RET
			
;------------------------------------------------------------------------------
;
; Subroutine to write one IDE/ATA Disk sector (256 bytes)
; Address of data to write to disk passed in HL
; LBA bits 0 to 7 passed in C, bits 8 to 15 passed in B
; LBA bits 16 to 23 passed in E

IDEWR:
IDEWR1:	IN	A,(IDESTAT)	; check status
	AND	80H		; check BSY bit
	JP	NZ,IDEWR1	; loop until not busy

IDEWR2:	IN	A,(IDESTAT)	; check status
	AND	40H		; check DRDY bit
	JP	Z,IDEWR2	; loop until ready

	LD	A,01H		; number of sectors = 1
	OUT	(SECCND),A	; sector count register
	LD	A,C
	OUT	(LBA7),A	; lba bits 0 - 7
	LD	A,B
	OUT	(LBA15),A	; lba bits 8 - 15
	LD	A,E
	OUT	(LBA23),A	; lba bits 16 - 23
	LD	A,11100000B	; LBA mode, select drive 0
	OUT	(IDEHEAD),A	; drive/head register
	LD	A,30H		; Write sector command
	OUT	(IDESTAT),A
	
IDEWR3:	; WAIT FOR DRQ SET
	IN	A,(IDESTAT)	; read status
	AND	08H		; DRQ bit
	JP	Z,IDEWR3	; loop until bit set			

IDEWR4:	; WRITE LOOP
	LD	A,(HL)
	OUT	(IDEDATA),A	; write data
	INC	HL
	IN	A,(IDESTAT)	; read status
	AND	08H		; check DRQ bit
	JP	NZ,IDEWR4	; write until bit cleared

IDEWR5:	; WAIT FOR BUSY CLEAr
	IN	A,(IDESTAT)
	AND	80H
	JP	NZ,IDEWR5

	IN	A,(IDESTAT)	; clear INTRQ
	RET

FREEMEM EQU $ 	;dynamischer Platz fuer Buffer etc.

;------------------------------------------------------------------------------
; Bereich kann geloescht werden unter CP/M
; um Platz fuer Puffer etc zu bieten

MSG:	DEFB CR,LF

	DEFM ESC,"[2J",ESC,"[H",BELL,CR,LF
	DEFM " -------------------------",CR,LF
	DEFM " Monitor MC COMPUTER V 7.2",CR,LF
	DEFM "   RDK/JS 1985 - UH 2026",CR,LF
	DEFM	" -------------------------",CR,LF,LF
	DEFM " Bootmenue = I",CR,LF,LF,0
	MSGL EQU $-MSG

INIT1:	;nur einmal verwendet

; Hardware Initialisierung Z80 SIO

	LD C,sa_sts
	LD B,8
	LD HL,TABSIA
	OTIR
	LD C,sb_sts
	LD B,8
	LD HL,TABSIB
	OTIR
	JR SKSKL

TABSIA:	DEFB 1,0
	DEFB 3,11100001B	; -CTS UND -DCD ENABLE rev 3.4 term1
	DEFB 4,01001100B
	DEFB 5,11101010B	;dtr rts +12V bedeutet ready rev 3.4

TABSIB:	DEFB 1,0
	DEFB 3,11100001B	; -CTS UND -DCD ENABLE
	DEFB 4,01001100B
	DEFB 5,11101010B	;dtr rts +12V bedeutet ready rev 3.4

;------------------------------------------------------------------------------

; Init 8251 (D71051c)
SKSKL:
;INIT_UART:
	XOR	A		; lt. Datenblatt erst mal "aufwecken"
	OUT	(U_STS),A	; SyncMode
	OUT	(U_STS),A	; SyncMode
	OUT	(U_STS),A	; SyncMode

	LD	A,40H		; Reset
	OUT	(U_STS),A	; UART Status Port

	LD	A,04EH		; BAUD x16, 8,1,n
	OUT	(U_STS),A	; UART Status Port
	LD	A,37H		; Cmd: TXE,RXE,RTS=LOW,DSR=LOW
	OUT	(U_STS),A	; UART Status Port
					
;------------------------------------------------------------------------------
; Monitor cold start

COLD:	LD A,(7000H)		; Bank-Select umschalten
	XOR A			; alles auf Console schalten
	LD (IOBYT),A

	LD SP,AHEAD-4
	JP MEMSIZ1

;------------------------------------------------------------------------------

	DEFW AHEAD

AHEAD:	LD SP,HL
	EX DE,HL
	LD BC,ENDX-EXIT
	LD HL,EXIT
	LDIR
	EX DE,HL
	LD BC,-5FH
	ADD HL,BC
	PUSH HL
	LD HL,0
	LD B,10 		; REGISTER

STKIT:	PUSH HL
	DJNZ STKIT

HELLO:	LD C,1AH
	CALL CO
	LD B,MSGL
	CALL TOM1

	;----------------------------------------------------------------------
	
WARM:	; main input loop

WARM:	LD DE,WARM
	PUSH DE
	CALL CRLF
	LD C,'>'
	CALL CO
	
WARM1:	CALL TI
	AND 7FH
	JR Z,WARM1
	
	SUB 'A'
	RET M
	CP 'Z'-'A'+1
	RET NC
	ADD A,A
	LD HL,TBL
	ADD A,L
	LD L,A
	LD A,H
	ADC A,0
	LD H,A
	LD A,(HL)
	INC HL
	LD H,(HL)
	LD L,A
	LD C,2
	JP (HL)		; execute monitor command

;------------------------------------------------------------------------------
; Befehlstabelle
; enthaelt alle Monitorbefehle

TBL:	DEFW ASSIGN	; A
	DEFW BYE	; B
	DEFW COMP	; C
	DEFW DISP	; D
	DEFW EOF	; E
	DEFW FILL	; F
	DEFW GOTO	; G
	DEFW HEXN	; H
	DEFW BOOT	; I
	DEFW TEST	; J
	DEFW KEXEC	; K
	DEFW LOAD	; L
	DEFW MOVE	; M
	DEFW NULL	; N
	DEFW OEXEC	; O
	DEFW PUTA	; P
	DEFW QUERY	; Q
	DEFW READ	; R
	DEFW SUBST	; S
	DEFW TYPE	; T
	DEFW UNLOAD	; U
	DEFW VERIFY	; V
	DEFW WRITE	; W
	DEFW XAM	; X
	DEFW WHERE	; Y
	DEFW SIZE	; Z

;------------------------------------------------------------------------------
; BOOT FLOPPY HARD/SOFT/MINI

BOOTMSG:
	DEFB CR,LF,LF
	DEFM "FLO2-Boot = 1, IDE/CF Karte = 2, FLO1-Boot = 3 : " 
FLPL	EQU $-BOOTMSG

BOOT:	CALL INIFLP 	; Vektoren etc definieren
	LD HL,BOOTMSG 	; Meldung ausgeben
	LD B,FLPL 	 
	CALL TOM 	; dann Antwort abwarten
	CALL CI
	AND 7FH  	; ohne Paritaet
	LD C,A
	CALL CO		; echo
	CALL CRLF
	
	CP "I"  	; I-Vektor fuer Benutzerbefehl
	JP Z,IEXEC	; 'I'
	
	CP "2"
	JR Z,IDE_CF	; '2' -> IDE-CF Boot
	
	CP '3'
	JP NZ,BOOT1
	
	; '3' = FLO1
	LD A,1
	LD (FLOC0),A	; 1 = FLO1
	JP BOOT3
	
BOOT1:	CP '1' 
	JP NZ,BOOT2
	
	; '1' = FLO2
	XOR A
	LD (FLOC0),A 	; 0 = FLO2
	JP BOOT3

BOOT2:	JP ERROR

BOOT3:

;+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++		
; Ueberspringt autom. Format Erkennung bei boot 
; fuer original löschen oder auskommentieren
; 2026 geaendert wg. Boot von DD Disketten
; FLO1/FLO2 in A

	LD C,00100001B 	; immer von Laufwerk A Mini Floppy Seite 0, DD booten
	LD HL,80H	; SD, load 128 byte boot sector to address 0080h
	JP EXEC1
	
; Ende +++++++++++++++++++++++++++++++++++++++++++++++++++++
			; automatisch Format bestimmen, REV 1.1
	LD C,00000001b 	; immer von Laufwerk A  Seite 0 booten
	CALL GETFL	; Formatierung bestimmen
	JP C,ERROR	; bei Fehler zurueck ins Menue	
	LD HL,80H 	; bei einfacher Dichte nach 80h
	BIT 4,C  	; =0, dann dd, sonst sd
	JR NZ,EXEC1 	; sd
	LD HL,0FC00H 	; sonst 1K Block ggf. dorthin.
; Ende +++++++++++++++++++++++++++++++++++++++++++++++++++++

exec1:	PUSH HL 	; rev (1.5) 1.1
	LD B,1  	; lesen
	LD D,0  	; track 0
	LD E,1  	; sektor 1
	CALL FLOP
	POP HL  	; Boot sector address
	JP NZ,ERROR
	
	JP (HL) 	; Boot sector ausfuehren

;------------------------------------------------------------------------------

IDE_CF:	LD HL,08000h	; laedt Bootloader von IDE/ATA Disk
			; in die RAM Adresse 08000h
	LD BC,0000h	; LBA 0
	LD E,00H
	CALL IDERD
	JP 08000H	; Boot sector ausfuehren

;------------------------------------------------------------------------------
; Monitor command ASSIGN

; assign IOBYTE
; 000000XX CONSOLE
; 0000XX00 READER
; 00XX0000 PUNCH
; XX000000 LISTER
; 00= TELETYPE CONS

ASSIGN:	CALL TI
	LD HL,LTBL
	LD BC,400H
	LD DE,5

ASSIG1:	CP (HL)
	JR Z,ASSIG2
	
	ADD HL,DE
	INC C
	DJNZ ASSIG1
	JR ASSIG5
	
ASSIG2:	LD E,C

ASSIG3:	CALL TI
	CP "="
	JR NZ,ASSIG3
	
	CALL TI
	LD BC,400H

ASSIG4:	INC HL
	CP (HL)
	JR Z,ASSIG6
	
	INC C
	DJNZ ASSIG4
	
ASSIG5:	; error
	JP ERROR
	
ASSIG6:	LD A,3
	INC E

ASSIG7:	DEC E
	JR Z,ASSIG8
	
	SLA  C
	SLA  C
	RLA
	RLA
	JR ASSIG7
	
ASSIG8:	CPL
	LD D,A
	
ASSIG9:	CALL PCHK
	JR NC,ASSIG9
	LD A,(IOBYT)
	AND D
	OR C
	LD C,A
	JP IOSET

;------------------------------------------------------------------------------
; Monitor command BYE

BYE:	CALL CRLF

BYE1:	CALL CI7	; In HEX Dump 1E 
	CP 0EH  	; CRTL-N ist 0Eh
	JR NZ,BYE1 	; gaendert gegenueber MC-Vers

	POP DE
	JP HELLO

;------------------------------------------------------------------------------
; Monitor command PUT ASCII
; PUT ASCII INTO MEM
; Texte direkt in den Speicher eingeben

PUTA:	CALL EXPR1
	CALL CRLF
	POP HL

PUTA1:	CALL CI7
	CP 4  		; Beenden der Eingabe CTRL-D
	JP Z,LFADR
	CP "_"  	; Rueckwaertsschritt
	JR Z,PUTA3
	
	LD (HL),A
	LD C,A
	INC HL

PUTA2:	CALL CO
	JR PUTA1

PUTA3:	DEC HL
	LD C,(HL)
	JR PUTA2

;------------------------------------------------------------------------------
; Monitor command COMPARE
;
; COMPARE BIN
; Vergleich eines Speicherbereichs mit dem Reader

COMP:	CALL EXLF

COMP1:	CALL RIFF	; Reader in
	CP (HL)
	CALL NZ,CERR
	
	CALL HILOX	; -> check HL, RET
	JR COMP1

	; M AUSGABE

CERR:	; error
	LD B,A
	CALL HLSP
	LD A,(HL)
	CALL LBYTE
	CALL BLK
	LD A,B
	CALL LBYTE
	JP CRLF

;------------------------------------------------------------------------------
; Monitor command DISPLAY
; Ausgabe eines Speicherbereichs

DISP:	CALL EXLF

DISP1:	CALL LFADR

DISP2:	CALL BLK
	LD A,(HL)
	CALL LBYTE
	CALL HILOX	; -> check HL, RET
	LD A,L
	AND 0FH
	JR NZ,DISP2
	
	JR DISP1

;------------------------------------------------------------------------------
; Monitor command EOF
; Output EOF for Punch
; Intel-Hex Ende ausgeben

EOF:	CALL EXPR1
	CALL PEOL
	LD C,':'
	CALL POO
	XOR A
	CALL PBYTE
	POP HL
	CALL PADR
	LD HL,0
	CALL PADR
	JP NULL

;------------------------------------------------------------------------------
; Monitor command FILL
; Einen Speicherbereich mit einem Wert fuellen

FILL:	CALL EXPR3

FILL1:	LD (HL),C
	CALL HILO
	JR NC,FILL1
	
	POP DE
	JP WARM

;------------------------------------------------------------------------------
; Monitor command GOTO
; Start eines Anwenderprogramms mit Break-Points

GOTO:	CALL PCHK
	JR C,GOTO5
	JR Z,GOTO1
	
	CALL EXF
	POP DE
	LD HL,PLOC
	ADD HL,SP
	LD (HL),D
	DEC HL
	LD (HL),E
	LD A,B
	CP 0DH
	JR Z,GOTO5

GOTO1:	LD D,2
	LD HL,TLOC
	ADD HL,SP

GOTO2:	PUSH HL
	CALL EXPR1
	LD E,B
	POP BC
	POP HL
	LD A,B
	OR C
	JR Z,GOTO3
	
	LD (HL),C
	INC HL
	LD (HL),B
	INC HL
	LD A,(BC)
	LD (HL),A
	INC HL
	LD A,0FFH
	LD (BC),A

GOTO3:	LD A,E
	CP 0DH
	JR Z,GOTO4

	DEC D
	JR NZ,GOTO2

GOTO4:	LD A,0C3H 	; Rueckkehr mit RST7 vorbereiten
	LD (RST7),A
	LD HL,TRAP
	LD (RST7+1),HL

GOTO5:	CALL CRLF
	POP DE
	LD HL,22
	ADD HL,SP
	JP (HL)  	; und Programm starten
	
;------------------------------------------------------------------------------
; Monitor command TEST
; FAST Complement Test fuer den Speicher

TEST:	CALL EXLF
TEST1:
	LD A,(HL)
	LD B,A
	CPL
	LD (HL),A
	XOR (HL)
	JR Z,TEST2
	
	PUSH DE
	LD D,B
	LD E,A
	CALL HLSP
	CALL BITS
	CALL CRLF
	LD B,D
	POP DE

TEST2:	LD (HL),B
	CALL HILOX	; -> check HL, RET
	JR TEST1
	
;------------------------------------------------------------------------------
; Monitor command MOVE
; Speicherbereich verschieben

MOVE:	CALL EXPR3

MOVE1:	LD A,(HL)
	LD (BC),A
	INC BC
	CALL HILOX	; -> check HL, RET
	JR MOVE1
	
;------------------------------------------------------------------------------
; Monitor command READ
; Einlesen von Intel-Hex oder TDL-Daten

READ:	CALL EXPR1
	LD A,B
	SUB 0DH
	LD B,A
	LD C,A
	POP DE
	JR Z,READ1
	
	CALL EXPR1
	POP BC

READ1:	EX DE,HL
	EXX
	CALL CRLF

READ2:	CALL RIX
	SUB ':'
	LD B,A
	AND 0FEH
	JR NZ,READ2
	
	LD D,A
	CALL SBYTE
	LD E,A
	CALL SBYTE
	PUSH AF
	CALL SBYTE
	EXX
	POP DE
	LD E,A
	PUSH BC
	PUSH DE
	PUSH HL
	ADD HL,DE
	EX (SP),HL
	POP IX
	EXX
	POP HL
	CALL SBYTE
	DEC A
	LD A,B
	POP BC
	JR NZ,READ3
	
	ADD HL,BC
	ADD IX,BC

READ3:	; arepa
	INC E
	DEC E
	JR Z,READ7
	DEC A
	JR Z,READ8

READ4:	CALL SBYTE
	CALL STORE
	JR NZ,READ4

READ5:	CALL SBYTE
	JR Z,READ2
	
READ6:	; err
	PUSH IX
	POP HL
	CALL LADR
	JP ERROR
	
READ7:	; done
	LD A,H
	OR  L
	RET Z
	EX DE,HL
	LD HL,PLOC
	ADD HL,SP
	LD (HL),D
	DEC HL
	LD (HL),E
	RET
	
READ8:	LD L,1

READ9:	CALL READ12
	JR C,READ11

READ10:	CALL STORE
	JR NZ,READ9
	JR READ5

READ11:	LD C,A
	CALL READ12
	LD B,A
	EXX
	PUSH BC
	EXX 
	EX (SP),HL
	ADD HL,BC
	LD A,L
	CALL STORE
	LD A,H
	POP HL
	JR READ10

READ12:	DEC L
	JR NZ,READ13
	
	CALL SBYTE
	DEC E
	LD H,A
	LD L,8

READ13:	CALL SBYTE
	SLA H
	RET

;------------------------------------------------------------------------------

SBYTE:	; sbyte
	PUSH BC
	CALL RIBBLE
	RLCA
	RLCA
	RLCA
	RLCA
	LD C,A
	CALL RIBBLE
	OR C
	LD C,A
	ADD A,D
	LD D,A
	LD  A,C
	POP BC
	RET

;------------------------------------------------------------------------------

STORE:	; store
	LD (IX+0),A
	CP (IX+0)
	JR NZ,READ6
	INC IX
	DEC E
	RET
	
;------------------------------------------------------------------------------
; Monitor command SUBST
; Interaktive Eingabe von Hex-Werten

SUBST:	CALL EXPR1
	POP HL
	
SUBST1:	LD A,(HL)
	CALL LBYTE
	CALL COPCK
	RET C
	JR Z,SUBST2
	CP '_'
	JR Z,SUBST4
	
	PUSH HL
	CALL EXF
	POP DE
	POP HL
	LD (HL),E
	LD A,B
	CP 0DH
	RET Z

SUBST2:	INC HL

SUBST3:	LD A,L
	AND 7
	CALL Z,LFADR
	JR SUBST1

SUBST4:	DEC HL
	JR SUBST3
	
;------------------------------------------------------------------------------
; Monitor command TYPE
; Ausgabe von Speicherbereichen in lesbarer Form
;
TYPE:	CALL EXLF

TYPE1:	CALL LFADR
	LD B,32+32

TYPE2:	LD A,(HL)
	AND 7FH
	CP ' '
	JR NC,TYPE4

TYPE3:	LD A,'.'

TYPE4:	CP 7CH
	JR NC,TYPE3
	
	LD C,A
	CALL CO
	CALL HILOX
	DJNZ TYPE2
	
	JR TYPE1
	
;------------------------------------------------------------------------------
; Monitor command SEARCH
; Suchen von Werten im Speicher
;
WHERE:	LD D,0

WHER1:	CALL EXPR1
	POP HL
	LD H,L
	PUSH HL
	INC  SP
	INC D
	LD A,B
	SUB 0DH
	JR NZ,WHER1
	LD B,A
	LD C,A
	LD H,A
	LD L,D
	DEC L
	ADD HL,SP
	PUSH HL
	PUSH BC

WHER2:	; findc
	PUSH BC
	CALL CRLF
	POP BC
	
WHER3:	; find
	POP HL
	POP IX
	LD E,D
	LD A,(IX+0)
	CPIR
	JP PO,WHER6
	
	PUSH IX
	PUSH HL
	
WHER4:	; found
	DEC E
	JR Z,WHER5
	
	LD A,(IX-1)
	CP (HL)
	JR NZ,WHER3
	
	INC HL
	DEC IX
	JR WHER4
	
WHER5:	; tell
	POP HL
	PUSH HL
	DEC HL
	PUSH BC
	CALL LADR
	POP BC
	JR WHER2

WHER6:	; done
	INC SP
	DEC E
	JR NZ,WHER6
	RET

;------------------------------------------------------------------------------
; Monitor command WRITE
; Output Intex Hex to Punch

WRITE:	CALL EXLF

WRITE1:	CALL PEOL
	LD BC,':'
	CALL POO
	PUSH DE
	PUSH HL

WRITE2:	INC B
	CALL HILO
	JR C,WRITE5
	
	LD A,24
	SUB B
	JR NZ,WRITE2
	
	POP HL
	CALL WRITE3
	POP DE
	JR WRITE1
	
	;----------------------------------------------------------------------

WRITE3:	LD D,A
	LD A,B
	CALL PBYTE
	CALL PADR
	XOR  A
	CALL PBYTE

WRITE4:	LD A,(HL)
	CALL PBYTE
	INC HL
	DJNZ WRITE4
	
	XOR A
	SUB D
	JP PBYTE

WRITE5:	POP HL
	POP DE
	XOR  A
	JR WRITE3

;------------------------------------------------------------------------------
; Monitor command XAM
; Output and change microcontroller registers

XAM:	CALL TI
	LD HL,ACTBL
	CP 0DH
	JR Z,XAM7
	
	CP "'"
	JR NZ,XAM1

	LD HL,PRMTB
	CALL TI
	CP 0DH
	JR Z,XAM7
	
XAM1:	CP (HL)
	JR Z,XAM2
	
	BIT 7,(HL)
	JP NZ,ERROR
	
	INC HL
	INC HL
	JR XAM1

XAM2:	CALL BLK

XAM3:	INC HL
	LD A,(HL)
	LD B,A
	AND 3FH
	EX DE,HL
	LD L,A
	LD H,0
	ADD HL,SP
	EX DE,HL
	INC HL
	LD A,(DE)
	CALL LBYTE
	BIT 7,B
	JR Z,XAM4
	
	DEC DE
	LD A,(DE)
	CALL LBYTE

XAM4:	CALL COPCK
	RET C
	
	JR Z,XAM6
	
	PUSH HL
	PUSH BC
	CALL EXF
	POP HL
	POP AF
	PUSH BC
	PUSH AF
	LD A,L
	LD (DE),A
	POP BC
	BIT 7,B
	JR Z,XAM5
	
	INC DE
	LD A,H
	LD (DE),A

XAM5:	POP BC
	POP HL
	LD A,B
	CP 0DH
	RET Z

XAM6:	BIT 7,(HL)
	RET NZ
	JR XAM3

XAM7:	CALL CRLF

XAM8:	CALL BLK
	LD A,(HL)
	INC HL
	OR A
	RET M
	LD C,A
	CALL CO
	LD C,"="
	CALL CO
	LD A,(HL)
	LD B,A
	AND 3FH
	INC HL
	EX DE,HL
	LD L,A
	LD H,0
	ADD HL,SP
	EX DE,HL
	BIT 6,B
	JR NZ,XAM10

	LD A,(DE)
	CALL LBYTE
	BIT 7,B
	JR Z,XAM8

	DEC DE
	LD A,(DE)

XAM9:	CALL LBYTE
	JR XAM8

XAM10:	PUSH HL
	LD A,(DE)
	LD H,A
	DEC DE
	LD A,(DE)
	LD L,A
	LD A,(HL)
	POP HL
	JR XAM9
	
;------------------------------------------------------------------------------
; Monitor message output routine
; Address in HL
; Length in B

TOM1:	LD HL,MSG

TOM:	LD C,(HL)
	INC HL
	CALL CO
	DJNZ TOM
	CALL CSTS
	OR A
	RET Z

; IF CTRL C ABORT

CCHK:	CALL CI7
	CP 3
	RET NZ

;------------------------------------------------------------------------------
; ERROR

ERROR:	CALL MEMSIZ
	LD DE,-22
	ADD HL,DE
	LD SP,HL
	LD C,7
	CALL CO
	LD C,'*'
	CALL CO
	JP WARM

;------------------------------------------------------------------------------
; Reader Input
; abort on carry
; compare with D

RIFF:	CALL RI
	JR C,ERROR
	CP D
	RET

;------------------------------------------------------------------------------
; Monitor command SIZE
; Output size of memory

SIZE:	CALL MEMSIZ
	LD BC,ENDX-EXIT
	ADD HL,BC

LFADR:	CALL CRLF

HLSP:	CALL LADR

BLK:	LD C,' '
	JP CO

;------------------------------------------------------------------------------
; Punch EOL

PEOL:	LD C,0DH
	CALL POO
	LD C,0AH
	JP POO

;------------------------------------------------------------------------------
; Monitor command UNLOAD
; Ausgabe eines Speicherbereichs binaer ueber Punch

UNLOAD:	CALL EXLF
	CALL LEAD
	CALL MARK

UNLOD1:	LD C,(HL)
	CALL POO
	CALL HILO
	JR NC,UNLOD1
	
	CALL MARK

;------------------------------------------------------------------------------
; Monitor command NULL
; NULL PUNCH
;
NULL:	CALL LEAD
	RET

;------------------------------------------------------------------------------

CONV:	AND 0FH
	ADD A,90H
	DAA 
	ADC A,40H
	DAA
	LD C,A 	;HEX TO ASC
	RET

;------------------------------------------------------------------------------

EXLF:	CALL EXPR
	POP DE
	POP HL

;------------------------------------------------------------------------------

CRLF:	PUSH HL
	push AF
	LD B,2
	CALL TOM1
	POP AF
	POP HL
	RET

;------------------------------------------------------------------------------
; Eingabe von Hex-Wertes von der Console

EXPR3:	INC C
	CALL EXPR
	CALL CRLF
	POP BC
	POP DE
	POP HL
	RET

;------------------------------------------------------------------------------

EXPR1:	LD C,1

EXPR:	LD HL,0

EX0:	CALL TI

EX1:	LD B,A
	CALL NIBBLE
	JR C,LXEX2
	ADD HL,HL
	ADD HL,HL
	ADD HL,HL
	ADD HL,HL
	OR L
	LD L,A
	JR EX0

LXEX2:	EX (SP),HL
	PUSH HL
	LD A,B
	CALL QCHK
	JR NC,LXEX3
	DEC  C
	RET Z

LXEX3:	JP NZ,ERROR
	DEC C
	JR NZ,EXPR
	RET

EXF:	LD C,1
	LD HL,0
	JP EX1

;------------------------------------------------------------------------------

HILOX:	CALL HILO
	RET NC

	POP DE
	RET

;------------------------------------------------------------------------------

HILO:	INC HL
	LD A,H
	OR L
	SCF
	RET Z
	
	LD A,E
	SUB L
	LD  A,D
	SBC A,H
	RET

;------------------------------------------------------------------------------
; Monitor command HEXN
; HEX MATH

HEXN:	CALL EXLF
	PUSH HL
	ADD HL,DE
	CALL HLSP
	POP HL
	OR   A
	SBC HL,DE
	
	; Entry
	
LADR:	LD A,H
	CALL LBYTE
	LD A,L

LBYTE:	PUSH AF
	RRCA
	RRCA
	RRCA
	RRCA
	CALL LXR22
	POP AF

LXR22:	CALL CONV
	JP CO

;------------------------------------------------------------------------------

MARK:	LD BC,8FFH
	JR LEO

;------------------------------------------------------------------------------

LEAD:	LD BC,4800H

LEO:	CALL POO
	DJNZ  LEO
	RET

;------------------------------------------------------------------------------

RIBBLE:	CALL RIX

NIBBLE:	SUB '0'
	RET C
	CP 'G'-'0'
	CCF
	RET C
	CP 10
	CCF
	RET NC
	SUB 'A'-'9'-1
	CP 0AH
	RET
	
;------------------------------------------------------------------------------

PADR:	LD A,H
	CALL PBYTE
	LD A,L

PBYTE:	PUSH AF
	RRCA
	RRCA
	RRCA
	RRCA
	CALL CONV
	CALL POO
	POP AF
	PUSH AF
	CALL CONV
	CALL POO
	POP AF
	ADD A,D
	LD D,A
	RET

;------------------------------------------------------------------------------

COPCK:	LD C,'-'
	CALL CO

PCHK:	CALL TI

QCHK:	CP ' '
	RET Z
	CP ','
	RET Z
	CP 0DH
	SCF
	RET Z
	CCF
	RET
	
;------------------------------------------------------------------------------

RIX:	CALL RIFF	; Reader input
	AND 7FH
	RET

;------------------------------------------------------------------------------
; Monitor command LOAD
; Laden von Binaerdaten 
; Startkennung ist eine Gruppe von 0FFh-Werten

LOAD:	CALL EXPR1
	POP HL
	CALL CRLF
	LD D,0FFH

LOAD1:	LD B,4

LOAD2:	CALL RIFF	; Reader input
	JR NZ,LOAD1
	
	DJNZ LOAD2
	
LOAD3:	CALL RIFF	; Reader input
	JR Z,LOAD3
	
	LD (HL),A
	LD A,7
	
;+++ OUT TTY +++
LOAD4:	INC HL
	CALL RIFF
	JR Z,LOAD5
	
	LD (HL),A
	JR LOAD4

LOAD5:	LD E,1

LOAD6:	CALL RIFF	; Reader input
	JR NZ,LOAD7
	
	INC E
	LD A,7 		; MAX +++
	CP E
	JR NZ,LOAD6
	JP LADR

LOAD7:	LD (HL),D
	INC HL
	DEC  E
	JR NZ,LOAD7
	
	LD (HL),A
	JR  LOAD4

; -----------------------------------------------------------------------------
; Entry after Break-Point

RSTRTB:	PUSH HL
	PUSH DE
	PUSH BC
	PUSH AF
	CALL MEMSIZ
	EX DE,HL
	LD HL,10
	ADD HL,SP
	LD B,4
	EX DE,HL

RSTRT2:	DEC HL
	LD (HL),D
	DEC HL
	LD (HL),E
	POP DE
	DJNZ RSTRT2
	
	POP BC
	DEC BC
	LD SP,HL
	LD HL,TLOCX
	ADD HL,SP
	LD A,(HL)
	SUB C
	INC HL
	JR NZ,RSTRT3
	
	LD A,(HL)
	SUB B
	JR Z,RSTRT5

RSTRT3:	INC HL
	INC HL
	LD  A,(HL)
	SUB C
	JR NZ,RSTRT4
	
	INC HL
	LD  A,(HL)
	SUB B
	JR Z,RSTRT5

RSTRT4:	INC BC

RSTRT5:	LD HL,LLOCX
	ADD HL,SP
	LD (HL),E
	INC HL
	LD (HL),D
	INC HL
	INC HL
	LD (HL),C
	INC HL
	LD (HL),B
	PUSH BC
	LD C,'@'
	CALL CO
	POP HL
	CALL LADR
	LD HL,TLOCX
	ADD HL,SP
	LD BC,200H

RSTRT6:	LD E,(HL)
	LD (HL),C
	INC HL
	LD D,(HL)
	LD (HL),C
	INC HL
	LD A,E
	OR D
	JR Z,RSTRT7
	LD A,(HL)
	LD (DE),A

RSTRT7:	INC HL
	DJNZ RSTRT6
	EX AF,AF'
	EXX
	PUSH HL
	PUSH DE
	PUSH BC
	PUSH AF
	PUSH IX
	PUSH IY
	LD A,I
	LD B,A
	LD A,R
	LD C,A
	PUSH BC
	JP WARM

;------------------------------------------------------------------------------
; Console in 7 Bits

CI7:	CALL CI
	AND 7FH
	RET

;------------------------------------------------------------------------------

TI:	CALL CI7
	RET Z
	
	INC A
	RET M
	
	DEC A
	CP 0DH
	RET Z
	
	CP 'N'
	RET Z
	
	CP 'n'
	JR Z,TI1
	
	PUSH BC
	LD C,A
	CALL CO
	LD A,C
	POP BC
	CP 'A'-1
	RET C
	
	CP 'z'+1
	RET NC
	
TI1:	AND 05FH
	RET

;------------------------------------------------------------------------------
; Monitor command QUERY
; Ein-und Ausgabe auf Ports

QUERY:	CALL TI
	CP 'O'
	JR Z,BITS2
	
	CP 'I'
	JP NZ,ERROR
	
	CALL EXPR1
	POP BC
	IN E,(C)

	;----------------------------------------------------------------------
	; Einsprung BITS
	
BITS:	LD B,8
	CALL BLK

BITS1:	SLA E
	LD A,'0' SHR 1
	ADC A,A
	LD C,A
	CALL CO
	DJNZ BITS1
	RET

BITS2:	CALL EXPR
	POP DE
	POP BC
	OUT (C),E
	RET

;------------------------------------------------------------------------------
; Monitor command VERFIY
; Vergleich von Speicherbereichen
 
VERIFY:	CALL EXPR3

VERIF1:	LD A,(BC)
	CP (HL)
	JR Z,VERIF2
	
	PUSH BC
	CALL CERR
	POP BC

VERIF2:	INC BC
	CALL HILOX
	JR VERIF1

;------------------------------------------------------------------------------
; IO LOOKUP TABLE

LTBL:	DEFB 'C'
	DEFB 'T'
	DEFB 'V'
	DEFB 'B'
	DEFB 'U'

	DEFB 'R'
	DEFB 'T'
	DEFB 'P'
	DEFB 'C'
	DEFB 'U'

	DEFB 'P'
	DEFB 'T'
	DEFB 'P'
	DEFB 'C'
	DEFB 'U'

	DEFB 'L'
	DEFB 'T'
	DEFB 'V'
	DEFB 'L'
	DEFB 'U'

;------------------------------------------------------------------------------

EXIT:	POP BC
	LD A,C
	LD R,A
	LD A,B
	LD I,A
	POP IY
	POP IX
	POP AF
	POP BC
	POP DE
	POP HL
	EX AF,AF'
	EXX
	POP DE
	POP BC
	POP AF
	POP HL
	LD SP,HL
	NOP
	LD HL,0
	JP 0

;------------------------------------------------------------------------------

	DEFW 0
	DEFB 0
	DEFW 0
	DEFB 0  	;TRAP AREA

ENDX:

ALOC	EQU 15H
BLOC	EQU 13H
CLOC	EQU 12H
DLOC	EQU 11H
ELOC	EQU 10H
FLOC	EQU 14H
HLOC	EQU 31H
LLOC	EQU 30H
PLOC	EQU 34H
SLOC	EQU 17H
TLOC	EQU 35H
TLOCX	EQU 25H
LLOCX	EQU 20H

APLOC	EQU 9
BPLOC	EQU 0BH
CPLOC	EQU 0AH
DPLOC	EQU 0DH
EPLOC	EQU 0CH
FPLOC	EQU 8
HPLOC	EQU 0FH
LPLOC	EQU 0EH
XLOC	EQU 7
YLOC	EQU 5
RLOC	EQU 2
ILOC	EQU 3

;------------------------------------------------------------------------------
; TABELLE

ACTBL:	DEFB 'A',ALOC OR 0
	DEFB 'B',BLOC OR 0
	DEFB 'C',CLOC OR 0
	DEFB 'D',DLOC OR 0
	DEFB 'E',ELOC OR 0
	DEFB 'F',FLOC OR 0
	DEFB 'H',HLOC OR 0
	DEFB 'L',LLOC OR 0
	DEFB 'M',HLOC OR 0C0H
	DEFB 'P',PLOC OR 080H
	DEFB 'S',SLOC OR 080H
	DEFB 'I',ILOC OR 0
	DEFB 0C1H

PRMTB:	DEFB 'A',APLOC OR 0
	DEFB 'B',BPLOC OR 0
	DEFB 'C',CPLOC OR 0
	DEFB 'D',DPLOC OR 0
	DEFB 'E',EPLOC OR 0
	DEFB 'F',FPLOC OR 0
	DEFB 'H',HPLOC OR 0
	DEFB 'L',LPLOC OR 0
	DEFB 'M',HPLOC OR 0C0H
	DEFB 'X',XLOC  OR 080H
	DEFB 'Y',YLOC  OR 080H
	DEFB 'R',RLOC  OR 0
	DEFB 0C1H

LASTMON:
	DEFB 0 	; LAST STORAGE

	.DEPHASE

	END 

;------------------------------------------------------------------------------
